### ISSUE TITLE
Study filter for list evaluations

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#1000]
We need a filter to return all the evaluations for a given study.
For instance:
/evaluation/list/study/99

should return all the evaluations for study 99

**Comment by sahithyaravi1493** [comment]
Jan added a filter for study yesterday. I think we can close this issue.

**Comment by janvanrijn** [comment]
Python API is also already updated, and reviewed by @mfeurer , will hopefully be merged this week

**Comment by joaquinvanschoren** [comment]
Was merged.
