### ISSUE TITLE
Test server down?

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#1003]
Can be test by visiting test.openml.org or `ping test.openml.org`.

**Comment by joaquinvanschoren** [comment]
I can't ssh either, maybe a networking issue. Will try to fix asap.

**Comment by joaquinvanschoren** [comment]
It's back

**Comment by mfeurer** [comment]
Thanks a lot!

**Comment by janvanrijn** [comment]
What was the problem?

**Comment by joaquinvanschoren** [comment]
The power went down in the computer science building.
The production server didn't have that problem because it's in a data center.
