### ISSUE TITLE
Split files on the test server are invalid ARFF

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#1019]
Since recently (I guess today since [PR1002](https://github.com/openml/OpenML/pull/1002)), the split files on the test server are invalid ARFF in the sense that they define five attributes, but only have four attributes per instance:
```
@relation diabetes_splits

@attribute type {TRAIN,TEST}
@attribute rowid numeric
@attribute repeat numeric
@attribute fold numeric
@attribute sample numeric

@data
TRAIN,455,0,0
TRAIN,242,0,0
```
See for example [here](https://test.openml.org//api_splits/get/801/Task_801_splits.arff).

**Comment by janvanrijn** [comment]
basically, I made a huge refactor to the code in May, but forgot to differentiate for learning curve tasks. 

this was unnoticed, as all openml servers have a caching mechanism on datasplits, saving them from generating the splits over and over again. yesterday I deleted the cache directory, making this error appear. 

I fixes the bug. I will replace the eval engine later today.

**Comment by mfeurer** [comment]
This appears to be fixed, thanks a lot!
