### ISSUE TITLE
DB snapshots not available

### ISSUE THREAD

**Issue by wendli01** [openml/OpenML#1043]
DB snapshots for local installation are not available.

 [https://www.openml.org/guide/developers](https://www.openml.org/guide/developers), which is listed as a resource for the databases in the [Local Installation Docs](https://docs.openml.org/Local-Installation/#databases), returns a 404.

**Comment by joaquinvanschoren** [comment]
Thanks, I updated to the correct link:
https://docs.openml.org/developers/

**Comment by wendli01** [comment]
Unfortunately, the link is broken again. I think it should point to [docs.openml.org/resources](https://docs.openml.org/resources/).
However, the current [Nightly database SNAPSHOT](https://www.openml.org/downloads/ExpDB_SNAPSHOT.sql.gz) listed there only contains an empty `ExpDB_SNAPSHOT.sql` file.
Can you maybe update it @joaquinvanschoren ?
