### ISSUE TITLE
Cannot delete dataset associated with flow created automatically

### ISSUE THREAD

**Issue by marcoslbueno** [openml/OpenML#1050]
#### Description

Hi, 

I uploaded a dataset via the python API (https://www.openml.org/d/42453) and after a few days a task (https://www.openml.org/t/233078) was associated to it. I guess the task was created automatically (by a bot, for example). When I try to delete this dataset I get the error 354 'Dataset is in use by other content. Can not be deleted'. Then, I tried to delete the associated task, but I cannot do so (no remove button is shown to me).

Not sure this is a bug, or just the way I'm trying to delete the dataset.

**Comment by joaquinvanschoren** [comment]
@marcoslbueno: Were you logged in? I could simply remove the task (just did). 

@mfeurer: Is it possible that there is no task deletion function in the Python API? I couldn't find it?

**Comment by marcoslbueno** [comment]
@joaquinvanschoren Yes, I was logged in. The way I was trying to delete the task was probably wrong I guess? Thanks anyway, I could now delete the dataset.

**Comment by LucaUrbinati44** [comment]
@marcoslbueno How did you manage to delete a dataset? I don't find any instruction about it. Thank you

**Comment by joaquinvanschoren** [comment]
@PGijsbers is this supported by the Python API now?

**Comment by PGijsbers** [comment]
I am currently working on the PR to allow people to delete any of their uploaded OpenML entities, including datasets. I hope to finish it next week.

**Comment by LucaUrbinati44** [comment]
I found this function by looking at the source code of OpenML (in the documentation there is nothing about it) and it works:
```
# Remove dataset
openml.utils._delete_entity("data", <your_dataset_id>)
```

**Comment by PGijsbers** [comment]
Yes, the PR is just to make documented functions and better error messaging surrounding that function: #1060
