### ISSUE TITLE
Is the OpenML webpage down?

### ISSUE THREAD

**Issue by FelixNeutatz** [openml/OpenML#1057]
Dear all,

is it possible that the OpenML webpage is down?
![Selection_032](https://user-images.githubusercontent.com/5217389/88139506-1dc10500-cbf0-11ea-88c7-f04f7ab6ecf5.png)

Best regards,
Felix

**Comment by FelixNeutatz** [comment]
seems to be running again :)

**Comment by janvanrijn** [comment]
Thanks for reporting this! 

We had some additional hardware installed which incurred some downtime, but everything is running again.
