### ISSUE TITLE
Error with creating supervised regression task

### ISSUE THREAD

**Issue by marcoslbueno** [openml/OpenML#1065]
There seems to be a problem with the python API when uploading a task for supervised regression. 

**Example:**
```
import openml
from openml.datasets.functions import create_dataset

data_id = 42688
dataset = openml.datasets.get_dataset(data_id)


tasktypes = openml.tasks.TaskTypeEnum
my_task = openml.tasks.create_task(
    task_type_id = tasktypes.SUPERVISED_REGRESSION,
    dataset_id = data_id,
    target_name = dataset.default_target_attribute,
    estimation_procedure_id = 7)


my_task.publish()
```

**Error:**
    
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openml/base.py", line 129, in publish
    response_text = openml._api_calls._perform_api_call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openml/_api_calls.py", line 53, in _perform_api_call
    return _read_url_files(url, data=data, file_elements=file_elements)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openml/_api_calls.py", line 86, in _read_url_files
    raise _parse_server_exception(response, url, file_elements=file_elements)
openml.exceptions.OpenMLServerException: Input value does not match allowed values in foreign column. - problematic input: [target_feature], acceptable inputs: [city, floor, animal, furniture]

```

**Python modules:**
Python 3.8.5
openml 0.10.2

**Comment by mfeurer** [comment]
Hey, two brief questions:
* what's estimation ID 7?
* why do you need to pass an estimation ID?

**Comment by PGijsbers** [comment]
It's the [estimation procedure](https://openml.org/api/v1/json/estimationprocedure/list), 7 corresponds to 10-fold cross-validation.

**Comment by PGijsbers** [comment]
Ah, it looks like `7` it might be 10-fold cross-validation for regression. Perhaps using `1` instead works (it's for classification, and will take stratified splits).

**Comment by marcoslbueno** [comment]
Thanks @mfeurer , @PGijsbers for replying..
It seems that `1` for estimation_procedure does not work for regression: 

`openml.exceptions.OpenMLServerException: Input value does not match allowed values in foreign column. - problematic input: [estimation_procedure], acceptable inputs: [7, 8, 9, 10, 11, 12, 24, 27]`

**Comment by PGijsbers** [comment]
Sorry, I should learn to read 😢 `7` does look like it should be the right estimation procedure.
It looks like the error is complaining about the target feature, which you have set to `dataset.default_target_attribute`. This corresponds to `"total_(BRL)"`. The server says that `[city, floor, animal, furniture]` are the only valid values however, which are exactly the only `nominal` features of this dataset. Considering you are trying to create a regression task (and set the task type accordingly) it might be a server-side issue.

**Comment by PGijsbers** [comment]
I checked locally, the xml generated and sent by `openml-python` is:
```xml
<oml:task_inputs xmlns:oml="http://openml.org/openml">
	<oml:task_type_id>2</oml:task_type_id>
	<oml:input name="source_data">42688</oml:input>
	<oml:input name="estimation_procedure">7</oml:input>
	<oml:input name="target_feature">total_(BRL)</oml:input>
</oml:task_inputs>
```
which looks perfectly ok to me. I was able to create the task through the (old) website: https://www.openml.org/t/317612.
The task XML:
```xml
<oml:task>
    <oml:task_id>317612</oml:task_id>
    <oml:task_name>
        Task 317612: Brazilian_houses (Supervised Regression)
    </oml:task_name>
    <oml:task_type_id>2</oml:task_type_id>
    <oml:task_type>Supervised Regression</oml:task_type>
    <oml:input name="source_data">
        <oml:data_set>
            <oml:data_set_id>42688</oml:data_set_id>
            <oml:target_feature>total_(BRL)</oml:target_feature>
        </oml:data_set>
    </oml:input>
    <oml:input name="estimation_procedure">
        <oml:estimation_procedure>
            <oml:id>7</oml:id>
            <oml:type>crossvalidation</oml:type>
            <oml:data_splits_url>
                https://www.openml.org//api_splits/get/317612/Task_317612_splits.arff
            </oml:data_splits_url>
            <oml:parameter name="number_repeats">1</oml:parameter>
            <oml:parameter name="number_folds">10</oml:parameter>
            <oml:parameter name="percentage"/>
        </oml:estimation_procedure>
    </oml:input>
    <oml:input name="evaluation_measures">
        <oml:evaluation_measures>
            <oml:evaluation_measure/>
        </oml:evaluation_measures>
    </oml:input>
    <oml:output name="predictions">
        <oml:predictions>
            <oml:format>ARFF</oml:format>
            <oml:feature name="repeat" type="integer"/>
            <oml:feature name="fold" type="integer"/>
            <oml:feature name="row_id" type="integer"/>
            <oml:feature name="prediction" type="string"/>
        </oml:predictions>
    </oml:output>
</oml:task>
```
So the fields that `openml-python`  provided matches with what the server generates when asked to create the task.
Also of note that if I know execute the python script again to create the task, I still get the same error.
I do not get the error that the task already exists.
 
On the test server I can create a regression task for a different dataset ([`d/471891`](https://test.openml.org/d/47189)), where `openml-python` generates xml:
```xml
<oml:task_inputs xmlns:oml="http://openml.org/openml">
	<oml:task_type_id>2</oml:task_type_id>
	<oml:input name="source_data">47189</oml:input>
	<oml:input name="estimation_procedure">7</oml:input>
	<oml:input name="target_feature">SalePrice</oml:input>
</oml:task_inputs>
```

Trying to create the task again gives the correct error message that the task already exists.

If I would have to guess, it actually has to do with the target column which contain parentheses. This is pure speculation based on the observation that creating the task on another dataset (albeit on the test server) works. That said, I have no idea how to navigate the server code, so I would appreciate it if someone more familiar could have a look at it @joaquinvanschoren .

**Comment by marcoslbueno** [comment]
However, I actually managed to create the task in the **test server** (see https://test.openml.org/t/23782). I didn't change the names of the columns.

So, this looks like an issue in the (old) website.

**Comment by joaquinvanschoren** [comment]
This was fixed today. There was a bad setting on the production server.
