### ISSUE TITLE
Using get_csv from openML data api

### ISSUE THREAD

**Issue by prabhant** [openml/OpenML#1066]
Hi everyone,
I wanted to ask if get_csv call from openml data api is being used in sklearn or openml-python?
https://www.openml.org/api_data_docs#!/data/get_get_csv_id

cc @joaquinvanschoren @amueller @mfeurer

**Comment by mfeurer** [comment]
I'm not aware about us using it in openml-python.

**Comment by amueller** [comment]
sklearn uses these endpoints:
```python
_OPENML_PREFIX = "https://openml.org/"
_SEARCH_NAME = "api/v1/json/data/list/data_name/{}/limit/2"
_DATA_INFO = "api/v1/json/data/{}"
_DATA_FEATURES = "api/v1/json/data/features/{}"
_DATA_QUALITIES = "api/v1/json/data/qualities/{}"
_DATA_FILE = "data/v1/download/{}"
```
right now, at least.

**Comment by joaquinvanschoren** [comment]
@prabhant can we close this?

**Comment by prabhant** [comment]
yes
