### ISSUE TITLE
Update and test 'new flow' form on website

### ISSUE THREAD

**Issue by aydindemircioglu** [openml/OpenML#107]
i specified a .png and a .txt file there, but the form does not accept it.
is there any format check? if so, it is not specified anywhere?

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<oml:error xmlns:oml="http://openml.org/openml">
oml:code162/oml:code
oml:messagePlease provide source or binary file/oml:message
/oml:error

**Comment by joaquinvanschoren** [comment]
We removed manual flow upload a while ago. We are working on better ways to do this (e.g. github integration)
