### ISSUE TITLE
Adding `run_details` does not work (?)

### ISSUE THREAD

**Issue by PGijsbers** [openml/OpenML#1087]
I was working on `openml-python` and noticed that we did not support `run_details` as per the [xsd](https://github.com/openml/OpenML/blob/develop/openml_OS/views/pages/api_new/v1/xsd/openml.run.upload.xsd). I tried to fix this, however uploaded runs don't seem to have stored `run_details` despite a fix.

I tried uploading an xml through the API test site (https://www.openml.org/api_docs#!/run/post_run) but it kept processing the run and never showed a reply. However I did initially get errors from the server that the `run_details` I had passed were invalid, so I am fairly confident we are at least sending correct xml since I fixed that (using `openml-python/fix_1013`).

Can you confirm/deny whether or not `run_details` is stored on the server if it is provided in the xml?

**Comment by PGijsbers** [comment]
@joaquinvanschoren @janvanrijn

**Comment by joaquinvanschoren** [comment]
Should work now. Can you please check and close if everything is ok?

**Comment by PGijsbers** [comment]
I uploaded a run with `run_details` (see xml below). When I download the run, the  [`xml`](https://www.openml.org/api/v1/run/10559894) does not contain `run_details`.

1. Is this fix live on the production server or the test server?
2. If it's the production server, then the problem is not (entirely) solved. You'd have to check if `run_details` is stored, and if so just make sure it is also returned on a `get` request. If it's only on the test server I'd have to run a separate check (and modify my script).

Uploaded XML uploaded to production server:
```xml
<oml:run xmlns:oml="http://openml.org/openml">
	<oml:task_id>2079</oml:task_id>
	<oml:flow_id>18817</oml:flow_id>
	<oml:setup_string>runbenchmark.py constantpredictor validation 1h4c</oml:setup_string>
	<oml:run_details>Custom:Hyperparameter</oml:run_details>
	<oml:parameter_setting>
		<oml:name>max_runtime_seconds</oml:name>
		<oml:value>3600</oml:value>
		<oml:component>18817</oml:component>
	</oml:parameter_setting>
	<oml:parameter_setting>
		<oml:name>max_mem_size_mb</oml:name>
		<oml:value>15990</oml:value>
		<oml:component>18817</oml:component>
	</oml:parameter_setting>
	<oml:parameter_setting>
		<oml:name>cores</oml:name>
		<oml:value>4</oml:value>
		<oml:component>18817</oml:component>
	</oml:parameter_setting>
	<oml:parameter_setting>
		<oml:name>seed</oml:name>
		<oml:value>1478377729</oml:value>
		<oml:component>18817</oml:component>
	</oml:parameter_setting>
	<oml:tag>amlb</oml:tag>
</oml:run>
```


XML returned by REST API:
```xml
<oml:run>
<oml:run_id>10559895</oml:run_id>
<oml:uploader>869</oml:uploader>
<oml:uploader_name>Pieter Gijsbers</oml:uploader_name>
<oml:task_id>2079</oml:task_id>
<oml:task_type>Supervised Classification</oml:task_type>
<oml:flow_id>18817</oml:flow_id>
<oml:flow_name>amlb_constantpredictor(3)</oml:flow_name>
<oml:setup_id>8276342</oml:setup_id>
<oml:setup_string>runbenchmark.py constantpredictor validation 1h4c</oml:setup_string>
<oml:parameter_setting>
<oml:name>max_runtime_seconds</oml:name>
<oml:value>3600</oml:value>
<oml:component>18817</oml:component>
</oml:parameter_setting>
<oml:parameter_setting>
<oml:name>max_mem_size_mb</oml:name>
<oml:value>15990</oml:value>
<oml:component>18817</oml:component>
</oml:parameter_setting>
<oml:parameter_setting>
<oml:name>cores</oml:name>
<oml:value>4</oml:value>
<oml:component>18817</oml:component>
</oml:parameter_setting>
<oml:parameter_setting>
<oml:name>seed</oml:name>
<oml:value>1478377729</oml:value>
<oml:component>18817</oml:component>
</oml:parameter_setting>
<oml:tag>amlb</oml:tag>
<oml:input_data>
<oml:dataset>
<oml:did>188</oml:did>
<oml:name>eucalyptus</oml:name>
<oml:url>
https://www.openml.org/data/download/3625/dataset_194_eucalyptus.arff
</oml:url>
</oml:dataset>
</oml:input_data>
<oml:output_data>
<oml:file>
<oml:did>-1</oml:did>
<!--
 Deprecated field, will be removed during next upgrade. 
-->
<oml:file_id>22045578</oml:file_id>
<oml:name>description</oml:name>
<oml:url>
https://www.openml.org/data/download/22045578/description.xml
</oml:url>
</oml:file>
<oml:file>
<oml:did>-1</oml:did>
<!--
 Deprecated field, will be removed during next upgrade. 
-->
<oml:file_id>22045579</oml:file_id>
<oml:name>predictions</oml:name>
<oml:url>
https://www.openml.org/data/download/22045579/predictions.arff
</oml:url>
</oml:file>
</oml:output_data>
</oml:run>
```

**Comment by sahithyaravi** [comment]
@PGijsbers  Its not available yet on any server (test/production).  Will pull and test tomorrow :)

**Comment by sahithyaravi** [comment]
@PGijsbers  could you check if it is fixed now? Here is what I get https://www.openml.org/api/v1/run/10559896. So run_details seem to be added

**Comment by PGijsbers** [comment]
From a very minimal test (uploading a new xml with a simple `run_details` string) it looks like it works now 👍
I'll close the issue now. I probably will try it more extensively towards the end of the week. If any issues do arise I'll re-open or create a new issue (depending on which is more appropriate). Thanks a lot!
