### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#110]
Hi,

I need a testaccount so I can write unit tests for uploading stuff.

1) I created an account with one of my personal Email-addresses and stumbled over the word "Username" in the login form -- how can I set a username? I couldn't find this anywhere. 

2) Is there a possibility to delete all of the testaccount's runs and flows via API call or something like that? This would be great because unit tests could always start with a "fresh" account. 

Thanks in advance.

**Comment by berndbischl** [comment]
This is a REALLY important issue, as it concerns all testing and development. any news here?

**Comment by mfeurer** [comment]
@joaquinvanschoren is this still open since we have [http://test.openml.org](http://test.openml.org)/[http://capa.win.tue.nl](http://capa.win.tue.nl)?

**Comment by joaquinvanschoren** [comment]
This is running for a while now
