### ISSUE TITLE
Server/Database down?

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#1103]
Hi together,

I'm having the impression that currently the server or the database is down. This is manifested by the website not showing any dataset information (i.e. it only shows menus), scikit-learn's OpenML fetcher returns only errors, and the API also gives database errors (see https://www.openml.org/api/v1/data/2).

**Comment by joaquinvanschoren** [comment]
We're getting a very high number of connections at the same time. I'm looking at it now.

**Comment by joaquinvanschoren** [comment]
Everything back to normal now. I'll keep an eye on it.

**Comment by joaquinvanschoren** [comment]
Everything is stable again. Closing this for now but will keep an eye on it. Thanks for reporting!
