### ISSUE TITLE
Datasplit for task 360112, 359929 is incomplete

### ISSUE THREAD

**Issue by PGijsbers** [openml/OpenML#1109]
The split file for tasks 359929  and 360112 stops midway through a data line.
Link to split file (warning: 55mb): https://www.openml.org//api_splits/get/360112/Task_360112_splits.arff
Link to other split file (warning: 780mb): https://www.openml.org//api_splits/get/359929/Task_359929_splits.arff

Could be related to #1108, first raised in [amlb#318](https://github.com/openml/automlbenchmark/issues/318).

Header of file, and data content from line 2463694 onwards:
```
@relation KDDCup99_splits

@attribute type {TRAIN,TEST}
@attribute rowid numeric
@attribute repeat numeric
@attribute fold numeric

@data
[skip to line 2463694]
TRAIN,3488085,0,0
TRAIN,4701175,0,0
TRAIN,4585614,0,0
TRAIN,523997,0,0
TRAIN,638
```
For the other one, similarly at line 45100636:
```
TRAIN,9132207,0,4
TRAIN,
```

**Comment by joaquinvanschoren** [comment]
Seems that this is related to the size of the split files. Is it possible that the download gets interrupted?

**Comment by PGijsbers** [comment]
I assume it's possible, though I do think I managed to download them to completion before (I'm fairly sure benchmark users used these tasks in the past, and I have tested them as well).

**Comment by joaquinvanschoren** [comment]
wget https://www.openml.org//api_splits/get/360112/Task_360112_splits.arff also returns an incomplete file.

**Comment by PGijsbers** [comment]
Removing the data split from the server cache allowed the split to be regenerated and downloadable.
The section
```
TRAIN,3488085,0,0
TRAIN,4701175,0,0
TRAIN,4585614,0,0
TRAIN,523997,0,0
```
is present but at a different line. I am not sure what the cause is. The fact that these lines at least appear in the same order together makes me hopeful the actual splits are still identical.

**Comment by PGijsbers** [comment]
The issue remains for task `359929`

**Comment by PGijsbers** [comment]
The issue seems to be resolved for `359929` right now as well. I'll suppose we can close the issue for now, though changes need to be made to guarantee long-term stability. Adding to #1110 the `v2` API might be enough.
