### ISSUE TITLE
Spelling of evaluation measures

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#111]
There's always underscores ("_") in the official list of evaluation measures:

http://openml.org/api/?f=openml.evaluation.measures

BUT in the actual tasks they or at least many of them are written with spaces instead, e.g.:

http://openml.org/api/?f=openml.tasks.search&task_id=1

My question is: Are there exceptions or are they always written with spaces? If spaces AND underscores are ok, I need to know :)

My advice would be to adjust the spellings.

**Comment by joaquinvanschoren** [comment]
has been fixed. use underscores everywhere
