### ISSUE TITLE
503 error, API is down

### ISSUE THREAD

**Issue by mkyl** [openml/OpenML#1115]
#### Description
It seems the API is down, I get a HTTP 503 error when trying to access the JSON api or the web interface.

#### Steps/Code to Reproduce
Visit https://www.openml.org/t/168868 and https://www.openml.org/t/168868/json  (for example).

#### Expected Results

HTTP 200 and a JSON payload.
#### Actual Results
HTTP 503

**Comment by joaquinvanschoren** [comment]
Thanks for reporting it. The API is up again.

**Comment by mkyl** [comment]
Thanks!
