### ISSUE TITLE
DB snapshot not available

### ISSUE THREAD

**Issue by wendli01** [openml/OpenML#1116]
Unfortunately, the link is broken again. I think it should point to [docs.openml.org/resources](https://docs.openml.org/resources/).
However, the current [Nightly database SNAPSHOT](https://www.openml.org/downloads/ExpDB_SNAPSHOT.sql.gz) listed there only contains an empty `ExpDB_SNAPSHOT.sql` file.
Can you maybe update it @joaquinvanschoren ?

_Originally posted by @wendli01 in https://github.com/openml/OpenML/issues/1043#issuecomment-883351139_

**Comment by joaquinvanschoren** [comment]
Apologies, fixed now!
The nightly snapshots should also be automatically refreshing again.

**Comment by wendli01** [comment]
Looks good now, thank you!
