### ISSUE TITLE
Unable to access datasets.

### ISSUE THREAD

**Issue by SachiniEMSPE** [openml/OpenML#1134]
Hi all, 

Thank you so much for your great work! I was using the datasets without any issue. However, today I noticed that it is unable to access any of the datasets.  I'm getting 0 results as attached every time I try to search for a dataset. Seems like the website is not working.
![image](https://user-images.githubusercontent.com/48669988/147779124-ae4340a3-675a-4466-beda-67fe1c08a015.png)
 I was wondering that is the server or the dataset database is down.  It would be great if you could help with this. 
Thank you!

**Comment by joaquinvanschoren** [comment]
Apologies. They are back now!

**Comment by SachiniEMSPE** [comment]
No worries. Thank you so much for the prompt response!
