### ISSUE TITLE
New Task Type: Survival Analysis

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#114]
Hey, 

as you hopefully know, I want to write my master's thesis about the integration of survival analysis in OpenML. Therefore, I need some help:

* **New task type** Survival Analysis, having a parameter "censoring" with possible values "left"/"right"/"interval". There are different possible notations in survival data sets. In mlr, we use only two: For left or right censored data, there are the target columns "time" and "event". For interval censored data, there is "time1" and "time2", defining an interval in which the event happened. I suggest that we stick to this so we have the same shape in each data set. 

* **Measures**. We have only one measure, the so-called C-Index, giving some kind of non-parametric correlation between the linear predictors (i.e., the predictions) and the real event times. We could compute this locally and pass it to the server for now, later it'd be cool if the server could compute this. We do have C code for this, which might make it easier for you to implement?

Is there anything I'm missing? Do you see any problems or disagree with anything? It'd be nice if we could set this up as soon as possible.

Thank you very much in advance!

**Comment by berndbischl** [comment]
@dominikkirchhoff 

This is important for you please respond here

**Comment by dominikkirchhoff** [comment]
Unfortunately, I can't download the data set. This text is in the .arff-file:

```
403 Forbidden
You don't have the right access rights to view this page.
```

Also, the default target attribute shouldn't be `C20orf46`, but `time` and `event`, I guess.

**Comment by joaquinvanschoren** [comment]
This turned out to be a fluke with the data file having bad permissions. Now corrected. I have also set the default target attributes as you suggested. They were correct in the task though.
