### ISSUE TITLE
Parquet files don't have ignore and row id columns

### ISSUE THREAD

**Issue by sebffischer** [openml/OpenML#1152]
So it seems to, that the parquet files are missing the `is_row_identifier` and `is_ignore` columns, at least for the two examples provided below. 

* For the  *ignore* column compare dataset 210
* For the *row identifier* compare dataset 8

**Comment by joaquinvanschoren** [comment]
Those should be in the dataset meta-data, not in the parquet file itself (they are also not in the ARFF file).
