### ISSUE TITLE
Datasets created since 26/06 are still in preparation

### ISSUE THREAD

**Issue by LeoGrin** [openml/OpenML#1157]
I was able to quickly upload datasets in the past, but now they seem to stay stuck "in preparation". Checking all uploaded datasets, it seems that those created since 26/06/2022 are still "in preparation". [Example 1](https://www.openml.org/search?type=data&sort=date&status=any&order=desc&id=44101), [example 2](https://www.openml.org/search?type=data&sort=date&status=any&order=desc&id=44148).

Some of these datasets are mine, and were uploaded through the Python API.

Thanks for your help :)

**Comment by joaquinvanschoren** [comment]
I believe this issue was already fixed. The two examples are verified and I also checked the latest ones, they are all verified.
Do you still see an issue or can we close this?

**Comment by LeoGrin** [comment]
Yes it seems to be fixed, thanks!
