### ISSUE TITLE
Use secure connection to authenticate

### ISSUE THREAD

**Issue by mllg** [openml/OpenML#119]
Please enable https for the website and API, at least for sign up and authenticate steps.

**Comment by joaquinvanschoren** [comment]
We're working on the API keys. We have removed the time limit from the session hash, so you can use them as an API key. There will soon be a new authenticate methods and we'll update the current username/password authentication to return your unique API key. Then we need to add a web form to request an API key. 

Do we really need read-only API keys? Can you give a scenario where users cannot be expected to create their own key and your own key cannot be hidden? A public read-only key can just be used by anyone, right?

**Comment by mllg** [comment]
> We're working on the API keys. We have removed the time limit from the session hash, so you can use them as an API key. There will soon be a new authenticate methods and we'll update the current username/password authentication to return your unique API key. Then we need to add a web form to request an API key.

Great! Please keep in mind that sometimes you need to revoke an API key.


> Do we really need read-only API keys? Can you give a scenario where users cannot be expected to create their own key and your own key cannot be hidden? A public read-only key can just be used by anyone, right?

A public r/o key is sufficient.

**Comment by joaquinvanschoren** [comment]
We have API keys and read-only keys now.
We still need to move to https. I think it is easier and safer to move the entire site to https, rather than only the API.

**Comment by joaquinvanschoren** [comment]
This is done. 🎉
