### ISSUE TITLE
HTTP error codes

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#124]
Currently, the API returns always the http error code 200. This makes checking the server's answer unnecesarrily cumbersome. To overcome this,  @janvanrijn and I decided that the following error codes would be useful:
- 200: The called function returned the requested xml
- 401: Not authorization hash sent with the request
- 4??: The called function doesn't exist
- 4??: The API call was wrongly invoked

**Comment by joaquinvanschoren** [comment]
@janvanrijn What is the status here?

**Comment by mfeurer** [comment]
Closing this now as the way it is currently handled works and there's not really a need to change it.
