### ISSUE TITLE
Support for tuning studies

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#129]

**Comment by janvanrijn** [comment]
Correct format for uploading traces:
http://www.openml.org/data/download/2035727/optimization_trace6946920946676621819.arff
The following fields are mandatory: repeat, fold, iteration, evaluation and selected. Furthermore, all fields that involve an optimized parameter are indicated with the prefix "parameter_" (in line with my email from May 24). All other fields are facultative.

**Comment by joaquinvanschoren** [comment]
Done. Documentation needed.

**Comment by janvanrijn** [comment]
I am still a bit confused about where or how to document this? In the [Wiki](https://github.com/openml/OpenML/wiki/Run-Uploading/)? or on the [doc-page](https://docs.openml.org/developers/)? 

There seems to be a wiki item but no item on the frontend

**Comment by janvanrijn** [comment]
Anyway, I added some description to the wiki. @joaquinvanschoren @amueller @mfeurer @giuseppec  can you check if this description is clear?

**Comment by amueller** [comment]
seems relatively clear, but I haven't used them, so maybe @mfeurer can talk about it more. Also, if it's part of the server, it shouldn't be in the wiki but in the API docs, right? Or maybe rather in the (non-existant) schema docs?

**Comment by mfeurer** [comment]
Looks to me. Regarding the arff, doesn't that require the correct solution, too? I agree with Andy that this document should be in the docs, for example as a new section in [the developer section](https://openml.github.io/OpenML/developers/).

**Comment by janvanrijn** [comment]
Closing for now, please reopen if there are questions.
