### ISSUE TITLE
Support for feature selection studies

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#131]

**Comment by amueller** [comment]
I'm not sure what this issue is about. You can definitely do feature selection using sklearn / the python API right now within a supervised task (actually the default model that @janvanrijn is using contains feature selection).

**Comment by berndbischl** [comment]
and how is the result stored on openml?

**Comment by amueller** [comment]
Ah, sorry, they are not stored. It's getting late over here ;)
They are stored in the model, but the model is not stored in the run. The way sklearn is set up it would be quite difficult / odd to store the selected features but not the whole model with all processing steps.

Feature selection can be at any point in the processing pipeline, right?

**Comment by joaquinvanschoren** [comment]
There are different use cases here:
* Feature selection studies. Here, people want to see how well different feature selection techniques work. Typically this is done by doing feature selection and then evaluating a (kNN) model built on them. A separate task for this would be good, but for most studies it's already sufficient to include the selected features in classification/regression task, since you usually build a model on it afterwards to evaluate the feature set.
* Simply look up which features were selected by the previous steps in a pipeline. Imagine that a model makes weird predictions: you may want to look up which features it was actually trained with - maybe the feature selection removed an important one. More generally, you want to trace back how a specific feature (fed to the classifier) was constructed by the pipeline.

Ideally we'd keep a trace of how the data changes throughout the pipeline, stored in the run. I'm not sure how easy that would be in sklearn or mlr.

Storing the model is even more important in my opinion. We already do this for all WEKA runs (WEKA has a model (de)serializer). If we could (optionally) store sklearn/mlr models, runs would definitely become more reusable. Also see https://github.com/openml/discussionboard/issues/11

**Comment by joaquinvanschoren** [comment]
Closing stale issues
