### ISSUE TITLE
Upload datasets from R package

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#148]
There's a nice R package with datasets:
http://stat.ethz.ch/R-manual/R-patched/library/datasets/html/00Index.html

Most are new to OpenML, except for Iris of course. Maybe we could 'stress test' the openml package by uploading all of these to OpenML? You can always edit the descriptions (e.g. target features) afterwards through the website.

**Comment by berndbischl** [comment]
Added to wiki data repo list, closing here
