### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by DraXus** [openml/OpenML#150]
In order to increase user participation and loyalty, we can include some badges to user profile such as "Great contributor of datasets" (if you submit more than 100 datasets), or "Weka enthusiastic" (if you submit 100 runs using Weka flows).

If you think that it is interesting, we can elaborate a list of possible badges.

**Comment by joaquinvanschoren** [comment]
Has been done. May still need tweaking. Please open more specific issues for that.
