### ISSUE TITLE
getting task/data status

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#151]
Hi,

I'd really appreciate one or two API calls to quickly retrieve the status (in preparation, active, deactivated) of a task or data set. 

Thanks in advance!

**Comment by dominikkirchhoff** [comment]
Hi, a small question: can a task's status differ from the related data set's status, or is the task status always equal to the data set status?

**Comment by dominikkirchhoff** [comment]
Yesterday we talked about this and came to the conclusion that **one** of the following is necessary:

1. Quick API calls to retrieve the current status of a task or data set.
2. Let a task or data set ID be optionally (!) handed over to the list-functions openml.tasks/openml.data so only the corresponding row is returned.

It's important that either of these is **efficient**. At the moment, we *can* retrieve a status, but it takes too long to do it before each download.

**Comment by berndbischl** [comment]
Why not do basically option 2. 

the "list" class include the status, and they can be restricted by passing a list of ids.

This seems easy, and very flexible?

**Comment by joaquinvanschoren** [comment]
this is now added to openml.data and openml.tasks. Question: do you even NEED deactivated / inpreparation datasets/tasks? Or are you always to filter those out anyway?

**Comment by joaquinvanschoren** [comment]
we added a flag 'active_only' Use that to only get the active ones. Will close after documentation is added.

**Comment by dominikkirchhoff** [comment]
We don't need anything else but active data sets, so the 'active_only' flag makes sense. However, this does not help if we have downloaded something that was active as it was cached but is deactivated now. So we need to check for this case quickly when the user accesses the cache.

**Comment by berndbischl** [comment]
> We don't need anything else but active data sets,

I would not be so quick. Maybe in some cases you would like to see more.

**Comment by joaquinvanschoren** [comment]
We now only return active datasets. The status is also returned in all dataset descriptions.
Any reason why you want to get a list of inactive datasets?

**Comment by joaquinvanschoren** [comment]
This is now available via the API and documented.
