### ISSUE TITLE
data types of measures

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#156]
Hey,

would it be possible to add the data types to openml.evaluation.measures (or return them somewhere else)? I need them to easily parse the evaluations correctly.

**Comment by berndbischl** [comment]
What is meant by "data types" here?

**Comment by dominikkirchhoff** [comment]
predictive_accuracy -> numeric, os_information -> character, ... 

... something like this. At the moment, we work around this problem by letting R "guess" the data types, which works for now but is not the 'perfect' solution.

**Comment by joaquinvanschoren** [comment]
We actually have the datatypes in the database but don't return them yet.
https://www.openml.org/api/v1/data/qualities/list

Should we add them? Maybe for API v2?

**Comment by janvanrijn** [comment]
Both evaliations and data qualities are always floats. Sometimes there is array data available (e.g., OS information), which is a horrible feature which we should probably remove or move else-where to semantic meta-data of a run. I will close this issue for now, as the main problem has been re-solved. Feel free to re-open
