### ISSUE TITLE
Datasets from Quandl

### ISSUE THREAD

**Issue by DraXus** [openml/OpenML#157]
I just found Quandl, a huge data repository (10 million datasets): https://www.quandl.com

Copy/paste from the website:
1. Our mission is to make all the numerical data in the world available on this website. We already cover 10 million datasets from 500 sources,
2. We enable our users to get the precise data they need, in the exact format they want. Instant unlimited downloads in any format or via any tool,
3. We support open data. We believe that public data must be free, open, and accessible to all. We promise never to charge for data that is available elsewhere for free,
4. We support commercial data. We believe that data users are entitled to data of the highest quality. Our premium databases set the standard for paid commercial data,
5. We respect data as IP. We believe that data publishers have the right to control the data they create. We empower individuals and organizations to monetize their data expertise,
6. We are an open platform. Anybody can buy, sell, store or share data on Quandl. We will not build walls around data or restrict who can participate in the data economy.

They also provide a quite handy API: https://www.quandl.com/help/api

Did you know about it? Do you think that can be integrated into OpenML somehow?

**Comment by joaquinvanschoren** [comment]
Closing since this is on the wiki now.
