### ISSUE TITLE
Missing API calls

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#158]
Hi,

to get our first version of the R package done, we need the following two API calls:

* openml.flows -> (impl.id, name, ...)
* openml.runs(filter) -> (run.id, task.id, impl.id, ...)*

\* Is it possible to pass some restrictions to the server, such as: return only runs of the following implementations and only on the following tasks, etc.?

We will meet at the end of next of week, and we want to get all the basic things done by then. So, please do this as soon as possible. Thanks in advance!

**Comment by berndbischl** [comment]
Is this done now?

**Comment by berndbischl** [comment]
And documented for the server API?

**Comment by joaquinvanschoren** [comment]
Is it still required that a comma-separated list can be used to  get runs for more than 1 task at once? Otherwise this runs fine. None of this is currently documented, but we will do this asap.

**Comment by joaquinvanschoren** [comment]
added comma-separated list option for task ids

**Comment by joaquinvanschoren** [comment]
Done and (beautifully) documented now:
http://www.openml.org/api_docs/#!/run/get_run_id
