### ISSUE TITLE
caching predictions

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#159]
Hi all,

we are currently caching predictions of runs when we download them (in R). As we want to have the same behaviour over all APIs, we should talk about this. 

1. Does this make sense? E.g., can predictions be manipulated after the first upload? Or is there another reason not to cache them?
2. If we all agree, let's do this. --> Please document here: https://github.com/openml/OpenML/wiki/Client-API and implement in all the programming APIs.

**Comment by berndbischl** [comment]
@dominikkirchhoff 
You have your answer, please document it in the global wiki, then either implement it in R or open a issue in our tracker

**Comment by dominikkirchhoff** [comment]
It's already implemented, but I don't have the rights to edit the global wiki.

**Comment by berndbischl** [comment]
@dominikkirchhoff  @joaquinvanschoren 
Joaquin will give you rights now

**Comment by joaquinvanschoren** [comment]
Done
