### ISSUE TITLE
Improve data format description by marking sparse .arff files

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#162]
Would anyone except me benefit from knowing that an .arff file is sparse before downloading it?

**Comment by berndbischl** [comment]
Again, +1 from me

**Comment by berndbischl** [comment]
I should be possible to auto-compute whether a file is sparse. 
This should be listed in the regaular data_qualities as well.
I guess it should be possible to check this with this regexp, when you look at the first line of the @DATA section
```
  ^\s*\{.*\}\s*$
```

**Comment by joaquinvanschoren** [comment]
We now state 'ARFF' or 'Sparse_ARFF' in the data format field, and also return it in the API.

**Comment by mfeurer** [comment]
I just tested this, and at least for [4000](http://www.openml.org/d/4000) OpenML still thinks the data is in a dense arff format.

**Comment by joaquinvanschoren** [comment]
I have done this manually for now. I still need to find a way to do this
automatically.

**Comment by mfeurer** [comment]
Ah, okay. Is there any way I can help here, for example finding out whether it is possible to use WEKA or@berndbischl regex in order to figure this out?

**Comment by joaquinvanschoren** [comment]
Well, we have a Continuous Integration thing going on right now. The
endgoal is to test every new datasets on a list of parsers, and to throw
the dataset back at the uploader of one of these fail. Not literally, but
we would show an error message stating that the dataset is not valid
according to the format that the user indicated (and we distinguish between
ARFF and Sparse_ARFF).

We may also use this to run unit tests on the dataset:
https://github.com/ropensci/testdat/

Cheers,
Joaquin

**Comment by mfeurer** [comment]
This might be a stupid question, but does your answer imply that you're already working on this?

**Comment by joaquinvanschoren** [comment]
Yes, we have a CI setup (Lars did this with Jenkins) and it is now running
through all the datasets.

**Comment by berndbischl** [comment]
> for example finding out whether it is possible to use WEKA or@berndbischl regex in order to figure this out?

I use this code to figure out whether it is sparse:
https://github.com/mlr-org/farff/blob/master/R/parseHeader.R
starts at line 64, and you can see the regex there

**Comment by joaquinvanschoren** [comment]
This is done now.
Any violations should be caught by the continuous integration.
