### ISSUE TITLE
apiconnector lib in Weka project differs from the actual version used

### ISSUE THREAD

**Issue by DraXus** [openml/OpenML#163]
I was having some errors compiling the Weka package. Apparently, the apiconnector.jar file provided in lib folder has a different version that the one used in the project.

I've generated a new jar file with the current code and it is working fine so far. I can update the jar file in the repository, although I'm not sure is the best way to mantain the compatibility between versions. What do you think?

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/java#13
