### ISSUE TITLE
Rest API returns internal server error when called from IE/.Net

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#166]
When I call http://openml.org/api/?f=openml.authenticate from Firefox, I get expected JSON (without params - no username provided). However, when I enter the URL in the IE, I get HTTP 500 internal server error. The same thing happens when called from .Net (I wanted to create a .Net api connector).
Could somebody look into the server logs what exactly happens?

Thanks
Jakub

**Comment by joaquinvanschoren** [comment]
Jan, can you please look into this?

**Comment by joaquinvanschoren** [comment]
API has been rewritten + IE is no longer supported by Microsoft. Closing ;)
