### ISSUE TITLE
Lot of links in the Web leads nowhere

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#167]
Compare: openML web, guide, RestApis, rest tutorial (however says http://openml.org/#rest_tutorial). Click. Thil leads to opening tutorial.
openML web, guide, RestApis, rest tutorial. Open in new tab. Thil leads to opening welcome page.
Enter http://openml.org/#rest_tutorial directly - you get welcome page again.

**Comment by joaquinvanschoren** [comment]
Thanks. This has been taken care of in the site redesign, which will
(hopefully) be pushed end of January.

**Comment by mfeurer** [comment]
This issue seems to persists. See for example www.openml.org/plugins, the links to the WEKA, MOA, KNIME and RapidMiner plugin all point to the welcome page of OpenML.org

**Comment by joaquinvanschoren** [comment]
Thanks, now fixed.

**Comment by joaquinvanschoren** [comment]
Have refreshed the entire guide now. Let me know if you find any more dead links.
