### ISSUE TITLE
One-based data-splits download and zero-based predictions upload

### ISSUE THREAD

**Issue by paobranco** [openml/OpenML#169]
Hi,

when a task is downloaded the estimation procedure provides the data splits to use. These data splits include the information for type, rowid, rep and fold.
For instance, the task with id 4990 has the following information for data splits:

type rowid rep fold
1 TRAIN 210 1 1
2 TRAIN 9 1 1

This is one based.
However, when we upload the predictions for this task we must transform all in zero based... 
I guess this should also be one-based.

**Comment by berndbischl** [comment]
This is an R issue, disregard.....
