### ISSUE TITLE
How to upload 'user defined metrics'?

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#175]
Hi,

I'm struggling to find out how to upload a measure, e.g. the C-index, for a run. I can't find any documentation for it and my first attempts by putting it in the run XML didn't work:

```
<oml:run xmlns:oml="http://openml.org/openml">
  <oml:task_id>7328</oml:task_id>
  <oml:implementation_id>1204</oml:implementation_id>
  <oml:output_data>
      <oml:evaluation>
        <oml:name>c_index</oml:name>
        <oml:value>0.65</oml:value>
      </oml:evaluation>
  </oml:output_data>
</oml:run>
```

I'm sure this can be fixed quickly. Thanks in advance!

**Comment by joaquinvanschoren** [comment]
Hi Dominik,

Did you register your evaluation measure (c_index)? OpenML requires
that it has a pointer to the code for that evaluation measure, so you
should register it first by uploading it as a flow, e.g.
'mlr.C_index', and then use the full name (something like
'mlr.c_index(1.0)') to upload a result.

Here's an example:

    <oml:evaluation>
      <oml:name>usercpu_time_millis_testing</oml:name>
      <oml:implementation>openml.evaluation.usercpu_time_millis_testing(1.0)</oml:implementation>
      <oml:value>0</oml:value>

You can also upload the results per fold/repeat:

    <oml:evaluation repeat="0" fold="0">
      <oml:name>usercpu_time_millis_training</oml:name>
      <oml:implementation>openml.evaluation.usercpu_time_millis_training(1.0)</oml:implementation>
      <oml:value>0</oml:value>
    </oml:evaluation>

Let me know if that works for you,

Joaquin

**Comment by dominikkirchhoff** [comment]
Jan has already assigned the [C index](http://openml.liacs.nl/a/evaluation-measures/c-index). I finally could upload something (see bottom)! Unfortunately, the measure does not show up in the run. Instead, in "My runs" there's an error: `Class attribute (null) not found`. Is the evaluation engine not set up for survival tasks or something like that?

```
<oml:run xmlns:oml="http://openml.org/openml">
  <oml:task_id>7328</oml:task_id>
  <oml:implementation_id>1204</oml:implementation_id>
  <oml:output_data>
    <oml:evaluation>
      <oml:name>c_index</oml:name>
      <oml:implementation>openml.evaluation.c_index(1.0)</oml:implementation>
      <oml:value>0.653</oml:value>
    </oml:evaluation>
  </oml:output_data>
</oml:run>
```

**Comment by dominikkirchhoff** [comment]
Sorry for getting on your nerves, but I'd really appreciate a response... :)

**Comment by joaquinvanschoren** [comment]
@Jan, can you please take a look? I'm not sure what the status is on the
survival analysis task.

Thanks,
Joaquin

**Comment by janvanrijn** [comment]
Please be informed that due to many deadlines things from the issue tracker these days escape my attention easily. Dominik, when there is an issue relevant to your master thesis, please feel always free to send a personal email or skype message along, that might speed things up :)

Solved it, I guess. Please check and close the issue.

**Comment by dominikkirchhoff** [comment]
Beautiful! Thank you so much!
