### ISSUE TITLE
.arff file encoding and http headers

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#177]
I am currently using python 3.X to download datasets from OpenML. Most datasets contain plain ASCII text, so it does not matter for them. Other datasets (see list below) contain further characters without specifying the encoding (see first response header). It would be great if you can send the encoding in the http header, for example like you do for the xml files (see second response header).

Datasets:
299, 310, 311, 316, 350, 374, 376, 379, 380, 537, 543, 1029, 1097, 1101, 1102, 1109, 1168

Problematic response header:

```
Cache-Control: must-revalidate
Connection: Keep-Alive
Content-Description: File Transfer
Content-Disposition: attachment; filename=dataset_1_anneal.arff
Content-Length: 143344
Content-Type: application/octet-stream
Date: Tue, 24 Feb 2015 10:04:59 GMT
Expires: 0
Keep-Alive: timeout=5, max=100
Pragma: public
Server: Apache/2.2.22 (Ubuntu)
Set-Cookie: XXX
X-Powered-By: PHP/5.4.30-2+deb.sury.org~precise+1
content-transfer-encoding: binary
```

Helpful response header:

```
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 122
Content-Type: text/xml; charset=utf-8
Date: Tue, 24 Feb 2015 10:07:30 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.2.22 (Ubuntu)
Vary: Accept-Encoding
X-Powered-By: PHP/5.4.30-2+deb.sury.org~precise+1
```

**Comment by joaquinvanschoren** [comment]
Thanks for bringing it up again. We will tackle this together with #201. It seems that in these datasets, the non-ASCII text is in the ARFF comment section, not the actual data.

**Comment by mfeurer** [comment]
Does it matter where in the text the non-ASCII characters are? 

At least the python module reads the comments and presents them to the user.

**Comment by joaquinvanschoren** [comment]
No, it doesn't matter, I just wanted to add a bit of extra information for
reference.

**Comment by mfeurer** [comment]
Related to #309.

**Comment by mfeurer** [comment]
Closing this as #201 is closed.
