### ISSUE TITLE
Defective data splits

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#179]
Hey,

[Task 2373](http://openml.org/t/2373) has defective data splits:

```
@data
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,0,0,0
TRAIN,0,0,0
TRAIN,0,0,0
TRAIN,0,0,0
TRAIN,0,0,0
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,1,0,0
TRAIN,1,0,0
[...]
```

Also, the associated [data set](http://openml.org/d/164) is labeled as a multi-class problem (`NumberOfClasses` = 4) but there are only two classes.

**Comment by dominikkirchhoff** [comment]
The same applies for [Task 2058](http://openml.org/t/2058) and probably for any other task using this data set.

**Comment by joaquinvanschoren** [comment]
These seem fine now :).
