### ISSUE TITLE
openml.task.types.search and openml.task.types API broken?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#181]
I wanted to use `http://www.openml.org/api/?f=openml.task.types.search&task_type_id=1` to get the evaluation procedures from a specific task type (see also http://www.openml.org/api), but the server seems to return a `Not Found` error (btw. I have same issue for `http://www.openml.org/api/?f=openml.task.types`). Can someone please check if the following call works as expected?

```
curl -XGET 'http://www.openml.org/api/?f=openml.task.types.search&task_type_id=1'
```
I need this to fix the issue https://github.com/openml/r/issues/53, therefore I mark this as "high prio".
Thanks.

**Comment by berndbischl** [comment]
@giuseppec 
I meant the color labels on the right side :)

**Comment by giuseppec** [comment]
@berndbischl I know, but I can't assign labels here (I do not have the rights or something)... Apparently, I can do this only in the openml/r issue tracker...

**Comment by berndbischl** [comment]
ok, i can do that then. just tell me here

**Comment by jaksmid** [comment]
I was going to report the same thing.
I will be happy to add this into java and net as soon as the api gets fixed.
@giuseppec  If really urgent, you should be able to execute own sql and get the results that way.

**Comment by joaquinvanschoren** [comment]
The functions have been renamed. 
The first one is: openml.task.type.get
The other one is: openml.task.type

Documentation is outdated, will fix this soon. 
We have added an alias for now, so the old functions work again, but please use the new function names instead.

**Comment by berndbischl** [comment]
In general, until we go on CRAN renaming is at least for us not really a problem.

Even later, it is mainly an internal thing, as long as you tell us it should be OK.

**Comment by giuseppec** [comment]
I used `http://www.openml.org/api/?f=openml.task.type.get&task_type_id=1` and the `estimation_procedure` part looks like:

```
  <oml:input name="estimation_procedure">
    <oml:estimation_procedure>
      <oml:type>[LOOKUP:estimation_procedure.type]</oml:type>
      <oml:data_splits_url>[CONSTANT:base_url]api_splits/get/[TASK:id]/Task_[TASK:id]_splits.arff</oml:data_splits_url>
      <oml:parameter name="number_repeats">[LOOKUP:estimation_procedure.repeats]</oml:parameter>
      <oml:parameter name="number_folds">[LOOKUP:estimation_procedure.folds]</oml:parameter>
      <oml:parameter name="percentage">[LOOKUP:estimation_procedure.percentage]</oml:parameter>
      <oml:parameter name="stratified_sampling">[LOOKUP:estimation_procedure.stratified_sampling]</oml:parameter>
    </oml:estimation_procedure>
 ```
Is this what should be returned? Instead of `[LOOKUP:estimation_procedure.type]` I expected something like:

```
  <oml:input name="estimation_procedure">
    <oml:estimation_procedure>
      <oml:type>crossvalidation</oml:type>
      ...
 ```

**Comment by joaquinvanschoren** [comment]
Yes, that's a bug. Jan, could you fix it, please?

**Comment by janvanrijn** [comment]
It's not a bug. Remember this is the task type, a template for tasks. 

The thing you're expecting is true, for the task function. E.g., type openml.org/api/?f=openml.task.get&task_id=1, and those variables will be set.

**Comment by joaquinvanschoren** [comment]
Sorry, I didn't realize this was the task type. 

I'm doubting whether we should expose these internal features in the API? What is the use case for returning this information in openml.task.type.get?

Should we hide them in the API until we figure this out (leave empty XML tags)?

I'm removing the high-priority label if that's ok.

**Comment by giuseppec** [comment]
Bernd opened the issue openml/r#53. In order to fix this issue, I need a list of all availabe estimation procedures (see http://openml.org/a/estimation-procedures) in order to match the estimation ID with the name of the estimation procedure, for example:

```
  est.id                             name
1      1          10-fold Crossvalidation
2      2   5 times 2-fold Crossvalidation
3      3 10 times 10-fold Crossvalidation
...
```

We need this because http://www.openml.org/api/?f=openml.tasks&task_type_id=1 gives us an integer code for the estimation procedure: 

```
...
  <oml:task_id>1</oml:task_id>
  <oml:task_type>Supervised Classification</oml:task_type>
  <oml:did>1</oml:did>
  <oml:name>anneal</oml:name>
  <oml:status>active</oml:status>
  <oml:input name="estimation_procedure">1</oml:input>
  <oml:input name="evaluation_measures">predictive_accuracy</oml:input>
...
```
and we would like to replace this by the name of the estimation procedure. Currently, there is one possibility to do this via `http://www.openml.org/api/?f=openml.estimationprocedure.get&estimationprocedure_id=1` but it would also be helpful to have an API that allows us to get a list of all estimation procedures and I thought this would be able with `openml.task.type.get` (to get at least all estimation procedures of a specify task type).

**Comment by giuseppec** [comment]
Hi,
currently, I am using the SQL query `SELECT DISTINCT id,name FROM estimation_procedure` to get the results I need. Shall we use this SQL query in the R-Package or are we planning to solve this issue using an API?

**Comment by berndbischl** [comment]
We can use the SQL right now, but this is a bad internal fix. We need proper API calls

**Comment by joaquinvanschoren** [comment]
There is this call (you have to give the ID):
http://openml.org/api/?f=openml_estimationprocedure_get&estimationprocedure_id=1

But I agree we should have a listing call too.
Jan, can you please add a 'openml_estimationprocedures' call?

I also added it to the wiki for API v.1.:
https://github.com/openml/OpenML/wiki/API-v1
