### ISSUE TITLE
dataset 376 is wrong

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#182]
https://archive.ics.uci.edu/ml/datasets/Syskill+and+Webert+Web+Page+Ratings

This is a text data set, not sure if we cover it already anyway. But the data is not even as on UCI but garbled mess. Should be removed or fixed.

**Comment by joaquinvanschoren** [comment]
376 is a text mining data set.

Should we remove the classification tasks until we have a proper text mining task?

**Comment by mfeurer** [comment]
If this is removed, one should have a look at all other datasets which contain attributes of type `string`. BTW: +1 for removing the classification task

**Comment by berndbischl** [comment]
Remove it.

**Comment by joaquinvanschoren** [comment]
Jan suggests not to remove the tasks, but tag the datasets/tasks as 'text mining'.  Tags are part of the dataset/task/flow descriptions, so you can filter them out.

**Comment by joaquinvanschoren** [comment]
Any consensus here? I would be OK with removing the classification task. All runs on this task are failing (except for ZeroR, which doesn't even look at the features). @janvanrijn ?

**Comment by joaquinvanschoren** [comment]
Alright. I removed the tasks. We'll revisit this when we create text mining tasks.
