### ISSUE TITLE
10 simple rules

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#185]
This paper presents 10 simple rules for building good ML studies: http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004191

Perhaps it is useful to link this to OpenML studies and _automatically_ test some/most of these points. As such, you would get an 'automatic pre-reviewer' for your study, and people (especially young PhDs) could use that to improve their study, run more experiments, do better comparisons, etc.

**Comment by janvanrijn** [comment]
Thanks for pointing to this paper! I don't think that this belongs in the issue tracker though. Let's close for now?
