### ISSUE TITLE
openml.data.qualities.list does not list all available qualities?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#186]
`openml.data.qualities.list` should list all data qualities that are used (i.e., are calculated for at least one dataset). However, I found out that `http://www.openml.org/api/?f=openml.data.qualities&data_id=2` contains qualities that are not listed in `http://www.openml.org/api/?f=openml.data.qualities.list`. 
For example, the qualities `DefaultTargetNominal`, `DefaultTargetNumerical` and `J48.00001.kappa` are contained in the data set with id=2, but they are not included in the `openml.data.qualities.list`.

**Comment by giuseppec** [comment]
PING.

http://api_new.openml.org/v1/data/qualities/list should return a list of all data qualities right?
counterexample: http://api_new.openml.org/v1/data/qualities/3 contains 8 additional fields that do not appear in `qualities/list`:

```
"DefaultTargetNominal"   "DefaultTargetNumerical" 
"J48.00001.kappa"        "J48.0001.kappa"       
"J48.001.kappa"          "NBAUC"                 
"NBErrRate"              "NBKappa"
```
There are several other datasets with the same issue

**Comment by joaquinvanschoren** [comment]
Thanks. Apparently these qualities where renamed in Fantail, but they
lingered in the database.
They are now removed.
