### ISSUE TITLE
Auto-versioning of flows is incorrect if the component versions change

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#190]
We auto-version flows: when a flow is submitted with the same name but different code, we automatically create a new version. However, we do not check whether the underlying components of a flow have a different version. We do store them as a different flow, but the version number is incorrect.

Occasionally, this leads to flows with duplicate versions: openml.org/f/1284

**Comment by janvanrijn** [comment]
I think this is no longer relevant, as we use different ways to check whether flows are unique.
