### ISSUE TITLE
Broken links on openml.org website

### ISSUE THREAD

**Issue by ledell** [openml/OpenML#192]
There are a few places I have found broken links on the website.

1. http://openml.org/register
The link for the "Honor Code and Terms of Use" points to http://localhost/OpenML/guide/#!terms instead of http://openml.org/guide#!terms

2. http://openml.org/search?q=&type=run&sort=date&order=asc
The links below the individual runs are missing a subdir in their URL.  For example, "Run 1" has a link to a flow and a task.  Those link to: http://openml.org/61 instead of http://openml.org/f/61 and http://openml.org/68 instead of http://openml.org/t/68

**Comment by joaquinvanschoren** [comment]
Many thanks. I have fixed these links.
We will also push a major website redesign (hopefully!) by the end of this
week.

Sincerely,
Joaquin

**Comment by ledell** [comment]
Thanks for fixing so fast!  I learned about the project today at [useR](http://user2015.math.aau.dk/tutorials#mlr), looks exciting!
