### ISSUE TITLE
Dataset 1240 cant be downloaded

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#194]
Marked as public, however visiting the download URL throws 403:
http://www.openml.org/data/download/522887/AirlinesCodrnaAdult.arff: Forbidden

**Comment by joaquinvanschoren** [comment]
Jan, this seems to be your dataset. Is it meant to be public or private?

**Comment by joaquinvanschoren** [comment]
This seems to be fixed. I could download the dataset.
