### ISSUE TITLE
No new Evaluations, Server Problems?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#195]
Hi,
I see you changed the homepage layout. I noticed severeal issues:

1) Since Run 463902, the server does not seem to calculate any evaluations (I noticed this already yesterday, but thought that it will

2) The homepage seems to be very, very slow.

3) username = "openml.rteam@gmail.com", password = "testpassword" does not work anymore, it tells me "incorrect login", also it seems that I cannot login with my account (however, because of point 2) I havn't tried it multiple times yet.

Also, I must say that we have a talk tomorrow, where we would like to showcase openml and the r-package. Are these issues already known or does this only happen to me?

**Comment by joaquinvanschoren** [comment]
Yes, something went wrong with the latest pull on he server. I'm looking
into it. I also have a demo later today :(.

**Comment by berndbischl** [comment]
haha :)

**Comment by joaquinvanschoren** [comment]
We can get it running again but it is still very slow. We're still looking
into it.

**Comment by berndbischl** [comment]
maybe revert it? we have our demo tomorrow....

**Comment by joaquinvanschoren** [comment]
I found the problem. It was a single trailing slash '/'.

**Comment by giuseppec** [comment]
It seems that the page is faster now, thank you for resolving this issue. But the "no new evaluations" issue for newer runs seems to be still there, doesn't it? 
Also, I can't see the number of datasets, tasks, flows and runs on the startpage. 
Another thing, which I am not sure if it is the WIFI's fault here or the OML server, is that I can't authenticate via the API, e.g. using the call in R 
`authenticateUser(username ="openml.rteam@gmail.com", password = "testpassword")`.

**Comment by joaquinvanschoren** [comment]
Thanks, you are right. For some reason the crontab was commented out. It is
now running again and is catching up.

I just ran this, seems fine?
authenticateUser(username ="openml.rteam@gmail.com", password =
"testpassword")
Authenticating user at server: openml.rteam@gmail.com
Retrieved session hash. Valid until: 2015-07-11 08:17:01

**Comment by janvanrijn** [comment]
Joaquin had a presentation yesterday. In an to attempt to make the site
faster, I manually turned it down. Will put it on when access to computer.
Jan
Op 11 jul. 2015 07:14 schreef "giuseppec" <notifications@github.com>:

**Comment by giuseppec** [comment]
Ok `authenticateUser` issue ist due to the WIFI here... I tested it from an external server... I will try to get it run.

**Comment by joaquinvanschoren** [comment]
Hi Guiseppe,

Is it working now?
I am really really sorry about the troubles yesterday. It was a situation
that doesn't occur in my local machine.
When we set up the test server we can avoid this in the future.

**Comment by giuseppec** [comment]
It seems that  the server does not seem to calculate any evaluations measures since Run-ID 463903.
For example http://www.openml.org/r/463902 shows "23 Evaluation measures" that were computed from the openml server, but http://www.openml.org/r/463903 (and all other runs above ID 463903) always show "0 Evaluation measures".

**Comment by joaquinvanschoren** [comment]
Hi, the server is really behind on calculating evaluations since we started over after the problem last week. It is now filling in some large gaps and is now around run 157000.

Jan is working on a fix so we can parallellize the process and catch up more quickly.

**Comment by joaquinvanschoren** [comment]
Everything running as usual again. Closing.

**Comment by giuseppec** [comment]
Hmmm... I experience again strange server issues. Uploading runs takes very, very long and the server does not give me the run.id when I uploaded the run. Did something change?

**Comment by joaquinvanschoren** [comment]
Already responded in another thread. Seems to be solved now.

**Comment by janvanrijn** [comment]
Resolved it with reboot (sunday)
Op 8 sep. 2015 00:41 schreef "Joaquin Vanschoren" <notifications@github.com
