### ISSUE TITLE
Return per-fold statistics for runs in the API

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#196]
1) You sometimes need the per-fold per-repeat results for a run. Can we extend the openml.runs (and maybe also the openml.task.evaluations) API call to include the per-fold statistics?

2) openml.runs seems to also returns with an error message, but the error message itself is not returns. Can it be added?

3) openml.data should optionally include the full range of data qualities, e.g. with a flag. Sometimes you want to list many datasets and you don't want to make 1,000 calls to the server.

4) We need an API call to create tasks. For instance with XML description:

``` xml
<inputs>
   <input name="estimation_procedure" value="10-fold-CrossValidation">
   <input name="source_data" value="1">
   <input name="target_feature" value="class">
   <input name="evaluation_measure" value="area_under_roc_curve">
</inputs> 
```

And it would then return the new task_id or the existing task_id if it already exists.

**Comment by joaquinvanschoren** [comment]
Also, id names are not always consistent:
openml.data returns a column 'did' instead of 'data_id'
openml.data.description returns 'id' instead of 'data_id'
openml.estimationprocedure returns 'ttid' instead of 'tasktype_id'

That's all I could find, but it would be good to check this better.

**Comment by berndbischl** [comment]
If names are inconsistent, change them now IMHO

**Comment by janvanrijn** [comment]
I personally don't think is issue is still relevant
