### ISSUE TITLE
Community link on landing page dead

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#197]
The link to the "forum" at the bottom of openml.org is dead: http://www.openml.org/community

**Comment by joaquinvanschoren** [comment]
Thanks, will fix when I have reliable internet access (currently in the
mountains), early next week.

**Comment by joaquinvanschoren** [comment]
Fixed. Thanks again.

**Comment by joaquinvanschoren** [comment]
Dear Andreas,

Thanks for mentioning it. It is fixed now.
