### ISSUE TITLE
Connecting with MLData

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#198]
Did you connect with the people form MLData by any chance? Their project is very similar to openml, and I feel concentrating efforts would really be beneficial for the community.

**Comment by joaquinvanschoren** [comment]
Hi Andreas,

Yes I know Mikio and Cheng well, and from the start we wanted to make the
two platforms compatible. We had a student writing code to connect the
platforms but he ran into technical difficulties and he didn't finish it.
It's high on our to do list. We just need somebody to take the lead on this.

Joaquin

**Comment by amueller** [comment]
I'll see if I can maybe get some students for this or other things...

**Comment by joaquinvanschoren** [comment]
Thanks, Andreas. That would be wonderful.

**Comment by joaquinvanschoren** [comment]
MLData is closing down. They'll archive the datasets on Zenodo. They asked to import most of them in OpenML, which I hope to do soon.
