### ISSUE TITLE
Website makes it hard to download the WEKA plugin

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#199]
Hi,

I tried to download the WEKA plugin, but there is a problem with the website. A part of the menu does not disappear (both in Firefox and Chromium), hiding the download link. I finally succeeded by opening the website source code.

**Comment by joaquinvanschoren** [comment]
Hi Matthias,

It should be fixed now. Could you please check?

Cheers,
Joaquin

**Comment by mfeurer** [comment]
Hi Joaquin,
thanks, I can read everything now.
Cheers,
Matthias
