### ISSUE TITLE
Ensure UTF8 for all textfiles

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#201]
Many files on OpenML can contain special chars in names or data fields. 
We MUST ensure that these files are encoded as UTF8.
Otherwise parsers can generate garbled and random output. 

Counterexamples:
Data sett ids / ARFF files:
374, 376,  379,  380

These are text mining files, with HTML contents, but they are stored as ASCII.

2 requests: 

a) Convert all files where this is currently wrong.

b) Disallow non-UTF8 files to be uploaded by the users 
Or, if you can do this properly: Auto-Convert them on upload for the user.

**Comment by joaquinvanschoren** [comment]
a) Datasets have been converted. Please check.
b) Not checked yet by the server. We'll take this up together with ARFF
checking

**Comment by mfeurer** [comment]
Can you please also consider issue #177, it is highly related and would solve the same issue.

**Comment by berndbischl** [comment]
WARNING: data 379 and 380 ARFFs are now EMPTY on the server? Mistake?

**Comment by joaquinvanschoren** [comment]
Yes. Fixed now. Thanks!

**Comment by berndbischl** [comment]
I can parse all 4 data sets. 
I will leave this open until you ensure on upload that only utf8 files exist for new data.
Then you can close.

**Comment by berndbischl** [comment]
Another related thing, (please tell me whether to open another issue for this).

Some OML uploaded files contain mixed linebreaks.
I have seen multiple times unix / mac breaks in single dataset.arff files.

I guess I am going to handle this on my side now in R. But this is extremely annoying....
IMHO it would be much better to define and ensure this for all files. 

Your opinion?

**Comment by joaquinvanschoren** [comment]
There are both Linux and Mac line breaks in the same file? That is indeed
annoying. We should also check this when we add checks to the dataset
uploads next week.

For now: if you can give a list of datasets where this happens, I can
probably fix that easily.

**Comment by berndbischl** [comment]
> There are both Linux and Mac line breaks in the same file

yes

**Comment by mfeurer** [comment]
Ping. I didn't have a problem regarding UTF-8 in the near past. Is this still relevant?

**Comment by joaquinvanschoren** [comment]
Haven't encountered this either, but we don't explicitly test for this yet. Will open a new issue to add this to the dataset check (Jenkins).
