### ISSUE TITLE
dataset 292 ARFF is totally broken?

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#202]
It contains curly brackets around the whole data section rows

it looks like it should be a dense format, and the header says it was converted from sparse. 

is this valid ARFF?

**Comment by mfeurer** [comment]
Yes, this is valid ARFF; I only tried with the python arff reader, but I do not see any issue here.

If I remember correctly, the uploader of these files has several similar-looking datasets online.

**Comment by berndbischl** [comment]
Ok. Sorry, I did not see that sparse format is not detectable for the tags right?
So this is a dense file, coded "stupidly" in sparse, but valid ARFF format?

**Comment by mfeurer** [comment]
What do you mean by 'Detectable for the tags'? I guess you want to know whether there is a flag which determines sparse data. As far as I know the only possibility is reading an arff file. I opened an issue for that #162 

Regarding the file and encoding: yes.

**Comment by berndbischl** [comment]
Yes, I meant that.

And now I want a flag too.

But this issue here was just a mistake by me.
