### ISSUE TITLE
dataset 676 is invalid ARFF?

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#203]
hi,

this data set contains possibly invalid NAs. A line looks like

eg line 173 looks like

```
,9.079582,20.946008,10.5527379,102273.95
```

I guess the first entry in 173 should be missing, but ARFF says this must be coded as ? then?

**Comment by joaquinvanschoren** [comment]
Turns out these are extra commas at the beginning of some lines. Fixed now.

**Comment by berndbischl** [comment]
Thx
