### ISSUE TITLE
new evaluationmeasures/list API not working?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#207]
http://api_new.openml.org/v1/evaluationmeasures/list?session_hash=testtest
tells me "Function not valid"

**Comment by joaquinvanschoren** [comment]
It should be:
http://api_new.openml.org/v1/evaluationmeasure/list?session_hash=testtest
<http://api_new.openml.org/v1/evaluationmeasures/list?session_hash=testtest>

The Wiki has been updated.
