### ISSUE TITLE
OML WS 2015, R issues

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#212]
Summary of stuff we need to move on:

- tags in "list task" call

**Comment by joaquinvanschoren** [comment]
This is done now. Closing

**Comment by berndbischl** [comment]
please ADD  to a normal run object:

- task_type
- uploader name or email
- maybe later: rename uploader to uploader.id. potentially make a issue out of this, not urgent for US NOW
- flow humand readable name
- the optimized perf measure, its name, IF it was selected

**Comment by berndbischl** [comment]
please finish list/runs

**Comment by berndbischl** [comment]
we still want a readonly APIKEY. now.

**Comment by berndbischl** [comment]
that readonly key should be vivisble somewhere in the OML global wiki.
other people besides us will want to use it for demos etc

**Comment by berndbischl** [comment]
we also want studies pls

**Comment by joaquinvanschoren** [comment]
all things are added to run objects. now continuing on studies

**Comment by giuseppec** [comment]
Do we have a good alternative to the old `openml.task.evaluations`? 
We would be really happy to have an API that is able to list all evaluation measures of runs of a specific task.

**Comment by joaquinvanschoren** [comment]
Weird, I just uploaded some runs, and they are evaluated fine.

**Comment by giuseppec** [comment]
Did you answer to the wrong issue? Uploading seems to work again, I had trouble uploading runs for 1-2 hours.

**Comment by joaquinvanschoren** [comment]
Sorry, yes wrong issue. We will have that evaluation call available soon.

**Comment by giuseppec** [comment]
Please let me know when we have an alternative for `openml.task.evaluations`. Also, can we have a high_priority label here?

**Comment by joaquinvanschoren** [comment]
Sure, you can also add these labels, I think :)
Jan has just finished the API call to create tasks, the call to download evaluations will be next.

**Comment by joaquinvanschoren** [comment]
Evaluations service is available for a while now:
http://www.openml.org/api_docs/#!/evaluation/get_evaluation_list_filters
