### ISSUE TITLE
Remove stale task tags

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#213]
When you remove tasks, its tags are not automatically deleted

**Comment by joaquinvanschoren** [comment]
Stale tags are removed now. Leaving this open for a more permanent solution later.

**Comment by mfeurer** [comment]
I'm sorry, but I have to tell you that I still get them via `task/list`

**Comment by joaquinvanschoren** [comment]
Hi Matthias,

I can't reproduce the problem. if I try task/list I get only correct tasks.
Is it possible that you are using a cached version?
Also, to be sure, it is normal that tags appear in a task. What should not
happen in an 'empty' task that only has tags.

Can you check please?

Thanks,
Joaquin

**Comment by mfeurer** [comment]
Hi Joaquin,
no, I'm performing an API call via the POSTMAN Chromium extension. Try to access http://api_new.openml.org/v1/task/list/1 and check the last tasks.

**Comment by joaquinvanschoren** [comment]
OK, I was using http://api_new.openml.org/v1/task/list
<http://api_new.openml.org/v1/task/list/1>

I'm not even sure what tasl/list/1 does...

**Comment by mfeurer** [comment]
It should list all tasks of a certain task type; in this case supervised classification.

**Comment by joaquinvanschoren** [comment]
Thanks. This is fixed now.

**Comment by mfeurer** [comment]
Thanks
