### ISSUE TITLE
Uploading Dataset 

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#215]
Hi,
I downloaded the dataset http://www.openml.org/d/10 and uploaded it again with the POST API for the datasets. For the POST, I uploaded the XML and the ARFF file. The result can be found here: http://www.openml.org/d/1763. 

My questions:
1) The dataset status is "in_preparation". How can I get rid of this status?
2) It seems that `http://www.openml.org/d/1763` does not contain any description info,  although I also uploaded the XML that contains the description info etc.

**Comment by giuseppec** [comment]
Continue the discussion from https://github.com/openml/openml-r/issues/135 

Question from @giuseppec:
> I uploaded the iris data set 9 months ago http://www.openml.org/d/4364 and it is still in_preparation?

Answer from @joaquinvanschoren: 

> Activating datasets is currently still done manually until we get the CI to work properly. I didn't activate the iris-example dataset because there was no description, and it looks like a duplicate?

Ok, I understand this, but I think we should at least notify the user after, say 24h and tell him a reason why his dataset is still `in_preparation`. 
E.g. instantly notifying him "you data set has no description" after the uploading API call, or after a manual check sending him an email with "your data set seems to be a duplicate". 
Otherwise the user will wait and never knows what happend and why his data set can't be used. At least that happend to me with the data set www.openml.org/d/4364.

**Comment by joaquinvanschoren** [comment]
Yes, this is very important but I couldn't get around to it yet. I typically email the uploader manually. For errors, I can show the error in the database on the website, but it may be cryptic.
 
This is important and will look at it soon.

**Comment by janvanrijn** [comment]
This issue now addressed this discussion right #794
