### ISSUE TITLE
Uploading only the flow.xml without a source or binary possible?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#217]
To fix https://github.com/openml/r/issues/49 we need the possibility to just upload the flow.xml file without a source or binary. 
Or maybe with the possibility to add a "callstring" instead of a source or binary file. Is this possible?

**Comment by joaquinvanschoren** [comment]
Indeed, we agreed during the workshop that it should be possible to state a url (e.g. to an exact github snapshot) instead of a binary file. In many cases it doesn't make sense to upload code from a library.

We will do this as soon as possible.

We also have an 'installation_notes' field, but I guess it is better to add a specific 'callstring' field as well?

**Comment by joaquinvanschoren** [comment]
In short, let's do the following:
- Allow upload without a file, just including the 'source_url' field in the XML.
- Add a 'callstring' field in the XML
- If you want to reference an algorithm that is part of a library, you give the name of the algorithm as the flow name, preferable using a schema such as 'lib.algo' (e.g. weka.RandomForest), you add the url to the library code (e.g. github snapshot for mlr, sourceforge link for WEKA), as well as the callstring that calls the specific algorithm.

**Comment by berndbischl** [comment]
Hi, 

just a quick clarification. During the WS we also (kinda) agreed that the code somewhere resides in a study. Ok, that would be referenced in the source_url. Agreed then.

I also like what you say about algos in libraries. But IIRC you already put the WEKA callstring somewhere? Is that an "inappropriate" place that you kinda misuse? What was it again?

**Comment by giuseppec** [comment]
@joaquinvanschoren is this done?
I am still getting the `Please provide source or binary file` error and how should I call the "callstring" field in the XML?

**Comment by jakobbossek** [comment]
Ping.

**Comment by joaquinvanschoren** [comment]
Jan is busy, so I did the update. I don't have Jan's testing setup running
here, but it should work.
Can you give it a try?

**Comment by jakobbossek** [comment]
Ok, great. What about the callstring field in the XML file? I cannot see it in the [xsd file](https://github.com/openml/website/blob/master/openml_OS/views/pages/rest_api/xsd/openml.implementation.upload.xsd).

**Comment by giuseppec** [comment]
I also thought about a callstring field, where we could define the learner. But: wouldn't be the name of the flow, which is something like `classif.rpart`, enough?

**Comment by joaquinvanschoren** [comment]
Sorry, I was confused. There is no callstring for flow uploads.
I guess we can close this?
