### ISSUE TITLE
evaluation/list vs. run/list

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#219]
If I count the runs from http://api_new.openml.org/v1/run/list/task/2, I get 707 results but
http://api_new.openml.org/v1/evaluation/list/task/2 tells me:
```
		Too many results.
		Size of result set: 13465; max size: 10000. 
```
how can this happen?
I thought the API `run/list/` returns all runs (including the ones with an error) and `evaluation/list/` returns all runs without the ones with error. So the number of runs for `run/list/` should always be >= the number of runs for  `evaluation/list/`, right?

**Comment by joaquinvanschoren** [comment]
Good morning :).

It was counting evaluations, not runs. Runs can have many evaluations for
different measures.
I agree that this is sort of unexpected, so I changed it to count runs
instead. It seems to work now.

**Comment by giuseppec** [comment]
I see, the thig is that `evaluation/list` does not count the number for runs, it counts the number of evaluations for each run

**Comment by joaquinvanschoren** [comment]
Yes, which is sort of annoying when you first query for runs and then their
evaluations.
Jan, do you also agree with this change (already running)?

**Comment by giuseppec** [comment]
I would keep the change you made. I think that if there are no errors, `evaluation/list/` shoult always output the same number of runs as `run/list/`. If you think that this change makes things much slower, because all evaluations are returned, I would rather prefer to choose one or more evaluation metrics instead of counting the number of evaluations for each run.

**Comment by giuseppec** [comment]
Another question: what is this `array.data`?

**Comment by joaquinvanschoren** [comment]
Some evaluation measures are a number (e.g. accuracy), others are arrays
(e.g. confusion matrix), others have both (e.g. average precision and
precision per class). That's why we have both.
