### ISSUE TITLE
Extend documentation on evaluation measures

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#220]
There should be a clear link to each evaluation measure computed by OpenML and a description of the exact meaning and computation. For instance, there should be clear distinction between recall with a given positive class, and weighted average recall over all classes.

We have an index of evaluation measures, but they are a bit hard to find and there is currently no clickable link in the run descriptions.

**Comment by janvanrijn** [comment]
The math function tabel contains many useful information regarding this already (@jaksmid and @WilliamRaynaut worked on this during a not-so-recent workshop)

**Comment by joaquinvanschoren** [comment]
Closing stale issues
