### ISSUE TITLE
additional qualities in data/list and task/list API

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#222]
Hi,

could we extend the data/list and task/list API so that they also return the following infos (some of them are already returned, but we really would like to have some more):

```
7                       Dimensionality
27                   MajorityClassSize
28         MaxNominalAttDistinctValues
37                   MinorityClassSize
50                       NumAttributes
51                       NumBinaryAtts
52                    NumMissingValues
53                      NumNominalAtts
54                      NumNumericAtts
55                     NumberOfClasses
56                    NumberOfFeatures
57                   NumberOfInstances
58  NumberOfInstancesWithMissingValues
59               NumberOfMissingValues
60             NumberOfNumericFeatures
61            NumberOfSymbolicFeatures
```

**Comment by giuseppec** [comment]
Ping. Adding at least `MajorityClassSize` and `MinorityClassSize` would help a lot.

**Comment by joaquinvanschoren** [comment]
They are now added, at least the ones that are not duplicates/derivates
ones ones we already had. The call already returns a lot of data.

**Comment by giuseppec** [comment]
Thanks this helps a lot. Regarding duplicated qualities: shouldn't we try to avoid redundant info and remove duplicated qualities? For long-term usage of OpenML this would save space and traffic.

**Comment by joaquinvanschoren** [comment]
Indeed, good point. We need some rewriting of the Fantail lib.

**Comment by joaquinvanschoren** [comment]
Closing this as the issue has been solved. We can open a new issue for making Fantail more efficient.
