### ISSUE TITLE
can we please get correct data properties

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#224]
hi,

in order to work we really need reliable properties / data qualities.

here is an example, where this is wrong.
It is NOT the only one, please check integrity with a script on your side

http://www.openml.org/d/312

1) The web site description says 
NumberOfNumericFeatures = The number of symbolic features in the dataset.

2) The NumberOfSymbolicFeatures seems completely missing, which means we get an NA in R

Can you please establish unit tests for stuff like this? Or shall we do this?
Lets please talk about this!

**Comment by joaquinvanschoren** [comment]
Thanks. I updated the error in the description, and also made a pass over the other descriptions to check for other errors.

The fact that NumberOfSymbolicFeatures is often missing is that it was not computed by default (while NumberOfNumericFeatures is). I agree this is weird, so I added it. I also filled it in for all datasets.

A unit test would be good, but these are not automatically run when a new dataset is uploaded. What we need is to check this before datasets are made active. I'll look into this asap.

**Comment by berndbischl** [comment]
What is the status here? Can we close this and convert the stuff about the unit test into a separate issue?

**Comment by joaquinvanschoren** [comment]
Yes this is solved. It would indeed be good to put the CI topic in a separate issue.

**Comment by berndbischl** [comment]
I have added a issue for R that we might do some unit testing for this, additionally (!), on our side. 
IMHO you can close this here then if you checked this.

And please open something for the CI then, if you think we need this. I am unsure of the status of that.
