### ISSUE TITLE
Pull request for python interface?

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#225]
Hi. Is someone working on the python interface already?
If so, it would be cool if there was a public pull request to see what is happening.

Thanks!

**Comment by joaquinvanschoren** [comment]
Hi Andreas,

We have a special repo for the python interface. Also see the readme for
the documentation. https://github.com/openml/python
We are a bit dormant because of other work, but plan to forge ahead after
NIPS.

Cheers,
Joaquin

**Comment by joaquinvanschoren** [comment]
I believe this question has been answered? See the openml/python repo for details. Please reopen if you need anything more.
