### ISSUE TITLE
Cannot download datasets: 403 Forbidden

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#226]
Hi,
I'm currently trying to download datasets. Starting from dataset ID 1215, I get the following error

    403 Forbidden
    
    You don't have the right access rights to view this page.

for the following datasets: 125, 1221, 1222, 1231, 1235, 1236, 1237, 1238, 1239, 1240

The datasets are marked as active and I cannot find a reason why I'm not allowed to download them. Do I overlook something?

**Comment by mfeurer** [comment]
I don't know if this is related, but the API call for the list of datasets shows that there is a dataset with ID 1170, if I try to access it online, I am presented a template-like website. This seems to happen for other datasets as well.

**Comment by joaquinvanschoren** [comment]
This is very weird, I could not reproduce this at all? Are you using the
new api? Or is this a caching issue? Or maybe Jan fixed it in the mean time
:).

I really tried to reproduce this, but I get a normal response (also with a
non-admin account) for all datasets except 1170, 1221 and 1239. Those 3
datasets don't exist (anymore), but I also don't see these returned in the
data/list call?

Please let me know if you find something.

Cheers,
Joaquin

**Comment by mfeurer** [comment]
![openml](https://cloud.githubusercontent.com/assets/5320498/11865649/a80ec174-a4a5-11e5-9b7c-974085756b9b.png)

That's what happens in the browser, both Firefox and Chromium, while being logged in. It also happens when using the API. I just reread my question, I think I wasn't specific about wanting to download the arff files;)

**Comment by joaquinvanschoren** [comment]
Indeed, some of these datasets were marked private in the file permission tables, even though they were active. This is now fixed.

Can you try again?

**Comment by mfeurer** [comment]
I tried again and it seems to be fixed; thank you very much.

But since I'm not at my university machine, I would like to leave this open and try again next year on a large scale.

**Comment by mfeurer** [comment]
I tried on a large scale, this is fixed. Thanks very much
