### ISSUE TITLE
evaluationmeasure/list: Function not valid

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#229]
Hi,
what happend with the http://api_new.openml.org/v1/evaluationmeasure/list ? It does not seem to exist anymore?
Do we have a place where renaming or removing of APIs is first discussed before they don't work? This would help a lot.

**Comment by joaquinvanschoren** [comment]
Sorry, it is back now.

http://www.openml.org/api_new/v1/evaluationmeasure/list
