### ISSUE TITLE
data set 1438: "relational" variable

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#230]
Hi, the dataset with ID 1438 is strange. There is this 'relational' variable-type that is currently not supported by any arff reader in R. This is the header:

```
 @attribute bag relational 
 	@attribute y numeric 
 	@attribute x numeric 
 	@attribute z numeric 
@end bag 
```

Why not converting the data set so that the header looks like:

```
 @attribute bag.y numeric 
 @attribute bag.x numeric 
 @attribute bag.z numeric 
```
What is the advantage of using this `relational` type? Just want to understand whats going on here.

**Comment by joaquinvanschoren** [comment]
This is a multi-instance learning problem. You should not use standard
classification algorithms on it. Does it have a classification task?

**Comment by giuseppec** [comment]
Yes, task 7537 and 7542 are supervised classification tasks that seem to use this data set (see http://www.openml.org/d/1438). However, I think it is okay to define supervised classification tasks that use this data set, as one can for example create several distance-based features from x,y and z. Do we have flows on OpenML that support "multi-instance learning"? I could not find a task type like this.

**Comment by joaquinvanschoren** [comment]
Sorry, of course that makes perfect sense, as long as the classifier can
handle that type of data.

However, I'm not sure you can convert it to a normal table as you describe.
In multi-instance learning you have 'bags' of instances, and a label for
that bag (e.g. positive). You know that at least one instance in that bag
is positive, but you don't know which. It's like knowing that one key in
the keychain works on your lock, but you don't know which.

However, WEKA has a wrapper method that allows you to run any classifier on
a MI dataset, so it is possible.

In fact, I just tried that, works fine (and OpenML handles it fine as
well): http://www.openml.org/r/506057
Given that this is a multi-class dataset with missing values, I had to use
some wrappers.

I would look around to see how other R packages handle multi-instance
learning, or see how the WEKA wrapper does it?

**Comment by giuseppec** [comment]
Thanks for clarification. Then I guess I have to talk to @berndbischl how we should read such data in R and add support for this data-format in the farff package (the RWeka package also does not support this arff files of this format).
