### ISSUE TITLE
run API does not return error_message field

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#232]
Look for example at the description.xml which you can manually download from the url http://www.openml.org/r/506421. The xml file contains a field

```
<oml:error_message>Error in training the model: 
 Error in na.fail.default(structure(list(class = structure(c(2L, 1L, 1L,  : 
  missing values in object
</oml:error_message>
```

This `oml:error_message` field is not returned if I use the API: http://api_new.openml.org/v1/run/506421
Is this intended or just a bug?

**Comment by joaquinvanschoren** [comment]
We updated the way we store errors a few weeks ago, making sure that you
only see actual client-side errors, not server errors or warnings.
Unfortunately, this introduced a bug, which is now fixed.

I checked and the api returns the error correctly now.
