### ISSUE TITLE
run/list should list if the run was created with R, python, weka...

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#233]
I think it would help if one can subset the list of runs according to the programming language that created the run. Of course you can do this by downloading the flow and then looking up if it is a R flow, Weka flow... What do you think?

**Comment by joaquinvanschoren** [comment]
Hmm, that would be useful, but I can't easily see which programming
language is used in the flow right now...
We would have to add that as a (required?) field in the run description?

**Comment by giuseppec** [comment]
Maybe yes. I think we have a `language` field for flows, but the field contains something like "English" and not programming language (not sure why we need the language). We could either use this field or introduce another programming_language field.
R and Weka flows could be identified by their `external_version`. They seem to start with `Weka_...` and `R_...` (and I have also seen `sklearn_`).

**Comment by joaquinvanschoren** [comment]
Yes, we could the language field for that. The external version indeed
often has that form, but not always.
Another question is whether you really want to know the programming
language or the library. E.g. in Java you have WEKA, KNIME, RapidMiner, all
very different.

**Comment by giuseppec** [comment]
Can be closed since we all seem to use the `external.version` field for this.
