### ISSUE TITLE
many runs are not listed although they exist 

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#234]
How can this happen?

A tiny example (there are much more runs for which this is happening):

This http://api_new.openml.org/v1/evaluation/list/run/148569 gives me the result of an existing run (without errors), however http://api_new.openml.org/v1/run/list/run/148569 tells me that there is no run?

**Comment by joaquinvanschoren** [comment]
I found 21 (almost consecutive) runs where this happened. There was
apparently  a server error, but the runs where evaluated successfully
afterwards. However, the error flag was not lowered after that happened,
and hence not returned.

Should now all be fixed.

**Comment by giuseppec** [comment]
Here some more candidates: 148613 148570 465253  54739  54874
See also: http://www.openml.org/r/148613 -> no evaluations exist here.
Here a R-Code for a sanity check in order to find similar issues: https://github.com/openml/r/issues/156

**Comment by joaquinvanschoren** [comment]
Thanks, I'll update the index overnight.

**Comment by berndbischl** [comment]
@joaquinvanschoren 
Can we add that to Lars' Jenkins checks?

**Comment by berndbischl** [comment]
> Not sure if it should. This only affects the website.

sorry. I was maybe a bit confused. what I wanted to say is: we now download other things on top of normal data and tasks. so runs. we could unit test these also with Lars approach'?
Because we can already see that some of these look strange or dont work. 
Shall we open up a issue for that?

**Comment by joaquinvanschoren** [comment]
Closing this. We could open a new issue for unit testing runs, but it would take huge amounts of computation to re-evaluate all runs. We need to test something more specific.
