### ISSUE TITLE
evaluation/list/run/ should provide flow info

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#235]
Realistic use case:
I want to reproduce this kind of plot (Evaluations per flow): http://www.openml.org/t/1#!results
That is, I want to lookup, e.g. the AUC of all runs of task 1 and plot the name of the flow against the AUC values to see a ranking.

What we currently have to do:
1) Since `evaluation/list/run/` does not provide any information of the flow, we first have to lookup the flow.id of each run, which can be done by joining the results of `evaluation/list/run/` and `run/list/run/`.
2) Since `run/list/run/` does not provide the name of the flow, we have to do another join with `flow/list` 

So we have to do two joins to do something which many users might want to do. Can we solve this by returning at least the flow.id in  `evaluation/list/run/`? So a single join would be enough. This would be less error prone (see for example https://github.com/openml/OpenML/issues/234 which will lead to missing runs when joining `evaluation/list/run/` and `run/list/run/`).

**Comment by joaquinvanschoren** [comment]
Here you go, I added both the flow_id and task_id.
Also documented:
http://www.openml.org/api_docs/#!/evaluation/get_evaluation_list_run_ids

Cheers,
Joaquin

**Comment by giuseppec** [comment]
Thx. This should be enough, at least for my needs.
