### ISSUE TITLE
not all listing APIs provide tag information

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#238]
Apparently only the `task/list` API gives information about their tags, all the other listing APIs (e.g. run, data ...) don't. This should be changed.

**Comment by joaquinvanschoren** [comment]
What is the exact use case? Do you want all datasets with a given tag? If
so, it would make more sense to add a tag filter, e.g. /data/list/tag/foo

**Comment by giuseppec** [comment]
Yes, maybe a tag filter solves the problem (the use case I thought of were OpenML studies). For consistency, we should change this in `task/list`, right? At least on a long-term basis this would make more sense, otherwise we get a large `tag` column.

**Comment by joaquinvanschoren** [comment]
Yes, indeed.

**Comment by giuseppec** [comment]
Could you put this feature to the TODO-list for the workshop?

**Comment by joaquinvanschoren** [comment]
Do we still need this if you can filter for tags?

**Comment by berndbischl** [comment]
> Do we still need this if you can filter for tags?

clear yes

**Comment by joaquinvanschoren** [comment]
Could you give me a use case? Happy to do it, but it may slow down the
listing calls.

**Comment by giuseppec** [comment]
It seems to be already implemented, thx.
