### ISSUE TITLE
stochastic bug?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#239]
Sorry, I can only explain this bug with screenshots. When I do an API call sequentially, multiple times, it gives me different results. Currently, I have seen 3 different scenarios, here you can see two scenarios: http://imgur.com/a/ucO7j , in the third scenario I get:
"Run not found"
with exactly the same API call... I could not figure out why this happens sometimes, but this is causing Rcheck failings with different error messages. I think this is also something that @HeidiSeibold observed.

**Comment by HeidiSeibold** [comment]
Yes, I get different errors every time I run testthat.R

**Comment by joaquinvanschoren** [comment]
That is very weird, it could be that our database is dropping calls. We can
probably fix this on the server.

**Comment by joaquinvanschoren** [comment]
I think it is indeed the database dropping some subcalls when it is very busy. I will need to search for a way to detect when this happens.

**Comment by giuseppec** [comment]
Not sure if it helps but yesterday afternoon it happend again. Let's hope that it won't happen next week.

**Comment by larskotthoff** [comment]
Well I get this every time I start the job, so downloading tasks as fast as you can triggers the bug.

**Comment by larskotthoff** [comment]
I'm getting this after a while even if I pause 10 seconds between tasks.

**Comment by joaquinvanschoren** [comment]
Can you see the exact error code that is returned? Or: how would I get that
from the OpenML R package?

**Comment by larskotthoff** [comment]
Run this code and wait until it crashes:

    library(OpenML)
    tasks = listOMLTasks() # Fetches all tasks
    for (id in tasks$task.id) {
      print(id)
      task = getOMLTask(task.id = id)
    }

**Comment by giuseppec** [comment]
I have observed that when it crashes, it sometimes messes up the whole server for several hours and repeating one api call several times yields different bugs.

**Comment by joaquinvanschoren** [comment]
Jan said this may be due to some heavy experiments he was running. Does
this still happen?

**Comment by larskotthoff** [comment]
Yep.

**Comment by joaquinvanschoren** [comment]
I think we have found it. We have tested it locally and pushed the fix to the test server (test.openml.org). Could you please do a test (run unit test or better stress test) on the test server? If that passes we'll push it to the production server.

**Comment by larskotthoff** [comment]
How do I use this? If I change the server URL from http://api_new.openml.org/v1 to http://test.openml.org/v1 I get 404s.

**Comment by joaquinvanschoren** [comment]
http://test.openml.org/api/v1

**Comment by joaquinvanschoren** [comment]
Also, don't use api_new anymore, just use www.openml.org/api/v1 for the production server. api_new works now but will break once we switch to https.

**Comment by larskotthoff** [comment]
Ok, thanks. Job started and it's looking good so far!

**Comment by larskotthoff** [comment]
I'm getting

    Downloading from 'http://test.openml.org/api/v1/data/45' to '/tmp/Rtmpvuaw0M/cache/datasets/45/description.xml'
    Error in parseXMLResponse(content, msg = paste0("Getting ", gsub("_",  : 
      Error (code = 112) in server / XML response for: Getting data set description
		No access granted.
		
    Calls: getOMLTask ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
    Execution halted

for dataset 103. Is that intentional?

**Comment by giuseppec** [comment]
Hm seems to be because task 103 uses dataset 45, which seems to be not accessible, see http://www.openml.org/d/45 . Maybe this is invisible data set? or private data? @joaquinvanschoren ?

**Comment by joaquinvanschoren** [comment]
Yes, it is private.

**Comment by giuseppec** [comment]
I guess this is fixed now. Will reopen if I stumble over this again.
