### ISSUE TITLE
Getting Flow with id 1 does not work

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#243]
http://www.openml.org/api_new/v1/flow/1
This URL does not return anything, seems like server is closing the connection.
When listing flows, the flow with id 1 does exist however.

Also, when accessing the list resource without authentication the server is returning 500 instead of not authorized.

**Comment by janvanrijn** [comment]
Due to a series of historic bugs, flow 1 was polluted with subflows, hyperparameters and even configurations. I cleaned it up today
