### ISSUE TITLE
WebSite does not react on back properly

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#245]
Go to http://www.openml.org/api_docs/#!/data/get_data_id
Enter some id, try the rest api.
The results show.
Hit back on browser. The results are still visible.

**Comment by joaquinvanschoren** [comment]
Thanks, but I have no idea how to fix it. I think this is a property of the JS lib used to test-run the calls.
Since this is not a major issue, I propose we leave it as it is? You can still easily click away the modal.

**Comment by joaquinvanschoren** [comment]
Hmm, I have no idea how to fix this. This is some weird behaviour of the
Documentation library.

**Comment by janvanrijn** [comment]
Is this still the case? We are two year further, there is probably an update for this library by now :)

**Comment by joaquinvanschoren** [comment]
Moved to a new library on the new frontend.
