### ISSUE TITLE
WebPage creates weird webpage on submitting invalid Flow

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#246]
Add new flow, click submit immediately.
The page shown is as follows - nothing clickable

![image](https://cloud.githubusercontent.com/assets/3618465/13772276/90d2a71c-ea93-11e5-9485-5d3fd31fe8d4.png)

**Comment by joaquinvanschoren** [comment]
Auch, ok, will fix soon

**Comment by jaksmid** [comment]
Actually, I am getting this even on valid submits

**Comment by joaquinvanschoren** [comment]
Yes, noticed that too

**Comment by janvanrijn** [comment]
Luckily, we can no longer upload flows through the webinterface. Will close
