### ISSUE TITLE
RestApi Reference is missing entries

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#247]
There is no entry of /data/qualities/list on the http://www.openml.org/api_docs/.
However, this part of API is functional and returns the list of all metafeature names:

<oml:data_qualities_list xmlns:oml="http://openml.org/openml">
      oml:qualityClassCount/oml:quality
      oml:qualityClassEntropy/oml:quality
      oml:qualityDecisionStumpAUC/oml:quality
      oml:qualityDecisionStumpErrRate/oml:quality

Etc.

**Comment by janvanrijn** [comment]
Cool, thanks. @joaquinvanschoren How can we update the swagger docs?

**Comment by joaquinvanschoren** [comment]
Done :)
https://www.openml.org/api_docs#!/data/get_data_qualities_list

**Comment by janvanrijn** [comment]
I don't see it, is that the right link?

**Comment by joaquinvanschoren** [comment]
Yes. I can see it? It’s ‘List all data qualities’

**Comment by janvanrijn** [comment]
Thanks!
