### ISSUE TITLE
documentation of POST requests

### ISSUE THREAD

**Issue by TGlas** [openml/OpenML#255]
I'd love to see some more documentation on the differences between GET and POST requests in the REST API, in particular which parameters go where. It seems that we have the following cases:
- GET parameters other than the api_key are part of the URL, e.g., /data/{id} - here "id" is a parameter.
- In a GET request, the api_key is transferred as a URL parameter, i.e., [url]?api_key=[...]
- In a POST request, all parameters (including the api_key) are in form data inside the request body.
  It would also be useful to output the request body (not only the response body) in response to the "TRY" button.

**Comment by joaquinvanschoren** [comment]
Has been available for a while. Also see https://new.openml.org/api
