### ISSUE TITLE
upload run always returns 202 "Please provide run xml"

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#263]
Uploading runs is not possible anymore. This is most easily seen when downloading a run and trying to reupload the run.xml and the prediction.arff (e.g. via http://www.openml.org/api_docs/#!/run/post_run) .
This gives:

```
{
  "error": {
    "code": "202",
    "message": "Please provide run xml"
  }
}
```

With response code 450

**Comment by joaquinvanschoren** [comment]
We had a full disk. It should be working again now.
