### ISSUE TITLE
Query API [feature request]

### ISSUE THREAD

**Issue by TGlas** [openml/OpenML#264]
This is a proposal / feature request for a more flexible OpenML query API. The SQL interface allows for full flexibility, however, I would prefer to hide it entirely from the user. And the existing interface is very restricted, leaving the burden to filter ID lists and to connect object types to the user.

My proposal is to introduce the following interface functions:

*  `/data/query`
*  `/task/query`
*  `/flow/query`
*  `/run/query`

All of these take a single argument, the condition (a string). The rationale is to keep the interface generic and extensible. The functions return the collection of all objects of the given type that fulfill the condition. There must be a clear-cut syntax for conditions, the violation of which results in an error message.

For now I think that the following two types of elementary conditions would do:

*  property operator value (equality or range check of a property)
*  `tag` tagname (require the presence of a tag)

Tag names are strings, values are strings or numbers. Operators are from the set `==`, `!=`, `<`, `<=`, `>`, and `>=`. Property names are more complicated, they act like members in object oriented programming. For example, a run has the properties "task" and "flow", a task has the property "dataset", and a dataset has the property "NumberOfInstances". To find all runs on datasets with more than a million points the condition reads
`task.dataset.NumberOfInstances > 1e6` .
As a full request it becomes (url-encoding dropped for readability)
`/run/query?api_key=...&condition=task.dataset.NumberOfInstances > 1e6`.
Of course, the properties of each object type must be defined in the documentation.

Elementary conditions can be combined with the boolean operators AND, OR and NOT, and parentheses are used the usual way. Actually, this part is not important, simple conjunction suffices. A further extension is to allow for arithmetic operators and for properties everywhere in expressions. Example: NumberOfInstances >= 10 * NumberOfFeatures.

The interface is easy to extend by adding new properties and even object types (e.g., task types), and also by adding new conditions, e.g., marked with keywords (similar to the `tag` keyword above). I am well aware that the proposal is not easy to implement on the database level, however, it would add a great deal of flexibility.

**Comment by joaquinvanschoren** [comment]
I believe this is now solved by #268 and the new querying filters (www.openml.org/api_docs). Is there still something missing? 

Note that using the SQL interface is not recommended, in fact we would like to close it in the near future. @janvanrijn

**Comment by TGlas** [comment]
I did not have time to follow up on this, but the filters indeed look very nice! They should cover all relevant cases, so no need for a query syntax. I'll close this for now.
