### ISSUE TITLE
List estimation procedures on website

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#265]
Currently, a user cannot find out the estimation procedures in an easy way as they are mixed with evaluation measures.

**Comment by joaquinvanschoren** [comment]
There is a filter in the left menubar, is this not what you need?
http://www.openml.org/search?q=type%3Aestimation_procedure&type=measure

**Comment by mfeurer** [comment]
This is exactly what I was looking for. Don't know why I didn't see this yesterday? Thanks!
