### ISSUE TITLE
Compress return of APIs to allow faster serving of files

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#268]
On my machine, it curretly takes ~60 seconds to load result of `task/list`. Half of that time is spent receiving the json file from the server, this are approx. 10MB. By zipping it, I was able to reduce it to 1.1MB, so there is a lof of redundancy. Thus, I assume that enabling http compression could speed up the API calls. Would something like this be possible from the server side?

**Comment by TGlas** [comment]
This would be a great feature. For downwards compatibility please be careful to compress only if the request indicates that the client supports it, i.e., by specifying the Accept-Encoding http header. See also
[https://en.wikipedia.org/wiki/HTTP_compression](url).

**Comment by giuseppec** [comment]
For the paper this would be a great feature because the XML file returned from the `task/list` API is currently 60MB which takes over 3 minutes... (zipped this would be only 3MB).
I think for the future of OpenML it is relevant to change something here. Currently `task/list` gives you everything and we have to subset the complete list afterwards in R, python... Wouldn't it make more sense to modify the API so that we could directly do requests like `task/list/NumberOfInstances/1,100/NumberOfNumericFeatures/1,5/` which should return all tasks with 1-100 instances and 1-5 features?

**Comment by TGlas** [comment]
+1
Queries for "all objects of this type" are not scalable. They have to be replaced with filtering functionality. That's actually a much better solution than compression, which only alleviates the problem without addressing its core.

**Comment by mfeurer** [comment]
+1 for filtering functionality. Nevertheless, not every internet access has the same speed as the one of a university computer. Thus, I still like to see compression implemented.

**Comment by joaquinvanschoren** [comment]
Thanks. We can implement filtering functionality similar to what we did for
runs and evaluations. I'll do this for the most common properties (number
of instances, features, task type,...)

For the compression, we can do this through the web server, you would then
need to send the following header:
Accept-Encoding: gzip, deflate
and then I can make it happen that you'll get a zip that you then have to
inflate.

Does that sound good?

**Comment by mfeurer** [comment]
Sounds good to me.

**Comment by giuseppec** [comment]
For me this sounds good, lets try this. Compression is then optional right (for reverse compatibility)? Don't forget to do this also for `data/list` API. For now, this would help a lot. Later, we maybe can think if we also need something similar for run-evaluations like `evaluation/list/auc/0,0.5` ...

**Comment by joaquinvanschoren** [comment]
Compression would work for EVERY request, and you choose when you want to
use it by setting that header in your request.

**Comment by TGlas** [comment]
Yes, compression for every request (on the webserver level) is the way to go, provided that the client indicates support.

For the filtering, covering the most common attributes is a good start. But why not make it very general? Is it difficult to handle a string composed of (in)equalities and boolean operators? For example

    (n >= 100 AND n < 10000) OR n < 2 * p

Of course the names of the properties must be fixed, i.e., "n" and "p" above, and the available operators must be defined.

**Comment by joaquinvanschoren** [comment]
That boolean function is very hard to implement in a RESTful way, we would
need to allow functions instead of using HTML syntax, which brings up a
whole bunch of other issues. Would it not be easier to do the OR yourself
(server side) by merging the results of two requests?

**Comment by TGlas** [comment]
The OR is probably not important, AND and NOT are enough :)
Jokes aside, I am missing the problem. We can pass arbitrary strings as parameters. Example:

    n >= 100 AND n < 10000

Actual query with URL-encoding applied:

    http://www.openml.org/api/v1/json/data/query?api_key=123&n+%3E=+100+AND+n+%3C+10000

Well, the need to encode the operators is somewhat nasty, but trivial for a machine.

I just thought that this would be attractive as a general solution that applies to all kinds of entities: data and tasks and flows, etc. I am not an expert on this, maybe this is against the spirit of a RESTful API, but it looks okay to me.

**Comment by joaquinvanschoren** [comment]
The 'issue' is that we choose HTML syntax for the API, hence you would need
to do something like
/data/NumberOfInstances/100..10000/NumberOfFeatures/0..20
This is possible if we limit the possible options to something
maintainable. Does that sound ok?

Using arbitrary functions like you use above is definitely possible to
implement but more work to maintain. Also, we would need to parse this on
the server side and thus need a 'contract' on what is allowed, which will
be quite some work and perhaps not very intuitive to use...

**Comment by TGlas** [comment]
I see. What you propose covers 99% of the use cases with far less effort, better maintainability, and is consistent with the existing interface. Makes perfect sense!

**Comment by joaquinvanschoren** [comment]
Compression is now working. For instance, try:
```
wget --header="Accept-Encoding: gzip,deflate" http://www.openml.org/api/v1/json/task/list/limit/1000?api_key=5c4fef1424a7ff1d3cd33640bf90acb1
```
and compare with
```
wget http://www.openml.org/api/v1/json/task/list/limit/1000?api_key=5c4fef1424a7ff1d3cd33640bf90acb1
```

**Comment by joaquinvanschoren** [comment]
Filters are also implemented. You can use following filters:
* data_id (the id of the main dataset in the task)
* NumberOfInstances
* NumberOfFeatures
* NumberOfClasses
* NumberOfMissingValues

For the last four, you can give a specific value, or a range like 0..10.
For instance, try:
```
http://www.openml.org/api/v1/task/list/NumberOfInstances/0..50/NumberOfFeatures/0..10
```

**Comment by joaquinvanschoren** [comment]
Also documented now:
http://www.openml.org/api_docs/#!/task/get_task_list_filters

**Comment by joaquinvanschoren** [comment]
I also added the same filters for data/list
Documentation here: http://www.openml.org/api_docs/#!/data/get_data_list_filters

**Comment by mfeurer** [comment]
Very cool, thanks for enabling the compression. Now, parsing the JSON with the builtin python module seems to be the bottleneck :(

Also, would it be possible to serve arff files compressed as well? They can be quite large as well.

**Comment by joaquinvanschoren** [comment]
I think that all responses are compressed now. Did you try to download an
arff file with the compression flag?

**Comment by mfeurer** [comment]
Yes, the library I'm using sends this flag by default for all requests.

**Comment by joaquinvanschoren** [comment]
Sorry, I wanted to cancel my earlier response because it was obviously
stupid, but it was sent already :)

I also thought I could easily enable this, but it took me a few hours. It
now works (try it).

However, there are a few caveats:
* It only works if the dataset file returned by the server actually has an
.arff extension. Some datasets still(?) have an auto-generated name like
php13ggh, I need to see how to fix that. In any case, I expect that we will
fix this server-side soon.
* I made it work by changing the mime-type in the header set by the server
for dataset downloads. It used to be application/octet-stream, now it is
text/plain for all arff files. For some reason apache doesn't want to
compress octet-streams. I need to talk to Jan to see if there is any reason
why the mime-type used to be octet-stream. If there is a good reason for
that, I may have to revert and find another solution to compress the
datasets.

Cheers,
Joaquin

**Comment by mfeurer** [comment]
Cool, most datasets are now compressed, as you noted, only if the filename ends on .arff. Nevertheless, it seems that splits aren't encoded yet. I'm not sure how important that is, I only found it's the case.

**Comment by joaquinvanschoren** [comment]
curl says that they are encoded:
```
$ curl -I --compress
http://www.openml.org/api_splits/get/1/Task_1_splits.arff
HTTP/1.1 200 OK
Vary: Accept-Encoding
Content-Encoding: gzip
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Type: text/plain
```
Do you have a counter example?

**Comment by mfeurer** [comment]
Yes, splits on the test server:

```
$ curl -I --compress http://capa.win.tue.nl//api_splits/get/1/Task_1_splits.arff
HTTP/1.1 200 OK
Date: Tue, 09 Aug 2016 13:25:30 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.5.33
Set-Cookie: ci_session=a%3A5%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%2215e33cd523bf5572b61eee9ac0e01ffc%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A15%3A%22132.230.166.218%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A11%3A%22curl%2F7.35.0%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1470749130%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3B%7D82f69acd57ab61f16f4c19784a3b73ce; expires=Tue, 09-Aug-2016 15:25:30 GMT; Max-Age=7200; path=/
Content-Length: 123867
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Connection: close
Content-Type: text/plain; charset=UTF-8
```

**Comment by joaquinvanschoren** [comment]
Thanks, I forgot to configure the test server. Done now :)

**Comment by mfeurer** [comment]
Nice, thank you very much. I'll keep this open and close it once the files with random names are compressed as well.

**Comment by mllg** [comment]
@giuseppec @jakobbossek Does this work in R? Can we just pass `httr::add_headers()` to `GET()` in `download.R`?

**Comment by jakobbossek** [comment]
@mllg yes. We can pass additional header to `httr::GET`. Should be something like:
```splus
GET("www.test.com", add_headers(Accept_Encoding = "gzip"))
```

**Comment by jakobbossek** [comment]
@mllg We already benefit from compression.
```splus
library(httr)
response = GET("http://capa.win.tue.nl//api_splits/get/1/Task_1_splits.arff")
print(response$headers[["content-encoding"]])
[1] "gzip"
```

**Comment by mfeurer** [comment]
Hey there, it seems like a lot of data files end on '.ARFF' now, and are no longer compressed. It would be great if those files could be send compressed.

**Comment by joaquinvanschoren** [comment]
After some digging, I found the following:
* For the /api/v1/ endpoint, all data (json,xml,arff,...) should be compressed fine
* For the /data endpoint, arff/csv files are sent as uncompressed attachments. From my understanding, it is not easy to transfer attachments in compressed form, especially not if proxies are involved.

I can easily switch off the line that forces data files to be sent as attachments. In that case, the arff/csv data is simply compressed and streamed (I tested it and it works fine). It is also a *lot* faster to download.

However, I guess that @janvanrijn used attachments for a reason, so I'd like to hear his feedback on whether we could send data as compressed streams rather than uncompressed files. 
@amueller, did you request csv files to be sent as attachments?

Maybe it has to do with the naming of downloaded files? Attachments can be easily renamed.

**Comment by TGlas** [comment]
Just a hint, I am not the definite expert on this: If I remember correctly, then gzip compression can be enabled on the level of the transfer and on the level of the content:
https://stackoverflow.com/questions/11641923/transfer-encoding-gzip-vs-content-encoding-gzip
Maybe switching to transfer encoding can help here?

**Comment by mfeurer** [comment]
In the python API we're right now checking whether content encoding is turned on. For most of the datasets this is actually the case. If transfer encoding will be turned on we can simply check a different header. I'll add a check to my rudimentary dataset checker to ensure that compression works.

**Comment by joaquinvanschoren** [comment]
@TGlas: I looked into this yesterday, but it didn't seem to do a lot. I think that this is because transfer encoding only works hop-to-hop, so proxies in between are uncompressing it before it gets to you. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

Nevertheless, I now switched it on, using the header:
```    header('Content-Transfer-Encoding: base64'); ```

This website tells me it's compressed no matter whether I use that header or not:
https://checkgzipcompression.com/?url=https%3A%2F%2Fwww.openml.org%2Fdata%2Fdownload%2F3608

@mfeurer: can you tell me which datasets are not compressed? That will be good to know.

**Comment by amueller** [comment]
right now the sklearn PR doesn't actually use the CSV ... might do in the future though... I would like ``pd.read_csv(url)`` to work, because that's really really easy.

**Comment by TGlas** [comment]
@joaquinvanschoren: True, content-encoding seems to be the right thing to do, due to dumb proxies. Anyway, why base64? This bloats the data by 33%, compared to "binary" transfer. 7bit channels were not heared in decades...

**Comment by joaquinvanschoren** [comment]
Sorry, reverted to using binary
![](http://s2.quickmeme.com/img/d6/d6a1143f571184db25f94613edd43b40af6d3a629221aba00d9efdcfef5efd84.jpg)

@amueller This works fine:
>>> pd.read_csv("https://www.openml.org/data/v1/get_csv/61")

However, for some other datasets I get an 'IncompleteRead' error.
Since it only fails on some datasets, the problem is likely not with the encoding. Investigating...

Btw, what do you use in the sklearn PR? The arff data?

**Comment by amueller** [comment]
yes, using the arff for now. But haven't finished the PR after the API got updated.

**Comment by joaquinvanschoren** [comment]
I pushed a fix. This seems to work fine now.
```
pd.read_csv("https://www.openml.org/data/v1/get_csv/61")
```

**Comment by mfeurer** [comment]
The following datasets are currently downloaded uncompressed:

    2, 15, 62, 198, 279, 300, 307, 308, 310, 311, 312, 313, 315, 316, 327, 328, 329, 333, 334, 335, 336, 337, 338, 339, 340, 342, 343, 344, 345, 346, 350, 351, 354, 357, 374, 376, 379, 380, 480, 486, 558, 572, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 664, 671, 673, 674, 676, 689, 691, 700, 703, 704, 709, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1091, 1092, 1098, 1099, 1167, 1168, 1169, 1176, 1216, 1217, 1218, 1220, 1233, 1245, 1412, 1414, 1419, 1420, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1432, 1433, 1434, 1435, 1436, 1441, 1442, 1443, 1444, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1600, 4060, 4061, 4062, 4067, 4068, 4140, 4329, 4340, 4550, 6332, 23380, 23381, 40509

The downloading happened between 10AM and 12PM.

**Comment by mfeurer** [comment]
Here's an updated list of uncompressed files:

    2, 3, 6, 7, 15, 62, 125, 126, 156, 157, 158, 198, 264, 271, 272, 279, 300, 307, 308, 310, 311, 312, 313, 315, 316, 327, 328, 329, 333, 334, 335, 336, 337, 338, 339, 340, 342, 343, 344, 345, 346, 350, 351, 354, 357, 372, 374, 376, 379, 380, 480, 486, 558, 572, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 664, 671, 673, 674, 676, 678, 682, 687, 688, 689, 690, 691, 692, 693, 694, 695, 698, 699, 700, 703, 704, 709, 710, 711, 717, 718, 719, 720, 721, 722, 752, 760, 851, 853, 858, 859, 873, 896, 897, 898, 899, 900, 902, 903, 905, 940, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1091, 1092, 1098, 1099, 1149, 1151, 1152, 1157, 1167, 1168, 1169, 1176, 1182, 1204, 1205, 1206, 1207, 1214, 1216, 1217, 1218, 1219, 1220, 1233, 1245, 1355, 1385, 1412, 1414, 1419, 1420, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1432, 1433, 1434, 1435, 1436, 1441, 1442, 1443, 1444, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1600, 4136, 4140, 4153, 4329, 4340, 4550, 6332, 23380, 23381, 23383, 40498, 40499, 40509, 40673, 40680, 40681, 40692, 40695, 40698, 40699, 40701, 40702, 40715, 40753, 40945

**Comment by joaquinvanschoren** [comment]
Can you tell me how you tested this? I tried the first few, and they are all compressed.

```
> curl -I -H 'Accept-Encoding: gzip,deflate' https://www.openml.org/data/download/2
HTTP/1.1 200 OK
Date: Sat, 04 Nov 2017 22:58:13 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: ci_session=56a51c40d0f52d02c038411b4664f12ee87d97cf; expires=Sun, 05-Nov-2017 00:58:13 GMT; Max-Age=7200; path=/; HttpOnly
Expires: 0
Cache-Control: must-revalidate
Pragma: public
Content-Description: File Transfer
Content-Disposition: attachment; filename=dataset_2_anneal.ORIG.arff
Content-Transfer-Encoding: binary
Connection: keep-alive
Keep-Alive: timeout=300, max=500
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Type: text/plain;charset=UTF-8
```

**Comment by joaquinvanschoren** [comment]
I just checked all of them, and compression seems to be enabled for all.

**Comment by mfeurer** [comment]
I can confirm, so far everything I downloaded today is compressed. Great job!
