### ISSUE TITLE
Error when uploading a run with a oml:component field

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#270]
In https://github.com/openml/website/blob/master/openml_OS/views/pages/api_new/v1/xsd/openml.run.upload.xsd it is possible to use an xml that looks like

```
  <oml:parameter_setting>
    <oml:name>xval</oml:name>
    <oml:value>0</oml:value>
    <oml:component>rpart</oml:component>
  </oml:parameter_setting>
``` 

However, if I have such a `<oml:component>rpart</oml:component> ` field in my xml, the server returns an error

```
<oml:error xmlns:oml="http://openml.org/openml">
	<oml:code>213</oml:code>
	<oml:message>Parameter in run xml unknown</oml:message>
	</oml:error>
```

**Comment by janvanrijn** [comment]
Component fiels requires an id, rather than name, right?
Op 27 mrt. 2016 21:18 schreef "giuseppec" <notifications@github.com>:

**Comment by giuseppec** [comment]
Hm, the xsd says 
`<xs:element name="component" minOccurs="0" maxOccurs="1" type="xs:string"/> `
and 
`<!-- If the parameter belongs to a subcomponent of an implementation, the implementation name of that component. This name must match a component of the implementation that is stated above (in 'implementation_id'). --> ` therefore I thought that just a string is also fine.
Ok, but this means that I have to use a flow.id here and the flow must be already available on the server before I can use it here right? 
If this is the case, I have to talk to @berndbischl how we can make use of the mlr-wrappers here...

**Comment by giuseppec** [comment]
@janvanrijn can we allow that only a string like `<oml:component>rpart</oml:component>` is allowed in the component field? This would simplify our life.

**Comment by giuseppec** [comment]
Nevermind, I found a solution how to handle this. However, I would need an answer in #274 as fast as possible, therefore I am closing this issue.
