### ISSUE TITLE
Cannot delete runs owned by myself + count of owned runs is wrong

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#271]
I currently have a total of four flows which I own according to http://www.openml.org/u/86/flows. Nevertheless, when I try to delete them via the web interface, I am asked for confirmation. When I confirm, nothing happens. When I try to delete the flows via the REST API I receive an error message indicating that I don't own the datasets. Furthermore, the counter of flows and runs is wrong here: http://www.openml.org/u/86.

**Comment by janvanrijn** [comment]
These are two separate issues. 
* es not counting correct
* potentially API bug (although I doubt that)

title states runs, url shows flows and error message states datasets. Which did you mean? Can we close this issue, as ES errors are represented in plenty issues and I doubt that the API error still is relevant

**Comment by mfeurer** [comment]
Yeah, let's close this for now as ES actually counts the number of my flows correctly (at the moment) and I don't want to delete things via the web interface any more. Also, it's three years old now, so not sure how relevant this still is.
