### ISSUE TITLE
Dataset state still in_preparation

### ISSUE THREAD

**Issue by mommi84** [openml/OpenML#272]
Hello,

about 12 hours ago, I've uploaded a dataset using the Java API: http://www.openml.org/d/23389
However, its state is still set to _in_preparation_. The arff file is fine, apart from the fact that it doesn't contain any class attribute. The issue is quite urgent, as I'm going to use OpenML as host for datasets used in a research paper.

Thank you.

**Comment by kazeevn** [comment]
The same thing for me: http://www.openml.org/d/23394

**Comment by joaquinvanschoren** [comment]
Hi, 23389 is not valid ARFF and therefore ignored for now.
23394 is now processed.

**Comment by mommi84** [comment]
Hi, actually WEKA did manage to parse that file.
The issue seems in the Java library.

The same ARFF file:
- uploaded using the library: http://www.openml.org/d/23419 gets errors,
- uploaded using the web interface: http://www.openml.org/d/23420 is fine.
