### ISSUE TITLE
uploading complex workfow yields: Unable to store input setting

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#274]
I am getting the error message  `214: Unable to store input setting` when I try to upload a flow which is a combination of 3 flows (a flow as a combination of 2 flows seems to work). 

Here the xml I am trying to upload:
```
<oml:run xmlns:oml="http://openml.org/openml">
  <oml:task_id>3736</oml:task_id>
  <oml:flow_id>3521</oml:flow_id>
  <oml:parameter_setting>
    <oml:name>mtry</oml:name>
    <oml:value>4</oml:value>
    <oml:component>3519</oml:component>
  </oml:parameter_setting>
  <oml:parameter_setting>
    <oml:name>fw.method</oml:name>
    <oml:value>rf.importance</oml:value>
    <oml:component>3520</oml:component>
  </oml:parameter_setting>
  <oml:parameter_setting>
    <oml:name>fw.perc</oml:name>
    <oml:value>0.5</oml:value>
    <oml:component>3520</oml:component>
  </oml:parameter_setting>
  <oml:parameter_setting>
    <oml:name>osw.rate</oml:name>
    <oml:value>1</oml:value>
  </oml:parameter_setting>
  <oml:parameter_setting>
    <oml:name>openml.seed</oml:name>
    <oml:value>1</oml:value>
  </oml:parameter_setting>
  <oml:parameter_setting>
    <oml:name>openml.kind</oml:name>
    <oml:value>Mersenne-Twister</oml:value>
  </oml:parameter_setting>
  <oml:parameter_setting>
    <oml:name>openml.normal.kind</oml:name>
    <oml:value>Inversion</oml:value>
  </oml:parameter_setting>
  <oml:output_data>
    <oml:evaluation>
      <oml:name>usercpu_time_millis_testing</oml:name>
      <oml:flow>openml.evaluation.usercpu_time_millis_testing(1.0)</oml:flow>
      <oml:value>0.18000000010943</oml:value>
    </oml:evaluation>
    <oml:evaluation>
      <oml:name>usercpu_time_millis_training</oml:name>
      <oml:flow>openml.evaluation.usercpu_time_millis_training(1.0)</oml:flow>
      <oml:value>43.3899999998976</oml:value>
    </oml:evaluation>
    <oml:evaluation>
      <oml:name>usercpu_time_millis</oml:name>
      <oml:flow>openml.evaluation.usercpu_time_millis(1.0)</oml:flow>
      <oml:value>43.570000000007</oml:value>
    </oml:evaluation>
  </oml:output_data>
</oml:run>
```

**Comment by janvanrijn** [comment]
Let's have a look at the flow xml: http://www.openml.org/api/v1/flow/3521

What I see from here is that the XML consists of three components: the main flow (id 3521), and two subcomponents (randomForest with id 3519 and randomForest.filtered, 3522). 
Q1: Isn't it the case that there should have been a hierarchy? Like main flow is parent of randomForest.filtered is parent of randomForest? This is not reflected in the XML. 
Q2: You are trying to set a parameter fw.perc, of component 3520. Shouldn't this be 3522? If I change this, it works. See: http://www.openml.org/api/v1/run/566999 (don't mind the uploaders name)

**Comment by giuseppec** [comment]
Could you explain Q1? Where do you see that there is no hierarchy reflected in the XML? I thought the hierarchy has to be defined as follows:
Assume I want to upload the workflow "random forest + imputation + feature filter" as main flow, then
1) register all childflows, that is 
   a) register "random forest" (has some parameters)
   b) register "random forest + imputation" (has the parameters from random forest + parameters for imputation)
2) create main flow  "random forest + imputation + feature filter" that contains all childflows in the `component`  field.

Regarding Q2 you are right, the XML I posted here was outdated as I deleted some flows from the server again. However, it still does not work for me. Let me create a new clean example to show you what does not work for me. 
Here https://drive.google.com/open?id=0B7Xb1_ywA2noSHduN0lFcmhrNGM you can find the run XML and the ARFF file for the run, which is not possible to be uploaded to the server (I am getting `214: Unable to store input setting` ). Currently, I don't see what is wrong and why I am getting this error.

**Comment by giuseppec** [comment]
It seems to work if I remove all component fields in the run XML. Is that what I have to do to?

**Comment by joaquinvanschoren** [comment]
Hmm, I'm seeing this in the DB (I'm not sure why this doesn't show on the
website anymore):[image: Screen Shot 2016-04-27 at 11.16.18.png]
In your XML you reference a flow 3542, so I guess it complains because it
cannot find that component. If you remove the component ID then the server
assumes that the parameter belongs to the main (top level) flow. In your
case, your top-level flow seems to contain all parameters of the components
as well, hence the server is not complaining when you remove them. But is
this correct (from your point of view)?

Cheers,
Joaquin

PS. Also, I thought you didn't need to register each subflow beforehand,
but you can register an entire workflow including components in one go?
PPS. Today is a holiday in the Netherlands, so Jan may be slower in
replying.

**Comment by giuseppec** [comment]
My mind is blown, maybe I am misunderstanding the concept and don't know how to use it properly.

> In your XML you reference a flow 3542, so I guess it complains because it cannot find that component.

A component can be a `flow.id` right? And the flow `3542` exists on the server, so why does the server not find that component? http://www.openml.org/f/3542 does exist right?

> If you remove the component ID then the server assumes that the parameter belongs to the main (top level) flow. In your case, your top-level flow seems to contain all parameters of the components as well, hence the server is not complaining when you remove them. But is this correct (from your point of view)?

In mlr the top-level flow inherits all parameters from the subflows (@berndbischl correct me if I am wrong here), so this is the reason why all parent flows contain the same parameters as their child flows + some further parameters from the parent flow itself. And this is what we are uploading to OpenML.

>  PS. Also, I thought you didn't need to register each subflow beforehand, but you can register an entire workflow including components in one go?

Whats the difference? If I am able to register the subflows, why shouldn't I do this? Or am I doing it wrong, if I do this? I did this because it was easier for now to register each subflow, as we have this wrapping mechanism in mlr, e.g. for a worfklow "random forest + imputation + feature filter" and I can successively say 
1) upload "random forest"
2) upload "random forest + imputation"
3) upload "random forest + imputation + feature filter"
so that 1), 2) and 3) can be used as a workflow itself.

**Comment by joaquinvanschoren** [comment]
I think that something simply went wrong when you registered the top level
flow. It looks like you registered both 3542 and 3544, you linked 3544 as a
subflow of 3543, and then wanted to set the parameters for 3542.

If your parameters are all inherited, it should suffice to only add the
parameters to the top flow?

If you can first register all subflows and then the top flow, that is of
course fine.

Cheers,
Joaquin

**Comment by joaquinvanschoren** [comment]
Did you manage to find the problem?

**Comment by janvanrijn** [comment]
You can indeed either first register all individual flows, or just do it all at once. For OpenML this is all the same. The way you register first "random forest" then "random forest + imputation" and then "random forest + imputation + feature filter" is good as well. 

Btw, I cannot reproduce the problem because the xml files that you attached are linked to a non-existing flow (id 3543). Can you please provide some actual flow on which the problem occurs?
