### ISSUE TITLE
include serialized run when uploading run?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#276]
Hi,

according to http://www.openml.org/api_docs/#!/run/post_run there is a possibility to upload a `model_seriali...` file, which contains "the serialized model generated by the run". 
How can I make use of this via the API? And How do I download this serialized model?

**Comment by janvanrijn** [comment]
like uploading the predictions file. In this case give it the field name "model_serialized"

**Comment by giuseppec** [comment]
Ok cool, it seems to work with the API. I did this via http://www.openml.org/api_docs/#!/run/post_run by selecting the file and it did not work. BTW is there any filesize limit?

**Comment by berndbischl** [comment]
i would find it cool if we could do that for R as well

**Comment by giuseppec** [comment]
@berndbischl I wanted to abuse this functionality to upload the benchmarkResult for tuneWrappers: we agreed to upload the tune results for tuneWrappers and they are contained in the benchmarkResult, so I thought, we could directly upload the benchmarkResult.
We can upload two additional files with a run, `model_serialized` and `model_readable`. Suggestion: 
We can use `model_serialized` to store the benchmarkResult of a run (e. g. add a upload.bmr flag when uploading runs, for tuneWrapper the flag is always TRUE). Or do we want to use `model_serialized` differently?

**Comment by berndbischl** [comment]
i dont really get what we are discussing here? the thread started out with a very simple thing:
that we would like to upload the model, which is fit on the complete data of the task at the end, in a separate file. in our case, the trained mlr model, in an RDS file.

?

**Comment by giuseppec** [comment]
Yes, this is simple and we can do this. But if we say that `model_serialized` is always used for "the model, which is fit on the complete data of the task at the end", where do we want to upload the tune results for the tuneWrappers (as we discussed yesterday)? The tune results must be uploaded with the run (not with the flow/learner) and uploading this as `model_serialized` or `model_readable` is the only way I currently see.
Therefore, in case of a tuneWrapper, I had the intension to "abuse" the `model_serialized` slot and use it for the tune results.
I see two possibilities here:
1) Use `model_serialized` to upload  "the model, which is fit on the complete data of the task at the end" for all learners except for tuneWrappers, for those we use the `model_serialized` slot to upload the tune results (and not the model).
2) We kindly ask the server guys to allow to upload another binary file `tune_results` so that `model_serialized` can be always used for the model itself.
Sorry, that this issue is going a bit off-topic.

**Comment by joaquinvanschoren** [comment]
Is it not possible to upload additional files? Did you try? Maybe the
server checks whether it was defined in the task.

**Comment by berndbischl** [comment]
@janvanrijn @giuseppec 

what giuseppe and i agreed on:
a) we will upload the model_serialized, as it should be done. simple the fitted R model on the complete task
(it is an option for the user to do this)

b) model_readable we currently wont support

c) jan, can ypu pls help giuseppe to figure out how to upload the tuning traces?
giuseppe, pls also check your emails, subject "MLJ", some info was in there

d) jan, can you help to upload giuseppe to upload "custom" additional files? 
we create quite a lot of (useful) info in R, that we would like to store as well

**Comment by berndbischl** [comment]
> Is it not possible to upload additional files? Did you try? Maybe the
> server checks whether it was defined in the task.

we tried to check the API docs for this today, but found nothing?

**Comment by joaquinvanschoren** [comment]
No the trace is not documented right now.

Do you prefer the string format or columns format for the parameter
settings? (See separate mail)

**Comment by berndbischl** [comment]
> No the trace is not documented right now.

i was mainly asking here where it is doced how to upload extra files? custom ones, with custom names and content.

**Comment by giuseppec** [comment]
It is not doced but it seems to work in the same way as uploading predictions. Therefore I think we can close here. Regarding the tuning traces, I will open a new "todo" issue in our tracker and copy the important points from the "MLJ" mails.
