### ISSUE TITLE
listing API do not work

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#277]
Hi, it seems that all listing APIs do not work anymore (we get  "error": "no response from server"). A bachelor student needs this. Could you have a look and try to fix it?

**Comment by joaquinvanschoren** [comment]
I just tried /data/list. Seems to work fine?
What is not working?

**Comment by joaquinvanschoren** [comment]
Ah, looks like it was indeed broken for a little while because of a new
call. Working now.
