### ISSUE TITLE
Upload run error 214

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#278]
I am trying to upload a run to the test server and am presented with the error code 214. I pasted the xml to the bottom of this issue, if you need any other information please let me know.

    <?xml version="1.0" encoding="utf-8"?>
    <oml:run xmlns:oml="http://openml.org/openml">
	    <oml:task_id>10107</oml:task_id>
	    <oml:flow_id>3146</oml:flow_id>
	    <oml:parameter_setting>
		    <oml:name>n_jobs</oml:name>
		    <oml:value>1</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>verbose</oml:name>
		    <oml:value>0</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>random_state</oml:name>
		    <oml:value>52981</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>warm_start</oml:name>
		    <oml:value>False</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>penalty</oml:name>
		    <oml:value>l2</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>refit</oml:name>
		    <oml:value>True</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>scoring</oml:name>
		    <oml:value>None</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>class_weight</oml:name>
		    <oml:value>None</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>verbose</oml:name>
		    <oml:value>0</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>param_distributions</oml:name>
		    <oml:value>{'C': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000]}</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>iid</oml:name>
		    <oml:value>True</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>n_jobs</oml:name>
		    <oml:value>1</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>cv</oml:name>
		    <oml:value>None</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>max_iter</oml:name>
		    <oml:value>100</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>dual</oml:name>
		    <oml:value>False</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>solver</oml:name>
		    <oml:value>liblinear</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>pre_dispatch</oml:name>
		    <oml:value>2*n_jobs</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>tol</oml:name>
		    <oml:value>0.0001</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>fit_params</oml:name>
		    <oml:value>None</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>random_state</oml:name>
		    <oml:value>7624</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>estimator</oml:name>
		    <oml:value>sklearn.linear_model.logistic.LogisticRegression</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>multi_class</oml:name>
		    <oml:value>ovr</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>fit_intercept</oml:name>
		    <oml:value>True</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>intercept_scaling</oml:name>
		    <oml:value>1</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>C</oml:name>
		    <oml:value>1.0</oml:value>
		    <oml:component>2796</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>error_score</oml:name>
		    <oml:value>raise</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:parameter_setting>
		    <oml:name>n_iter</oml:name>
		    <oml:value>5</oml:value>
		    <oml:component>3146</oml:component>
	    </oml:parameter_setting>
	    <oml:tag>Python_3.4.4.</oml:tag>
	    <oml:tag>Sklearn_0.17.1.</oml:tag>
	    <oml:tag>NumPy_1.11.0.</oml:tag>
	    <oml:tag>SciPy_0.17.0.</oml:tag>
	    <oml:tag>Mon_May__2_17.59.30_2016</oml:tag>
	    <oml:tag>run_task</oml:tag>
	    <oml:tag>sklearn.grid_search.RandomizedSearchCV</oml:tag>
    </oml:run>

**Comment by janvanrijn** [comment]
You are referring to component 2796 which is not in the flow:
http://capa.win.tue.nl/api_new/v1/flow/3146

**Comment by mfeurer** [comment]
Thanks, there is an error in my code for retrieving existing flows.
