### ISSUE TITLE
Flow without a description and without possibility to download xml from website

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#279]
Hi, I just found a flow which I think is missing a description, which according to the xsd is one of only two required fields: [http://www.openml.org/f/1631](http://www.openml.org/f/1631). Also, there is no button for the download of the xml file. From the xml downloaded via the API, I can see it has a lot of components. None of these components is actually displayed on the flow page.

**Comment by joaquinvanschoren** [comment]
This is a flow with Stacking, which is not fully supported by the Weka plugin. I think this why the webpage does not show the components.

The description is actually not missing but it is empty, which apparently causes it not to be returned in the XML by the API (no description tag is added). This should indeed be fixed.

Datasets and flows don't have an XML download button. I'll try to add that soon.

**Comment by mfeurer** [comment]
So datasets and flows now have a button to download the XML, which solves parts of the issue.

I don't get why the components cannot be rendered as they are available in the XML.

However, I just found another issue. According to the API, [flow 1631](http://www.openml.org/f/1631) has [run 473350](https://www.openml.org/r/473350) which is not rendered.

**Comment by janvanrijn** [comment]
I think there is a general issue with the way the frontend shows information. This week we found many inconsistencies with the API. We should make a general issue for this, and it should be solved, as many users are not aware of the api, use the frontend and it looks very bad.

As of this issue, I deleted the flow and the run.
