### ISSUE TITLE
Testserver: link in run overview points to the production server

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#281]
![untitled](https://cloud.githubusercontent.com/assets/5320498/14985078/1a5bd25a-1146-11e6-9879-cdbb3405c181.png)

**Comment by TGlas** [comment]
A few more of these:

* Every single link in the blue header bar of test.openml.org, including the links the expandable menu on the left and the login field, refer to http://capa.win.tue.nl.
* The login form logs me into capa.win.tue.nl. If I switch back manually to test.openml.org then I am no longer logged in.
* One level further, if I manually open http://test.openml.org/guide (the link will not get me there, as explained above) and then click on "Developers / REST API Reference" then I end up at http://capa.win.tue.nl/api_docs/#!/data/get_data_id.
* Changing this manually to test.openml.org/api_docs/#!/data/get_data_id results in a broken (mostly empty) page.

**Comment by mfeurer** [comment]
I just checked and this seems to be fixed.
