### ISSUE TITLE
Run contains invalid parameters

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#282]
I just found [run 537363](http://www.openml.org/r/537363/json) which claims to be a run of sklearn.linear_model.LogisticRegression. Inspecting the [json file](http://www.openml.org/r/537363/json), we can see that it the [flow used for this run](http://www.openml.org/f/2856) actually is the sklearn.dummy.DummyClassifier. Shouldn't this be forbidden and somehow checked on upload?

**Comment by joaquinvanschoren** [comment]
It seems OK now. Maybe this was a mixup on the test server. Closing :).
