### ISSUE TITLE
Maximum flow length?

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#283]
I was trying to call the API call flow/exists with a flow name like `0404d5bdTESTSENTINEL999sklearn.pipeline.Pipeline(sklearn.preprocessing.data.OneHotEncoder__sklearn.ensemble.forest.ExtraTreesClassifier)` Although I registered the flow before, it wasn't found. When inspecting the website, I found that the name is truncated to ` 0404d5bdTESTSENTINEL999sklearn.pipeline.Pipeline(sklearn.preprocessing.data.OneHotEncoder__sklearn.ensemble.forest.ExtraTreesCla`, and when using that string in flow/exists I can find it. The truncated string is exactly 128 characters long. Is this the length limit of a flow name?

**Comment by joaquinvanschoren** [comment]
Currently the database allows a max. length of 128 characters. Shall I
increase that to 512?

**Comment by mfeurer** [comment]
Yes, please. This will solve it for the short term, assuming that users don't have more than around 8 components in a single flow. I will raise an exception in the python code in case this happens.

**Comment by joaquinvanschoren** [comment]
OK, updated to 1024 on both production and test server.

**Comment by mfeurer** [comment]
Solved. Thanks a lot.
