### ISSUE TITLE
Cannot delete flows any more

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#284]
According to the website, I own the following flows on the test server:

     3732, 3751, 3749, 3770, 3768, 3744, 3756, 3763, 3586, 3598, 3649, 3757, 3745, 3752, 3771, 3769, 3764, 3587, 3599, 3746, 3758, 3760, 3765, 3753, 3603, 3588, 3590, 3730, 3754, 3759, 3747, 3742, 3761, 3766, 3589, 3591, 3731, 3750, 3748, 3755, 3767, 3762, 3743

The flows have a description etc., see for example [http://capa.win.tue.nl/f/3732](http://capa.win.tue.nl/f/3732)

When I try to delete them via with `http://test.openml.org/api/v1/xml/flow/%d?api_key=%s` where `%d` is the flow ID, I only get the server response 'flow does not exists'. How is this possible?

**Comment by joaquinvanschoren** [comment]
That's likely because the test server should be used without the website
for now, sorry. The API should work fine, but I still need to set up a
separate ElasticSearch instance on the test server. Hence, what you see on
test.openml.org is a weird mixture of test server stuff and production
server stuff. The flow ID's that you see there are possibly not correct.

I'll try to do this somewhere next week.

**Comment by janvanrijn** [comment]
Can you please give me an up to date flow id? All these seem to be removed from the testserver already. 

(query returns an empty result: SELECT * FROM `implementation` WHERE id IN ( 3732, 3751, 3749, 3770, 3768, 3744, 3756, 3763, 3586, 3598, 3649, 3757, 3745, 3752, 3771, 3769, 3764, 3587, 3599, 3746, 3758, 3760, 3765, 3753, 3603, 3588, 3590, 3730, 3754, 3759, 3747, 3742, 3761, 3766, 3589, 3591, 3731, 3750, 3748, 3755, 3767, 3762, 3743))

**Comment by joaquinvanschoren** [comment]
Maybe they never existed on the test server. What you see on test.openml.org is not only what is on the test server. I understand this is annoying, and hope to fix it soon, but this should not be blocking?

**Comment by mfeurer** [comment]
According to the test server I own the following 505 flows:

```4521, 4526, 4519, 4571, 4576, 4569, 4552, 4557, 4590, 4595, 4540, 4545, 4533, 4538, 4583, 4588, 4603, 4608, 4564, 4381, 4386, 4379, 4401, 4406, 4432, 4437, 4420, 4425, 4393, 4398, 4413, 4418, 4374, 4367, 4362, 4343, 4348, 4350, 4355, 4723, 4728, 4691, 4696, 4711, 4716, 4684, 4689, 4704, 4709, 4451, 4456, 4449, 4502, 4507, 4499, 4470, 4475, 4463, 4468, 4444, 4494, 4514, 4487, 4482, 4641, 4646, 4639, 4672, 4677, 4622, 4627, 4660, 4665, 4653, 4658, 4634, 4615, 4610, 3864, 3852, 3826, 3833, 3814, 3819, 3821, 3799, 3802, 3807, 3840, 3838, 4329, 4331, 4324, 4317, 4300, 4297, 4285, 4312, 4292, 4305, 4336, 4730, 3803, 3808, 3810, 3827, 3834, 3815, 3822, 3860, 3865, 3853, 3858, 4399, 4421, 4426, 4419, 4382, 4387, 4370, 4375, 4433, 4438, 4414, 4394, 4402, 4407, 4368, 4616, 4609, 4661, 4666, 4659, 4642, 4647, 4630, 4635, 4623, 4628, 4673, 4678, 4654, 4611, 4471, 4476, 4469, 4452, 4457, 4490, 4495, 4440, 4445, 4510, 4515, 4503, 4508, 4464, 4483, 4488, 4705, 4700, 4685, 4680, 4692, 4697, 4349, 4351, 4363, 4356, 4344, 4318, 4320, 4325, 4332, 4298, 4306, 4286, 4293, 4301, 4313, 4541, 4546, 4539, 4591, 4596, 4589, 4522, 4527, 4572, 4577, 4560, 4565, 4553, 4558, 4534, 4584, 4604, 4337, 4712, 4717, 4724, 4729, 4731, 3816, 3823, 3828, 3830, 3835, 3804, 3809, 3861, 3866, 3854, 4275, 4314, 4302, 4294, 4287, 4319, 4299, 4307, 4326, 4321, 4338, 4333, 4167, 4340, 4352, 4345, 4491, 4496, 4489, 4441, 4446, 4439, 4422, 4427, 4472, 4477, 4460, 4465, 4410, 4415, 4453, 4458, 4434, 4484, 4674, 4720, 4371, 4376, 4369, 4403, 4408, 4383, 4388, 4364, 4395, 4390, 4357, 4561, 4566, 4559, 4511, 4516, 4509, 4542, 4547, 4530, 4535, 4580, 4585, 4573, 4578, 4523, 4528, 4504, 4554, 4631, 4636, 4629, 4662, 4667, 4592, 4597, 4600, 4605, 4650, 4655, 4643, 4648, 4624, 4617, 4612, 4725, 4693, 4698, 4713, 4718, 4681, 4686, 4701, 4706, 4732, 3800, 3805, 3817, 3829, 3831, 3836, 3850, 3855, 3862, 3867, 4702, 4707, 4721, 4726, 4694, 4699, 4714, 4719, 4288, 4310, 4290, 4315, 4303, 4295, 4308, 4322, 4327, 4334, 4396, 4389, 4372, 4377, 4384, 4404, 4365, 4360, 4391, 4579, 4601, 4606, 4581, 4586, 4632, 4637, 4620, 4625, 4593, 4598, 4644, 4613, 4618, 4156, 4531, 4536, 4529, 4492, 4497, 4512, 4517, 4562, 4567, 4500, 4505, 4550, 4555, 4543, 4548, 4524, 4574, 4339, 4353, 4346, 4341, 4358, 4651, 4656, 4649, 4670, 4675, 4663, 4668, 4682, 4687, 4411, 4416, 4409, 4461, 4466, 4459, 4442, 4447, 4430, 4435, 4473, 4478, 4423, 4428, 4454, 4485, 4480, 4733, 3856, 3801, 3806, 3818, 3820, 3851, 3832, 3863, 4431, 4436, 4429, 4412, 4417, 4450, 4455, 4380, 4385, 4400, 4405, 4443, 4448, 4424, 4397, 4392, 4671, 4676, 4669, 4652, 4657, 4640, 4645, 4633, 4638, 4664, 4486, 4479, 4501, 4506, 4532, 4537, 4462, 4467, 4520, 4525, 4493, 4498, 4513, 4518, 4474, 4481, 4715, 4710, 4722, 4727, 4703, 4708, 4366, 4359, 4347, 4354, 4373, 4378, 4342, 4361, 4551, 4556, 4549, 4621, 4626, 4619, 4602, 4607, 4599, 4582, 4587, 4570, 4575, 4614, 4594, 4544, 4563, 4568, 4695, 4690, 4683, 4688, 4227, 4291, 4289, 4311, 4309, 4316, 4304, 4296, 4284, 4323, 4328, 4330, 4335, 4734```

When I want to test an actual study, I need to register flows. If these already exist and I can't delete them, it's a blocker.

**Comment by janvanrijn** [comment]
Again, there's a great deal of flows that already are deleted. Furthermore, I just tested it and I can delete some of the flows.

Here's what I reckon. Deleting flows that contain subflows is a more complex process. For example, we block the deletion of "decision tree", if there is a flow that has "decision tree" as a subflow (e.g., Bagging decision trees). 

So suppose you run with a script over all your flows to delete, some will be deleted, whereas sometimes you will get error 324: 'flow is in use by other content. Can not be deleted'. The thing I just cannot explain is why you get a "flow does not exists" error. 

I only get these when the flows really don't exists (and thus are already deleted).

**Comment by mfeurer** [comment]
Indeed, I was able to delete most of the runs. I can also see the error 324 and it goes away if I run the deletion script multiple times. 

Nevertheless, there are still runs and flows which are shown in the web interface, but which I cannot delete. Have a look at http://capa.win.tue.nl/search?q=uploader_id%3A86&type=run&listids=1&size=2:

This flow is obviously there, but calling http://test.openml.org/api/v1/xml/run/572202?api_key=XXX gives me a response code of 450 and the following error message:

```
<oml:error xmlns:oml="http://openml.org/openml">
	<oml:code>392</oml:code>
	<oml:message>Run does not exists</oml:message>
<oml:error>
```

The same is true for the flows that are associated with me: http://capa.win.tue.nl/search?q=uploader_id%3A86&type=flow&listids=1&size=64

**Comment by joaquinvanschoren** [comment]
Yes, the web interface on the test server is not accurate. Fixing that now.

**Comment by mfeurer** [comment]
Seems to be fixed. Thanks.
