### ISSUE TITLE
Flow using same component multiple times

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#286]
I'm wondering if it is possible to reference the same component multiple times in a flow. In the example that I have I want to make the distributions used in random search a flow. Let's now assume that the target algorithm has two hyperparameters, and I want to sample them from the same distribution. The xml for the flow permits this, but I don't know how to upload a run referencing the same flow twice. It looks like I cannot state the identifier in the original flow when uploading the run.

In case this doesn't work at the moment, would it be possible to add this features?

**Comment by mfeurer** [comment]
Okay, here is a potential solution: By adding another field to the parameters in the run xml which references the component identifier, one could overcome the problem if all components with identical IDs are on the same level of the component tree. This flag wouldn't need to be required since it's very often not necessary. When having a more complicated component tree this won't help any more though.

**Comment by joaquinvanschoren** [comment]
Hi Matthias,

I'm not sure whether I follow you exactly, but it is definitely possible to
state the flow component id in the parameter description of a run:
  <oml:parameter_setting>
    <oml:name>E</oml:name>
    <oml:value>20</oml:value>
    <oml:component>1820</oml:component>
  </oml:parameter_setting>

I think that the WEKA plugin does this by default:
http://openml.org/data/download/1971108/weka_generated_run8040696062307353861.xml

Does that answer your question?

**Comment by mfeurer** [comment]
I'll have a look whether I can solve this with your input. Thanks a lot.

**Comment by joaquinvanschoren** [comment]
Is this still an issue?

**Comment by mfeurer** [comment]
No, I'm doing this differently now.
