### ISSUE TITLE
Raise Server error if string value is longer than database entry

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#287]
The server should respond with an error if a string for an entry, e.g. the default value of a parameter in a flow, is longer than the string field of the database. This happened in #285.

**Comment by joaquinvanschoren** [comment]
Easiest is to put this into the XSD descriptions, using xs:maxLength
You would then get an error that the entry specification is incorrect. Would that be OK?

**Comment by mfeurer** [comment]
That would help. I want this just to safeguard the user to avoid her thinking everything is alright while the server actually truncates parts of the xml file.

**Comment by mfeurer** [comment]
@janvanrijn is this solved and can be closed?

**Comment by janvanrijn** [comment]
I think this has been done for all xsd schema's now. Please reopen if you don't agree:
https://github.com/openml/OpenML/tree/master/openml_OS/views/pages/api_new/v1/xsd
