### ISSUE TITLE
Duplicates of Metadata

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#288]
OpenML automatically calculates metadata. However, adding the faintail library caused that some metadata are computed multiple times which is a) reduntant, b) confusing as one has to filter duplicate metadata not to give more weight to that particular metadata

Duplicates I found:
 NumberOfMissingValues = NumMissingValues
ClassCount = NumberOfClasses
 NumberOfInstances = InstanceCount
 NumberOfFeatures= NumAttributes
NumberOfNumericFeatures = NumNumericAtts,
 NumberOfSymbolicFeatures = NumNominalAtts 
NumberOfInstancesWithMissingValues = IncompleteInstanceCount metafeature.

**Comment by joaquinvanschoren** [comment]
Thanks. Fixed :)
