### ISSUE TITLE
Concepts of Experiments, Studies and Investigations

### ISSUE THREAD

**Issue by janvanrijn** [openml/OpenML#289]
Currently, OpenML contains the concept of studies, which is a combination of data sets, tasks, flows and runs in a paper. Currently, OpenML contains the concept of studies, which is a combination of data sets, tasks, flows and runs. This can be referred to from papers.

However, as I recently experienced, typically, a paper consists of multiple experiments. It would be nice to reflect this also in OpenML. For example in line with the  ISA standard, in which there are Experiments, Studies and Investigations. Experiments is a combination of tagged data sets, tasks, flows and runs, studies (or papers) then a combination of experiments and investigations are one level higher in the hierarchy. 
Although at first sight this might not be a priority, it seems convenient to have the issue out here, so we can pick it up whenever there is time. At a first stage, we could implement the concept of 'experiments', and if necessary later also 'Investigations'.

**Comment by berndbischl** [comment]
1) first of all, whatever we do here, we should design this with a larger group of people (the steering group) to get this right.

2) can you please post a more concrete example / description what your are missing and what you ideally would like to have?

**Comment by janvanrijn** [comment]
Doesn't seem that we will pursue this on short term with the new study model
docs.openml.org/benchmark
