### ISSUE TITLE
Upload simple runs taking some minutes

### ISSUE THREAD

**Issue by rgmantovani** [openml/OpenML#291]
Hi
I'm running an small example with the R package, but the upload operations are spending some minutes to finish and return the 'run.id'. We checked the R package and it's ok. The same occurs using the api call directly (http://www.openml.org/api_docs/#!/run/post_run).

My Files (description and predictions are attached here):
[Files.zip](https://github.com/openml/OpenML/files/289837/Files.zip)

Thanks.

**Comment by joaquinvanschoren** [comment]
This is fixed now.
