### ISSUE TITLE
Website regarding data sets offline 

### ISSUE THREAD

**Issue by philippstats** [openml/OpenML#292]
I cannot find some websites regarding data sets I used.

Via `R` the data is still downloadable:
```
library(OpenML)
d = getOMLDataSet(did = 251)
```
This are the links which doesn't work anymore:
- http://www.openml.org/d/251
- http://www.openml.org/d/901
- http://www.openml.org/d/727

Is this shutting down on purpose? Or did the description moved somewhere else?

Thanks in advance!

**Comment by joaquinvanschoren** [comment]
We're reindexing everything on the website. It should reappear soon. Sorry
for the inconvenience.

**Comment by philippstats** [comment]
Ok, thanks!

**Comment by joaquinvanschoren** [comment]
Hi, I found an edge case that caused some datasets not to be indexed, but
this should be fixed now. Please check and close if your issue is solved.

**Comment by joaquinvanschoren** [comment]
I assume that this can be closed?
