### ISSUE TITLE
When resetting password, the form that requests your email defaults to "undefined"

### ISSUE THREAD

**Issue by rhiever** [openml/OpenML#293]
For this page: http://www.openml.org/password_forgot

See the image below. This is on Chrome. It should probably default to something else.

<img width="472" alt="screen shot 2016-06-23 at 5 42 02 pm" src="https://cloud.githubusercontent.com/assets/1719223/16321246/df662a0a-3969-11e6-9363-5f3cb75720dc.png">

**Comment by joaquinvanschoren** [comment]
This should be undefined, as a check that the person who wants to reset actually knows the email address.

But styling could indeed be better. Also the email that is sent can be improved.
