### ISSUE TITLE
"Edit Profile" not working

### ISSUE THREAD

**Issue by TGlas** [openml/OpenML#303]
On the account page http://capa.win.tue.nl/u/[user-id], when being logged in, there is a (new?) button "EDIT PROFILE". It seems to replace the old "account settings". Pressing the button sends me to http://www.openml.org/#edit, which does not work. Indeed, there is no anchor tag called "edit" in the page source.

**Comment by joaquinvanschoren** [comment]
Was fixed during the hackathon
