### ISSUE TITLE
add date info to run list and run evaluation list

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#315]

**Comment by joaquinvanschoren** [comment]
Added this while mlr was compiling :)

**Comment by joaquinvanschoren** [comment]
<oml:runs xmlns:oml="http://openml.org/openml">
<oml:run>
<oml:run_id>90127</oml:run_id>
<oml:task_id>3563</oml:task_id>
<oml:setup_id>1504</oml:setup_id>
<oml:flow_id>1</oml:flow_id>
<oml:uploader>17</oml:uploader>
<oml:upload_time>2014-12-08 11:33:11</oml:upload_time>
<oml:error_message/>
</oml:run>
<oml:run>
<oml:run_id>614</oml:run_id>
<oml:task_id>1</oml:task_id>
<oml:setup_id>1</oml:setup_id>
<oml:flow_id>56</oml:flow_id>
<oml:uploader>16</oml:uploader>
<oml:upload_time>2014-04-07 12:26:32</oml:upload_time>
<oml:error_message/>
</oml:run>
</oml:runs>

**Comment by giuseppec** [comment]
You added this to the main server, but not to the test server right? So tests on the test server are passing, but the main package is failing.

**Comment by giuseppec** [comment]
And: that is also not a valid json file, cause of an additional comma after `"upload_time": "",`, see e.g. 
http://www.openml.org/api/v1/json/evaluation/list/task/3/limit/1

```
{
	"evaluations": {
		"evaluation": [{
			"run_id": 28,
			"task_id": 3,
			"setup_id": 18,
			"flow_id": 77,
			"flow_name": "weka.LogitBoost_DecisionStump(1)",
			"data_name": "kr-vs-kp",
			"function": "area_under_roc_curve",
			"upload_time": "",
			,
			"value": 0.977253,
			"array_data": [0.977253, 0.977253]
		}]
	}
}
```

**Comment by giuseppec** [comment]
And: It seems that `"upload_time"` is always an empty string?

**Comment by joaquinvanschoren** [comment]
Sorry, was too rushed. 
Fixed a bug in the evaluations list, updated docs, and pulled on the test server now.
