### ISSUE TITLE
Main server completely down?

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#322]
hi, this is not so good

www.openml.org

seems dead?

**Comment by joaquinvanschoren** [comment]
Just saw it too. Don't know what happened, rebooting now.

**Comment by joaquinvanschoren** [comment]
Back online.

**Comment by giuseppec** [comment]
Back offline.

**Comment by joaquinvanschoren** [comment]
up again

**Comment by gwilson-xaxis** [comment]
back offline

**Comment by joaquinvanschoren** [comment]
Sorry, online again.

**Comment by giuseppec** [comment]
back offline again. This seems to happen very often in the last weeks, any ideas why and how we can reduce the downtimes?

**Comment by joaquinvanschoren** [comment]
Up again. The server is fine but Apache crashes. May be a disk issue. We
are installing the new server right now so that we have redundancy and can
take a closer look at the current server.

**Comment by giuseppec** [comment]
Completely down since yesterday
