### ISSUE TITLE
API for making Tasks

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#325]
I see this https://github.com/openml/website/blob/master/openml_OS/views/pages/api_new/v1/xsd/openml.task.upload.xsd but I don't understand the following things:
- how can I set the id of the data set that should be used for the task?
- how can I set the estimation procedure and the evaluation measure? 
- And how are the splits generated? Do I have to upload the splits via an arff? If yes, the API does not seem to allow the uploading of an additional arff, see http://www.openml.org/api_docs/#!/task/post_task 

As far as I can see, the current xsd scheme allows only setting the `task_type_id` and the `feature`?

**Comment by janvanrijn** [comment]
Task_id should not be set (i have updated the xsd accordingly, will be on
server later)

Using the input fields, various properties of the tasks can be set.

E.g. input 'source_data' can be used to set a dataset id,
estimation_procedure can be used to select an estimation procedure (id) and
evaluation_measure can be used to select an evaluation measure.
This might be a hard function to implement, as tasks are quite a
complicated aspect of openml.

2016-09-15 16:09 GMT+02:00 giuseppec <notifications@github.com>:

**Comment by joaquinvanschoren** [comment]
We have an API call for creating tasks:
https://www.openml.org/api_docs#!/task/post_task

Example:
https://www.openml.org/api/v1/xml_example/task

Note:
* Don't upload a task_id, it will be returned once the task is created
* For looking up the estimation procedure id we have an API:
https://www.openml.org/api_docs#!/estimationprocedure/get_estimationprocedure_list
* The splits will be created automatically based on the estimation procedure

Is there anything else not clear, or can we close the issue?

**Comment by janvanrijn** [comment]
I am officially still working on this function, please keep it open for a while. 

In fact, it's one of my highest priorities before the workshop to have this more robust.

**Comment by joaquinvanschoren** [comment]
This is done a long time ago :)
