### ISSUE TITLE
Feature request: flow listing should contain tags

### ISSUE THREAD

**Issue by jakobbossek** [openml/OpenML#327]
Why is there not `tags` field in the request?
IMHO there should always be the tags field. Even if there are no tags assigned.

E.g. http://test.openml.org/api/v1/json/flow/list/tag/Cortana
```json
{"flows":{"flow":[
    {"id":4818,
   "full_name":"SubgroupDiscovery(1)",
   "name":"SubgroupDiscovery",
   "version":1,
   "external_version":"3073",
   "uploader":1	   }
    ]}
}
```

**Comment by joaquinvanschoren** [comment]
We do have tags in flow listings:

**Comment by jakobbossek** [comment]
Why are there no tags in the upper request?

**Comment by joaquinvanschoren** [comment]
In all listings, we only show the tags if there are any. We could show an empty array otherwise. Would that really help?

**Comment by jakobbossek** [comment]
In the above example I request all flows with the "Cortana" tag. Hence, there should be at least the "Cortana" tag assigned, right?

**Comment by joaquinvanschoren** [comment]
Yes... this is a bug

**Comment by jakobbossek** [comment]
😉

**Comment by joaquinvanschoren** [comment]
Fixed. Thanks for reporting it.
