### ISSUE TITLE
Proposal: enable developers to assign labels to all OpenML* repos

### ISSUE THREAD

**Issue by jakobbossek** [openml/OpenML#328]

**Comment by joaquinvanschoren** [comment]
You'll have to explain me how that works ;)

**Comment by jakobbossek** [comment]
No idea 😆 
I guess you need to add us as admins by hand? 😰

**Comment by jakobbossek** [comment]
https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by joaquinvanschoren** [comment]
It says there that if you can write, you can add labels and milestones?
Added you to admins. Can you show an example of what labels do?

**Comment by jakobbossek** [comment]
Well, I can open issues and classify myself, i.e., assign priorities, feature requests, enhancements and stuff like that directly. This way you do not need to do this by hand and you have a better understanding of what is going on in you issue tracker.
