### ISSUE TITLE
All queries to the test server give "no response from server"

### ISSUE THREAD

**Issue by TGlas** [openml/OpenML#334]
I am trying to query the test server for information, i.e.:

`http://capa.win.tue.nl/api_docs/#!/data/get_data_id`

No matter what I try (datasets, tasks, ...), no matter what type of query, I always receive an empty reply:

```
Request URL: http://www.openml.org/api/v1/json/data/11?api_key=[........]
Response Body: no content
Response Code: 0
Response Headers: { "error": "no response from server" }
```

Interestingly, the request URL redirects to the production server, where of course the API key can be different. This looks like a bug, but it does not yet explain everything. I manage two accounts, one with identical API key for both servers, one with different keys. The test server works in neither case, the production server does work. So it is not only the difference in API key. Maybe there is a configuration issue on the test server...?

**Comment by joaquinvanschoren** [comment]
Fixed now.
Sorry for the slow response.

**Comment by TGlas** [comment]
I'd like to open this again. When testing the REST API in the browser, e.g. here:

[https://test.openml.org/api_docs/#!/data/get_data_id](https://test.openml.org/api_docs/#!/data/get_data_id)

I get nothing but an empty reply. I.e., the fields Request URL, Response Body, Response Code, Response Headers all being empty. This works on the real system, so sounds like a bug to me.
