### ISSUE TITLE
missing evaluation measures in task/list

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#335]
When I use the `task/list`, and look at the values for `evaluation.measures`, I see the values "cluster-anil" and "type" (the latter value occurs for task id 71316 and should be a bug). However, the `evaluationmeasure/list` API that should list all possible evaluation measures does not show "cluster-anil".
And another question: I forgot why we have tasks without an evaluation measure, what was the reason for this? And what is the difference to tasks that have an evaluation measure?

**Comment by joaquinvanschoren** [comment]
I removed all unusual clustering tasks. We will check the clustering task creation code whether this can still happen.

To answer your question:
The evaluation measure *pre-specifies* a specific evaluation measure to optimize for. This is important if only a specific evaluation measure makes sense given the data, or when optimizing hyperparameter settings. When there is no single best evaluation measure, a task can be created without it, and the best models are selected afterward by sorting them by any evaluation measure computed by the server. Hence, anyone can interpret the results according to their goals.
