### ISSUE TITLE
data/list and task/list have missing values for the number of instances?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#337]
For the following data sets it seems that the data/list and task/list API do not show data qualities such as number of instances:

```
     data.id                            name
1067    1245              lungcancer_shedden
2382    4133              kdd_internet_usage
2389    4329                thoracic_surgery
2396    4536        SensorlessDriveDiagnosis
2399    4539 MiniBooNEparticleidentification
2413    4670       sequence_data_with_gender
2531   23515                          sulfur
```

This is what the server returns:

```
{"did":1245,
   "name":"lungcancer_shedden",
   "version":1,
   "status":"active",
   "format":"ARFF",
   "quality":[
        ]
      }
```

**Comment by joaquinvanschoren** [comment]
In fact there were no qualities computed at all. For a few cases, there was a problem with the default target features, which is now fixed. The others are simply too large to fit in memory. I have reverted them to 'in_preparation' status until we can address this.

**Comment by joaquinvanschoren** [comment]
We also show warnings now when a dataset has an issue that prevents it from being activated:
http://www.openml.org/d/4536
