### ISSUE TITLE
Clustering tasks: invalid ARFF "Task not providing datasplits."

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#338]
Some clustering tasks have an evaluation measure "testontrainingdata" e.g. task 5521 has the field:

```
<oml:input name="estimation_procedure">
<oml:estimation_procedure>
<oml:type>testontrainingdata</oml:type>
<oml:data_splits_url>http://www.openml.org/api_splits/get/5521/Task_5521_splits.arff</oml:data_splits_url>
<oml:parameter name="number_repeats">50</oml:parameter>
<oml:parameter name="stratified_sampling"></oml:parameter>
</oml:estimation_procedure> 
</oml:input>
```

However, the provided data splits ARFF http://www.openml.org/api_splits/get/5521/Task_5521_splits.arff is not a valid ARFF format because it has the content

```
Task not providing datasplits.
```

**Comment by joaquinvanschoren** [comment]
I agree that this is incongruous. There simply should not be a data splits file for these types of tasks.
We'll need to revisit how we do clustering tasks properly. I've removed all clustering tasks until we have done this.
