### ISSUE TITLE
Description (and prediction) file for runs are not available on test server

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#346]
I get a "not found" when I try to download the ARFF or description file by clicking on the "Predictions" or "Description" button, respectively. See, e.g. http://test.openml.org/r/2, where the url for the ARFF file links to 
http://capa.win.tue.nl/data/download/66/weka_generated_predictions3181957963973800253.arff 
maybe just the url is wrong?

This error also occurs when I try to download a specific run through the API.

**Comment by janvanrijn** [comment]
This  happens because the database was once copied from live, but the files are not (So, if you submit a run specifically to test.openml.org, the links are correct.) This should* not happen on the live site.

**Comment by giuseppec** [comment]
I know that this works on the live site. However, the problem is that our unit tests fail because downloading runs from the test server does not work (e.g. the arff file and description xml does not exist on the server). Do we have to live this? If yes, I have to disable all tests that download runs or operate on downloaded runs, which is bad right?

**Comment by giuseppec** [comment]
I see that newer runs are availalbe. I can solve this using different runs (e.g. runs with id > 542000), right?

**Comment by janvanrijn** [comment]
Genau. That's actually also how the Java Unit tests deal with it.

**Comment by giuseppec** [comment]
Cool thx, I just did't see that it works for newer runs, will rewrite the tests.
