### ISSUE TITLE
evaluation/list bug?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#347]
The resulting `run.id`s from 
http://test.openml.org/api/v1/json/evaluation/list/task/3/tag/study_1 
should be a subset of the `run.id`'s that occur in 
http://test.openml.org/api/v1/json/evaluation/list/task/3 
right? But it's not. The intersection of the `run.id`s from both API calls is an empty set. Same happens on the main server.

**Comment by janvanrijn** [comment]
Can you please elaborate on that? (e.g., can you give me a list of run ids
which are missing in the second call?)

I tried to reproduce this issue quickly by hand, but to me it seems that
the
run ids of the first api call are indeed a subset of the run ids from the
second
api call.

2016-11-10 10:49 GMT+01:00 giuseppec <notifications@github.com>:

**Comment by giuseppec** [comment]
Hm, so [this](https://drive.google.com/file/d/0B7Xb1_ywA2noVWwyZzN1WmlhY1U/view?usp=sharing) is the resulting JSON file from 
http://test.openml.org/api/v1/json/evaluation/list/task/3/tag/study_1
and [this](https://drive.google.com/file/d/0B7Xb1_ywA2noQW9OS0F0MHNxZjg/view?usp=sharing) is the resulting JSON file from 
http://test.openml.org/api/v1/json/evaluation/list/task/3
All `run.id`s from the first call are missing in the second call (and vice versa).

**Comment by giuseppec** [comment]
Just forget it. This was my fault.
