### ISSUE TITLE
FilteredClassifier flows not properly supported

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#350]
User report: 

Whenever I try to use it with the OpenML plugin through the classifier 'weka.classifiers.meta.FilteredClassifier' so that my results get uploaded, I get a "Exception in thread "Thread-X" java.lang.NoClassDefFoundError: weka/core/setupgenerator/AbstractParameter"

OpenML seems to expect that the multisearch package is installed.

**Comment by joaquinvanschoren** [comment]
Can we remove this dependency? Multisearch shouldn't be necessary here?

**Comment by janvanrijn** [comment]
Done. New Weka release in website development branch. Will release next week.
