### ISSUE TITLE
Malfunctioning links in the menu of my account

### ISSUE THREAD

**Issue by Addono** [openml/OpenML#351]
When on one of the pages of my account:
1. Data sets http://www.openml.org/u/1947/data
2. Flows http://www.openml.org/u/1947/flows
3. Runs http://www.openml.org/u/1947/runs

it is not possible to go to the Api-key page or the Profile and Password page

**Comment by joaquinvanschoren** [comment]
Hi, Are you logged in? Then there should be an 'account settings' menu in the sidebar.

**Comment by Addono** [comment]
Yes, it does work, but only from the Overview page.

This is accessible:
http://www.openml.org/u/1947#!api

But this isn't (which is the link in the menu when I come from the Data Sets page):
http://www.openml.org/u/1947/data#!api

(And in case this is any relevant, I am running Chrome 54 x64 on Win8.1)

**Comment by joaquinvanschoren** [comment]
Yes, you're right. Thanks, we'll fix it soon.

**Comment by joaquinvanschoren** [comment]
This is now fixed. Thanks!
