### ISSUE TITLE
No evaluation measures for runs uploaded today

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/OpenML#358]
See e.g. 
https://www.openml.org/r/1847232
and
https://www.openml.org/api/v1/json/evaluation/list/run/1847233
gives
`{"error":{"code":"542","message":"No results"}}`

**Comment by joaquinvanschoren** [comment]
Sorry, fixed.

**Comment by HeidiSeibold** [comment]
Same problem occurs for one run I just uploaded. 
https://www.openml.org/r/1847400

The other runs (1847388-1847411) are fine.
