### ISSUE TITLE
Wrong quality order and descriptions on the main site

### ISSUE THREAD

**Issue by WilliamRaynaut** [openml/OpenML#391]
The qualities displayed on any dataset's page are in the wrong order (should have few obvious ones at the top, when on https://www.openml.org/d/357 for instance we have "HoeffdingAdwin.changes"...).
Also, some description seem not to have updated from "DataQuality extracted from Fantail Library". They do have the correct description on the test db though, but I can't check the main db... Can I get an access for debuging purposes ?

**Comment by joaquinvanschoren** [comment]
Ordering is fixed.
Is there still an issue with the descriptions?

**Comment by amueller** [comment]
closing as no reply. Please reopen if there's still an issue.
