### ISSUE TITLE
Evaluation Engine on main server is stuck since 2 days?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#400]
E.g. the run https://www.openml.org/r/1853500 does not have evaluations. This seems to be the case for runs since middle of last week. Evaluation Engine possibly crashed? 
Do you have an automatic notification mechanism that notifies you when this is happening? Or do we still have to write issues when we see that this happens?

**Comment by janvanrijn** [comment]
Since db update we are recalculating all runs. You don't see it on the
frontpage (as the results are still in elastic search cache), but on
backend everything is being recalculated.

If i go into office today (big if) i will make sure that recent runs get
evaluated with priority.

**Comment by giuseppec** [comment]
Assigning higher priority to recent runs would be great. You can close this issue when this is done. THX.

**Comment by janvanrijn** [comment]
... And running.

Let's close this when eval engine is done calculating all evals again. Maybe there are some other people that need some calculations done with priority.

**Comment by giuseppec** [comment]
Could you please manually let the eval engine run the runs from https://www.openml.org/s/30 ? Currently, evaluation/list does not show the results of these runs and I really need them.

**Comment by janvanrijn** [comment]
Got some nodes running. Depending on the number of runs, it should go fast.

**Comment by janvanrijn** [comment]
Apparently, it's already done. Could you check?
