### ISSUE TITLE
Python interface: How is the cache used? When is it cleared?

### ISSUE THREAD

**Issue by rhiever** [openml/OpenML#404]
I've been using the OpenML Python interface for the past week to run a bunch of benchmark locally on my machine. I assumed that the datasets in the cache were being reused every time I pulled the same dataset for the same task, but now I'm not so sure. My cache has over 40,000 directories in the `datasets` directory , each with a dataset in the entries, totaling over 1GB of cache.

For the most part, I've only been running algorithms on the datasets under the `study_14` tag, which contains a fixed set of 100 datasets. So now I wonder:

1) Is the Python OpenML interface really using the cache?

2) When does the cache get cleared? Do I have to clear it myself, and if so, how?

**Comment by mfeurer** [comment]
Answering your questions:

1. Yes, it is. You can download a dataset, cut off your internet connection and you'll still be able to load it.
2. The cache does not get cleared. It saves everything you ever download.

and some more intuition on what is cached:

For each dataset, the API connector downloads an arff file. As parsing arff files is slow, they corresponding numpy array is pickled. Having one GB of cached data for 100 datasets implies that each dataset takes about 10 MB, which is realistic. 

Why there are a total of 40.000 directories in the cache directory is not clear to me. Could you please check the directory names whether they are only numbers, and what the minimum and maximum number are?

**Comment by rhiever** [comment]
Thank you for the clarification, @mfeurer! It looks like there's actually "only" 118 directories, which seems about right. The numbers seem to correspond to dataset number. My mistake!
