### ISSUE TITLE
API: Get count of runs by tag

### ISSUE THREAD

**Issue by DanielKuehn87** [openml/OpenML#405]
I have >10.000 runs with the mlrRandomBot tag:
https://www.openml.org/api/v1/json/run/list/tag/mlrRandomBot

It would be nice to have some way to get the total number of results (and not from the error message). 
The return value of something like this query would do:
SELECT count(*)
FROM run.table
WHERE run.tag = "my_tag"

**Comment by joaquinvanschoren** [comment]
Thanks for posting. I'm closing this one in favor of a more general solution, see #1032
