### ISSUE TITLE
listOMLTasks for given task.ids

### ISSUE THREAD

**Issue by PhilippPro** [openml/OpenML#406]
[https://github.com/openml/openml-r/issues/316#issuecomment-291067681](https://github.com/openml/openml-r/issues/316#issuecomment-291067681)

**Comment by HeidiSeibold** [comment]
To make it easier for you, I repost the original issue:

Imagine I want to extract the results of all mlr forest runs on OpenML

```
library("OpenML")

## get info on all forest flows in mlr 
all_flows_info <- listOMLFlows()
is_flow_forest <- grepl("Forest|forest", all_flows_info$full.name)
is_flow_mlr_forest <- is_flow_forest & grepl("mlr", all_flows_info$full.name)
forest_flows_info <- all_flows_info[is_flow_mlr_forest, ]

## get run evaluations for all runs of these flows
forest_flows_eval <- listOMLRunEvaluations(flow.id = forest_flows_info$flow.id)
```

Now I want to add information of tasks to this (e.g. to separate between regression and classification tasks). My prefered option would be something like:
```
## get task infos for the runs
all_tasks_info <- listOMLTasks(task.id = forest_flows_eval$task.id)
```
But listOMLTasks does not allow me to enter the task.id.

**Comment by giuseppec** [comment]
list/setup by setup.id and list/runs by run.id is already possible. It would make also sense to 
- list/task by task.id and
- list/data by data.id

**Comment by giuseppec** [comment]
I reopened a clean issue here https://github.com/openml/OpenML/issues/523
