### ISSUE TITLE
Website slow and often crashing

### ISSUE THREAD

**Issue by janvanrijn** [openml/OpenML#407]
Something I encountered today. We should investigate. Were there recent changes to the server, e.g., some new software running?

**Comment by joaquinvanschoren** [comment]
Only recent change is an update to the wiki engine. However, That is loaded dynamically and should not slow down the website? Any hardware issues?

**Comment by janvanrijn** [comment]
I don't know, it seems better now. maybe it were network problems. Let's monitor this for a while

**Comment by DanielKuehn87** [comment]
I currently can't log into my account and also can't view any data-sets (I see the message: "We could not find anything in the database"). Tried with Firefox, Chrome and Edge.

**Comment by janvanrijn** [comment]
I reboot the server, should be fixed in 5

2017-05-02 22:47 GMT+02:00 DanielKuehn87 <notifications@github.com>:

**Comment by joaquinvanschoren** [comment]
Do we need to keep this open? I haven't experienced any crashed, only some slow loading times when lots or data needs to be imported.
