### ISSUE TITLE
API: Get description result xml file

### ISSUE THREAD

**Issue by DanielKuehn87** [openml/OpenML#409]
Is there any way to retrieve this description result file?
E. g. https://www.openml.org/data/download/5119925/description62bb27c9a806.xml for run https://www.openml.org/r/2083475

**Comment by joaquinvanschoren** [comment]
Sure, this is in the run description:
https://www.openml.org/api/v1/run/2083475
Then extract output_data > description > url

**Comment by DanielKuehn87** [comment]
Ok, so currently I need to call the API -> download the XML -> parse the XML for each run, right? So if I need usercpu_time_millis or scimark_benchmark values for many runs, I face the same problem as with https://github.com/openml/OpenML/issues/411. 
Would it be possible to also get these output_data-values via a listing call?

**Comment by joaquinvanschoren** [comment]
No, all evaluations (also user-provided ones) should be returned by the evaluations API, which has plenty of listing calls, i.e.
https://www.openml.org/api/v1/evaluation/list/run/2083475

I do notice now that user_cpu_time_millis etc. is not returned. It should. We'll look into it.

**Comment by janvanrijn** [comment]
user_cpu_time_millis and scimark_benchmark are measures that are calculated
on the users pc and therefore can vary per workbench. As this is an MLR
run, I don think that scimark_benchmark is measured (java specific)

2017-05-02 23:23 GMT+02:00 Joaquin Vanschoren <notifications@github.com>:

**Comment by DanielKuehn87** [comment]
We run a separate scimark_benchmark and upload it together with the MLR run. So for all Bot-runs these values should be available.

**Comment by joaquinvanschoren** [comment]
@janvanrijn MLR has wrapped scimark to calculate the benchmarks.
Still, user-specific measures like user_cpu_time_millis should be stored in our database, right? They are not for this run.

**Comment by giuseppec** [comment]
Wait, the user-specific measures can be found under "Result files" in the "Description" file https://www.openml.org/data/download/5119925/description62bb27c9a806.xml ? 
This is the XML that the R package is uploading to OpenML. It is strange that the hyperparameter values are extracted from the website but it seems that the time measurements and the scimark measurements are simply ignored, right? Once this used to work (see https://www.openml.org/r/573013).

**Comment by joaquinvanschoren** [comment]
Yes, this used to work. A bug sneaked in along the way and we need to fix that now. See #412.
Btw, nothing is extracted from the website, it is extracted from the run description files (XML).

**Comment by giuseppec** [comment]
seems to be possible now with 

```
res = listOMLRunEvaluations(tag = "botV1", limit = 100, evaluation.measure = "usercpu_time_millis")
```
