### ISSUE TITLE
Check storage of user-defined measures

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#412]
As noted in #409, user-uploaded evaluation measures are not returned by the API.
It seems that for all runs since 595627, this is not being stored in the database.

Probably a bug. Needs to be fixed, and runs re-evaluated.

**Comment by janvanrijn** [comment]
Yes, it is a bug. Based on a legacy naming convention in the XML. 

As a consequence, currently user defined measures are not properly stored in the database and user uploaded 'check variables' are not used (i.e., there will probably be no api warnings in the database too).

The information is still in the xml's and can be retrieved though. need some time to fix this properly.

**Comment by joaquinvanschoren** [comment]
This is fixed but some rerunning is needed, see #425

**Comment by PhilippPro** [comment]
Would be nice if this could be fixed, as this is blocking me a bit. ;)

**Comment by PhilippPro** [comment]
Ping ;)

**Comment by joaquinvanschoren** [comment]
All runs should be re-evaluated by now.
@PhilippPro can you check and close?

**Comment by PhilippPro** [comment]
This code still give different results without and with runtime...
```
listOMLRunEvaluations(run.id = 2253351)
listOMLRunEvaluations(run.id = 2306596)
```

**Comment by joaquinvanschoren** [comment]
You're right, we missed a few. Processing now...

**Comment by PhilippPro** [comment]
Thanks, solved, can be closed.
