### ISSUE TITLE
function filter for evaluation list

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#414]
In https://github.com/openml/openml-r/issues/275 it was mentioned that this should work but doesn't: https://www.openml.org/api/v1/xml/evaluation/list/tag/mlrRandomBot/function/area_under_roc_curve

Is there any progress?

**Comment by joaquinvanschoren** [comment]
This is fixed. Waiting for Jan to review the PR.

**Comment by joaquinvanschoren** [comment]
Closing, as this is a duplicate of #423
