### ISSUE TITLE
Python API quickstart page outdated

### ISSUE THREAD

**Issue by rkadlec** [openml/OpenML#419]
I tried to run a code snippet from 
https://www.openml.org/guide#!python
with the latest openml-python API and it fails while executing line "run = runs.run_task(task, clf)".

 "run_task" method was probably refactored to "run_model_on_task", after this change the code works.

**Comment by mfeurer** [comment]
This was indeed not updated to the development branch, but should still work in the master branch. For the development branch your observation is correct and `run_model_on_task` is what you're looking for.

**Comment by mfeurer** [comment]
This quickstart guide does no longer exist. Python docs can be found at docs.openml.org.
