### ISSUE TITLE
function filter in evaluation/list

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#423]
In https://github.com/openml/openml-r/issues/275#issuecomment-290105948 @joaquinvanschoren sad "I notice the 'function' filter is not documented, and in fact it does not work correctly. This should work but doesn't: https://www.openml.org/api/v1/xml/evaluation/list/tag/mlrRandomBot/function/area_under_roc_curve"

Is there any update?

**Comment by joaquinvanschoren** [comment]
I submitted a PR with a fix. As soon as Jan reviews it I'll update the server.

**Comment by joaquinvanschoren** [comment]
Running on production now:
https://www.openml.org/api/v1/evaluation/list/function/area_under_roc_curve/limit/100
