### ISSUE TITLE
Bug in evaluation list fn

### ISSUE THREAD

**Issue by janvanrijn** [openml/OpenML#428]
This function is not correct. 

I get a "too many results" issue, even on very small result sets (obviously smaller than the limit)

I understand that the query needs to be fast and some concessions needs to be made, but we should at all times make sure that the results are reliable. 

edit: was already broken for a while it seems.

**Comment by janvanrijn** [comment]
different bug, it does not check for legal tags. will push a fix this afternoon

**Comment by janvanrijn** [comment]
Should be fixed. I will add a unit test later

**Comment by joaquinvanschoren** [comment]
I didn't actually change anything about the amount of results, right? I only forced the use of some indices and removed an unnecessary join?

**Comment by janvanrijn** [comment]
I know, it was a historic bug, mea culpa. now fixed

2017-06-19 15:36 GMT+02:00 Joaquin Vanschoren <notifications@github.com>:
