### ISSUE TITLE
Data with string features not parsed?

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#439]
Somewhat related to https://github.com/openml/website/issues/164#issue-245829944.

I wanted to find out which datasets had string features, so I got the datasets and wanted to check for which datasets ``"NumberOfFeatures"`` is not the sum of ``"NumberOfNumericalFeatures"`` and ``"NumberOfSymbolicFeatures"``. Turns out, it always is. Except for some cases where the dataset was not parsed, and all three keys are missing:

```python
import openml
asdf = openml.datasets.list_datasets()
for k, v in asdf.items():
    #print(k)
    try:
        if v['NumberOfFeatures'] != v['NumberOfNumericFeatures'] + v['NumberOfSymbolicFeatures']:
            print(k)
            print(v)
    except KeyError as e:
        print("Not parsed: ", k)
```
```
Not parsed:  23389
Not parsed:  23417
Not parsed:  23418
Not parsed:  23419
Not parsed:  23425
Not parsed:  23428
Not parsed:  23466
Not parsed:  23485
Not parsed:  23490
Not parsed:  23500
Not parsed:  23502
Not parsed:  23503
Not parsed:  23504
Not parsed:  23505
Not parsed:  23506
Not parsed:  23507
Not parsed:  23510
Not parsed:  23511
Not parsed:  40588
Not parsed:  40589
Not parsed:  40590
Not parsed:  40591
Not parsed:  40592
Not parsed:  40593
Not parsed:  40594
Not parsed:  40595
Not parsed:  40597
Not parsed:  40601
```

Going through a bunch of these, even though [they were uploaded a year ago](https://www.openml.org/d/23417) they say they are not parsed and I should refresh the page. The one thing they have in common, looking at the ARFF files, is that they all seems to have string features.

So, was that just never implemented, and the server errors on string features and just never parses them?
This seems strange, in particular because the datasets were added to the database, but never parsed. I wonder why this didn't result in errors elsewhere.

**Comment by amueller** [comment]
Maybe I was too quick: enron is not parsed and has no string features: https://www.openml.org/d/40590 But string features is pretty certainly one of the issues.

**Comment by amueller** [comment]
The last one seems broken altogether? https://www.openml.org/d/40601

**Comment by amueller** [comment]
I think something changed. Two days ago it said "not parsed yet", now it says "0 features 0 properties".

**Comment by joaquinvanschoren** [comment]
The parser breaks on some of these:
```
jvanscho@openml:~$ java -jar /var/www/openml.org/public_html/openml_OS/third_party/OpenML/Java/evaluate.jar -config "api_key = d488d8afd93b32331cf6ea9d7003d4c3" -f process_dataset -id 23500
[10-10-2017 18:52:49] [OK] [Process Dataset] Processing dataset 23500 on special request.
[10-10-2017 18:52:49] [OK] [Process Dataset] Processing dataset 23500 - obtaining basic qualities.
java.lang.NullPointerException
	at weka.core.Instances.setClass(Instances.java:1468)
	at org.openml.webapplication.features.ExtractFeatures.getQualities(ExtractFeatures.java:130)
	at org.openml.webapplication.ProcessDataset.process(ProcessDataset.java:62)
	at org.openml.webapplication.ProcessDataset.<init>(ProcessDataset.java:40)
	at org.openml.webapplication.Main.main(Main.java:106)
[10-10-2017 18:52:49] [Error] [Process Dataset] Dataset 23500 - Error: null
```

**Comment by joaquinvanschoren** [comment]
all reverted to in_preparation now

**Comment by joaquinvanschoren** [comment]
Can this be closed now?
