### ISSUE TITLE
Test server errors since yesterday

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#440]
1) https://test.openml.org/api/v1/json/data/qualities/list gives me no results?
2) https://test.openml.org/api/v1/json/task/list gives me no results?
3) uploading datasets to the test server does not work anymore, I am getting a message "Extra content at the end of the document".

**Comment by joaquinvanschoren** [comment]
1 and 2 work as expected?
3 I don't know, can you try again, please?

**Comment by janvanrijn** [comment]
Recently, we had a huge internal update (specification is the same but data quality related features should be more stable). 

During the development period the test server was instable and unit tests failed. Should all be working by now again.

**Comment by giuseppec** [comment]
Ok, nice. Works again. Another bug is "An Elastic Search Exception occured." when trying to delete datasets (directly after having uploaded them).
