### ISSUE TITLE
Flow is not returned by API call

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#451]
I just figured out that [flow 3805](https://www.openml.org/f/3805) is not returned when I check for the list of flows uploaded by myself (user 86): https://www.openml.org/api/v1/flow/list/uploader/86

**Comment by janvanrijn** [comment]
@joaquinvanschoren @giuseppec @berndbischl 

Again one issue with the tags in the listing functions. I will drop this function immediately and completely. Please adapt your api's accordingly.

**Comment by janvanrijn** [comment]
My PR has been merged and the flow is visible again. I will send an email with clarification about the issue.
