### ISSUE TITLE
connection: close -- why?

### ISSUE THREAD

**Issue by TGlas** [openml/OpenML#479]
I noticed that OpenML seems to close the connection after each REST request. At least, the header field

```
connection: close
```

seems to be present in the `http` reply, no matter what I do (web interface or my own programmatic requests).

Please don't do that. This is particularly relevant after switching to `https`, since opening a new connection comes with a significant TLS handshake overhead.

**Comment by joaquinvanschoren** [comment]
Are you sure that we close it? The header of https://www.openml.org/api/v1/task/1 looks like this.
Notice the Connection: KeepAlive

<img width="599" alt="screen shot 2017-10-17 at 01 17 41" src="https://user-images.githubusercontent.com/1724503/31639449-1360602a-b2d9-11e7-86ee-0d7fc6a37891.png">

**Comment by TGlas** [comment]
Thanks for looking into this. Here is an example of "connection: close":
https://test.openml.org/api/v1/json/task/1


```
Access-Control-Allow-Headers | Origin, X-Requested-With, Content-Type, Accept
Cache-Control | no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection | close
Content-Encoding | gzip
Content-Length | 433
Content-Type | application/json; charset=utf-8
Date | Tue, 17 Oct 2017 06:40:48 GMT
Expires | Thu, 19 Nov 1981 08:52:00 GMT
Pragma | no-cache
Server | Apache/2.2.15 (CentOS)
Vary | Accept-Encoding
X-Powered-By | PHP/5.5.38
```

The simplest conjecture seems to be that this is misconfigured only on the test server.

**Comment by joaquinvanschoren** [comment]
Thanks, found it.
Better now?

**Comment by TGlas** [comment]
Thanks a lot!
