### ISSUE TITLE
evaluation/list gives HTTP ERROR 500

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#498]
1) This works (has <= 10000 results): https://www.openml.org/api/v1/json/evaluation/list/tag/study_14/function/area_under_roc_curve

2) This also works (server tells us that there are too many results):
https://www.openml.org/api/v1/json/evaluation/list/task/10101/function/area_under_roc_curve

3) This does not work (I get HTTP ERROR 500):
https://www.openml.org/api/v1/json/evaluation/list/tag/botV1/function/area_under_roc_curve
however, this works https://www.openml.org/api/v1/json/evaluation/list/tag/botV1/function/area_under_roc_curve/limit/10000

Seems like a bug (was reported in https://github.com/openml/openml-r/issues/399)?

**Comment by joaquinvanschoren** [comment]
Hmm, if I run this locally, I get:
{"error":{"code":"543","message":"Too many results","additional_information":"Size of result set: 492805 evaluations; max size: 10000. Please use limit and offset."}}

**Comment by joaquinvanschoren** [comment]
It's actually 5899300 evaluations on the production server, that's why it crashed.

I improved the pre-test. Should be fine now.

**Comment by giuseppec** [comment]
thx. solved
