### ISSUE TITLE
[URGENT] Where is study 30?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#500]
I've created study 30 (which consists of 6 flows and 6 tasks => 36 runs) for the R paper.
I've unit tests that check if everything is fine with this study as this is used in the R paper.

Since yesterday I noticed the following bugs for this study:
1) https://www.openml.org/s/30 is empty? Which is bad as we use it in the paper.
2) https://www.openml.org/api/v1/json/evaluation/list/tag/study_30 does not show me the results of the 36 runs, however, this https://www.openml.org/api/v1/json/run/list/tag/study_30 works.

**Comment by joaquinvanschoren** [comment]
It's back :)

**Comment by giuseppec** [comment]
But https://www.openml.org/api/v1/json/evaluation/list/tag/study_30 still tells me

```
{"error":{"code":"543","message":"Too many results","additional_information":"Size of result set: 5944261 runs; max size: 10000. Please use limit and offset."}}
```
how can this happen if study 30 only consists of 36 runs?

**Comment by giuseppec** [comment]
Maybe this has something to do with https://github.com/openml/OpenML/issues/498

**Comment by joaquinvanschoren** [comment]
Silly bug. Fixed now.

**Comment by giuseppec** [comment]
Confirmed :).
