### ISSUE TITLE
Reference machines to compare runtimes over different CPU's

### ISSUE THREAD

**Issue by janvanrijn** [openml/OpenML#52]
Although OpenML does not natively support the evaluation of runtimes (since the model building and prediction phase are executed locally), it is possible for a client to also upload the run time as a user defined evaluation measure. However, since clients PC's can have different CPU power, it makes sense to also store some sort of CPU information along with it. The most straightforward thing to do seems to be a CPU benchmark score in terms of Mega (or Giga) Flops. 

Today I experimented with various CPU Benchmark tools to estimate the CPU score on various benchmark test. The results varied from 45 Mflops to 2700 Mflops... On the same PC. Which cannot be correct, of course. 

Does anyone have experience with these kind of benchmarks? If so, what is a good suit for performing these? I found this suit (http://math.nist.gov/scimark2/index.html) on the internet which seem to have reasonable relative performance between various PC's, however I cannot entirely trust the absolute scores. 

And how are the results to be interpreted? E.g., if we want to do an experiment in which we also compare runtimes, are we allowed to multiply the CPU time with this measures benchmark score and compare the final outcomes, or should we be more conservative? For example, only compare runtimes with each other that were run on a CPU with a similar benchmark score.

**Comment by joaquinvanschoren** [comment]
Went off-topic. Will open a new issue about standardized custom evaluation measures.
