### ISSUE TITLE
Incomplete feature visualization for new uploaded data sets

### ISSUE THREAD

**Issue by Goschjann** [openml/OpenML#526]
# Problem
I iterated through some data sets and uploaded new, updated versions of them (as part of my job in Bernds team). Those new datasets are not visualized in a correct way. Only the features for those observations that contain the first level of the last factor variable are visualized, the rest is left out. 

# MWE
Check the original dataset „Australian 3“ (id: 40509) and the new version „Australian 4“ (id: 40981). Only the "A15 == 0" observations are displayed. When downloaded via getOMLDataset(40981), the new version is complete and contains all observations.

**Comment by joaquinvanschoren** [comment]
Must be a plotting issue. The JSON meta-data shows the stats correctly:
https://www.openml.org/d/40981/json

**Comment by joaquinvanschoren** [comment]
Confirmed. Fixed with PR https://github.com/openml/website/pull/220

<img width="789" alt="screen shot 2017-12-22 at 01 31 45" src="https://user-images.githubusercontent.com/1724503/34280476-210d16e2-e6b8-11e7-91a2-cc89e21b0405.png">
