### ISSUE TITLE
Issues with titanic dataset

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#527]
Looking for titanic: https://www.openml.org/search?q=titanic&type=
the "titanic" dataset is actually a highly processed version and not the standard "titanic" dataset. That's "titanic_full". That's a bit weird, in particular given the fact we have "versions". Shouldn't these be versions of each other? Also, the search result says
![image](https://user-images.githubusercontent.com/449558/33633173-e31e3e60-d9dd-11e7-90a6-e3c24cb7dbed.png)

I'm not sure why there are 370 classes. Probably the default_target_attribute is not set correctly. But I can't see how it is set at all from the web interface? (It should be "survived")

**Comment by amueller** [comment]
Looking at the json, the ``default_target_attribute`` is null: https://www.openml.org/d/40945/json

**Comment by amueller** [comment]
Opened #528 for the more general problem of computing classes for ``default_target_attribute='null'``. This issue should be for fixing how the attribute is set for titanic, and possibly having a version of ``titanic`` thats ``titanic_full`.

**Comment by joaquinvanschoren** [comment]
We renamed titanic_full to titanic a while ago. I now also set the correct target feature.

**Comment by amueller** [comment]
thanks!
