### ISSUE TITLE
Easy linking to headers

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#538]
_From @amueller on November 16, 2017 18:10_

Many pages (in particular sphinx generated pages) allow deep links to headers like this:
http://scikit-learn.org/dev/modules/lda_qda.html#dimensionality-reduction-using-linear-discriminant-analysis

hovering over a header will show a paragraph sign and allow you to copy a deep link.
I find this very helpful to link to sections. I have no idea what to google for to make that work. I'm sure whatever frontend we're using supports that...

_Copied from original issue: openml/website#212_

**Comment by joaquinvanschoren** [comment]
_From @amueller on January 16, 2018 15:26_

Apparently this is how you do this:
https://github.com/scikit-learn/scikit-learn/commit/3e5469eda719956c076ae8e685ec1183bfd98569

**Comment by joaquinvanschoren** [comment]
Also requested by Matthias to directly link to sections in the bootstrap guide.
Implement as part of the documentation redesign

**Comment by amueller** [comment]
Given how easy this is to do I wouldn't wait for the redesign. I sent Hilde on a quest to make some minor fixes to the website.

That at least will test our current development model for the website and might inform how we are going to change the infrastructure.

**Comment by joaquinvanschoren** [comment]
I meant the redesign I'm currently doing in the develop branch. 
All help welcome. Please go ahead :)

**Comment by amueller** [comment]
ahh... so there's no big rewrite going to happen any time soon? (not questioning that, just asking)

**Comment by joaquinvanschoren** [comment]
It depends. I'll probably put this on hold until I get a dedicated developer. April at the soonest.

**Comment by amueller** [comment]
Makes sense.

**Comment by joaquinvanschoren** [comment]
Anchors are added now.
