### ISSUE TITLE
Anchors to headers

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#593]
_From @mfeurer on March 18, 2016 12:49_

I want to link to the dataset section in the OpenML guide from the python API. So far, I can only link [openml.org/guide](openml.org/guide), it would be great if I could link openml.org/guide#data

_Copied from original issue: openml/website#42_

**Comment by joaquinvanschoren** [comment]
There is suggestion in #57 to redesign the guide, and have a series of blog posts discussing various aspects of OpenML. You would then also have direct links to aspects such as datasets, and room for much more detail.

**Comment by amueller** [comment]
Duplicate of #548 and #538. #538 actually provides the solution: https://github.com/scikit-learn/scikit-learn/commit/3e5469eda719956c076ae8e685ec1183bfd98569

**Comment by joaquinvanschoren** [comment]
Indeed a duplicate of #538
