### ISSUE TITLE
database snapshot not available currently

### ISSUE THREAD

**Issue by PhilippPro** [openml/OpenML#610]
when I try to click on the [link](https://www.openml.org/downloads/ExpDB_SNAPSHOT.sql.gz):

Not Found

The requested URL /downloads/ExpDB_SNAPSHOT.sql.gz was not found on this server.

**Comment by joaquinvanschoren** [comment]
Sorry, the cronjob broke.
Fixed it. The snapshot is building right now. Check back in about 15mins.
