### ISSUE TITLE
Cannot edit study description

### ISSUE THREAD

**Issue by MarianoRico** [openml/OpenML#633]
Why I can edit the description of https://www.openml.org/s/91
but not the one from https://www.openml.org/s/53 ?

**Comment by joaquinvanschoren** [comment]
Sorry, small wiki issue. Fixed now!

**Comment by MarianoRico** [comment]
It is happening again :-S
Instead of the "edit icon" there is a endless "loading icon". Tested with https://www.openml.org/s/53

**Comment by joaquinvanschoren** [comment]
Thanks. I restarted the wiki engine. Should be ok now!
