### ISSUE TITLE
Why was travis removed?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#635]
In https://github.com/openml/OpenML/commit/e0da4c5187594869cd1199e676f60776e5b51d33 travis was removed. Could you please add it again?

I want to set this up https://docs.travis-ci.com/user/triggering-builds/#Customizing-the-build-configuration so that I can always trigger the R package travis builds when you push a commit to the openml/OpenML repo. This way I can better figure out what server change caused the R package to fail.

**Comment by giuseppec** [comment]
Did a PR here https://github.com/openml/OpenML/pull/636 not sure about the other stuff but bash script should run directly after the travis build script finished.

**Comment by joaquinvanschoren** [comment]
That Java code was moved to a different repo.
Could you write a minimal travis config needed to trigger the R unit tests?

**Comment by joaquinvanschoren** [comment]
hmm, let me try something

**Comment by joaquinvanschoren** [comment]
I created a minimal travis config that runs your script. Works fine :)

**Comment by mfeurer** [comment]
@giuseppec @joaquinvanschoren this looks like an interesting feature, but does a commit imply a server change?

**Comment by giuseppec** [comment]
I hope. If not could you guys explain your workflow for server changes?

**Comment by joaquinvanschoren** [comment]
Not automatically. But usually when a commit is done and all checks pass, we also pull it on the server. 
The test server does this for the develop branch and the production server the master branch.

In any case, you want to run the tests on the commit. We will wait until all checks have passed before we pull and change the server.

**Comment by mfeurer** [comment]
But if we run the individual tests on a commit to the server, we don't actually get the changes (unless the tests and pulling on the server happen in <1 min); they might be there later or not at all.
