### ISSUE TITLE
Missing averaged evaluations

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#65]
Some evaluations, e.g. build_cpu_time, are stored as per-fold statistics, but the results are not averaged and stored in the evaluations table, and are thus not visible in the webinterface.

Verify the code that calculates these averages and add the evaluations that are missing.

Thanks!

**Comment by berndbischl** [comment]
done?

**Comment by joaquinvanschoren** [comment]
this has been fixed. cpu times are now averaged
