### ISSUE TITLE
dataset quality "MajorityClassPercentage" - inconsistent value definition

### ISSUE THREAD

**Issue by bstrang** [openml/OpenML#657]
The value of the dataset quality "MajorityClassPercentage" is in some cases a ratio (< 1.00) and in some cases a percentage value (i.e. ratio * 100).
[meta_features.zip](https://github.com/openml/OpenML/files/1798298/meta_features.zip)

**Comment by janvanrijn** [comment]
Thanks for reporting this. I will have a look at this very soon

**Comment by bstrang** [comment]
The percentage issues seems to apply for various 'Percentage...' meta features ...

**Comment by janvanrijn** [comment]
I close this one, as #659 seems to cover the issue
