### ISSUE TITLE
task/dataset of run not shown on OpenML

### ISSUE THREAD

**Issue by hildeweerts** [openml/OpenML#691]
There are a few tasks that consistently seem to result in runs for which no task and no dataset are shown on openml.org.

E.g. the following runs on task 9976: 
* https://www.openml.org/r/8941232 (flow 8310, R model)
* https://www.openml.org/r/8941401 (flow 8317, sklearn model)

And the following run on task 9981:
* https://www.openml.org/r/8941416 (flow 8315, sklearn model)

Even though in the xml-file of the run, the right task_id and flow_id are mentioned. As an example the xml of run 8941232:
``` 
<oml:run xmlns:oml="http://openml.org/openml">
  <oml:task_id>9976</oml:task_id>
  <oml:flow_id>8310</oml:flow_id>
  <oml:tag>mDataExp</oml:tag>
  <oml:tag>Modelage</oml:tag>
  <oml:tag>study_107</oml:tag>
  <oml:input_data/>
  <oml:output_data/>
</oml:run>
```
Does anybody know why this happens? I suspect it might be a frontend issue, since the Python API correctly recognises a run to already exist on the server, even though none of the runs are shown on the task page.

**Comment by janvanrijn** [comment]
Run 8941232 is not processed yet

**Comment by hildeweerts** [comment]
Allright!
