### ISSUE TITLE
SQL error on the test server

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#719]
Hey, when retrieving task 7 (https://test.openml.org/t/7) the server returns the following error:

```
Caught exception: {"_index":"openml","_type":"task","_id":"7","found":false}
A PHP Error was encountered

Severity: Notice

Message: Undefined property: MY_Loader::$task

Filename: t/pre.php

Line Number: 104

Backtrace:

File: /var/www/openml.org/public_html/openml_OS/views/pages/frontend/t/pre.php
Line: 104
Function: _error_handler

File: /var/www/openml.org/public_html/openml_OS/helpers/cms_helper.php
Line: 19
Function: view

File: /var/www/openml.org/public_html/openml_OS/controllers/Frontend.php
Line: 80
Function: loadpage

File: /var/www/openml.org/public_html/index.php
Line: 334
Function: require_once
A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

SELECT io.name, io.type, io.description, tt.description as typedescription, io.io, io.requirement, ti.value FROM task_type_inout io left join task_inputs ti on (io.name = ti.input and ti.task_id=7) left join task_io_types tt on io.type=tt.name WHERE io.ttid=

Filename: models/abstract/Database_read.php

Line Number: 31
```

@ArlindKadra that's part of the reason why unit tests fail at the moment.

**Comment by janvanrijn** [comment]
Unit tests do not rely on the frontend right?

**Comment by janvanrijn** [comment]
That is quite logical as task 7 does not seem to exist on the test server. Es does not seem to be aware of this; please ask @joaquinvanschoren

**Comment by joaquinvanschoren** [comment]
Not sure what to do here :)

According to the database there *is* a task 7.
According to the list task API, it also exists: https://test.openml.org/api/v1/task/list
And it is retrieved: https://test.openml.org/api/v1/xml/task/7

There is no run with ID 2, but I also don't see why that is an issue. Neither the API nor the search engine claim that it does.

Was this solved in the mean time?

**Comment by joaquinvanschoren** [comment]
https://test.openml.org/u/86/tasks works now. Turns out that page was never implemented 😲

**Comment by joaquinvanschoren** [comment]
Which 'create task button' doesn't work?

**Comment by joaquinvanschoren** [comment]
I created and deleted task 1069. It was correctly deleted, also from the search engine.
I then created task 1070, and this all works fine:
https://test.openml.org/t/1070
https://test.openml.org/api/v1/task/list/

That SQL error I could not reproduce.

**Comment by mfeurer** [comment]
Thanks a lot @joaquinvanschoren for checking this and implementing the missing webpage. I will close this now as the error no longer exists. Creating a task on the test server via the website does in general not work for me.
