### ISSUE TITLE
list data status filter bug

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#739]
This used to work:

https://test.openml.org/api/v1/json/data/list/status/active

Now I get:

```
{"error":{"code":"371","message":"Input not safe","additional_information":"Filters with illegal values: status"}}
```

**Comment by janvanrijn** [comment]
Mea culpa.. 

should be fixed.

**Comment by giuseppec** [comment]
Thx, fixed. Another similar one: 

This used to work:
https://www.openml.org/api/v1/json/task/list/data_name/iris

Now it results in

```
{"error":{"code":"481","message":"Filter input not according to constraints","additional_information":"Filters with illegal values: data_name"}}
```

**Comment by janvanrijn** [comment]
Fixed (on test server)

**Comment by janvanrijn** [comment]
Thanks for reporting!
