### ISSUE TITLE
Sign in broken

### ISSUE THREAD

**Issue by thvasilo** [openml/OpenML#744]
I've tried signing in today to upload a dataset, but after I fill in user/pass and click sign in nothing happens.

When in Data view the sign in window does not come up after clicking sign in in the top right.
In the main website https://www.openml.org/home, I get the sign in box, but after filling in user/pass and clicking the Sign In button, the window just disappears, I'm still not signed in.
Tested on FF and Chrome under Linux, with copy-pasted/autofilled password.

**Comment by joaquinvanschoren** [comment]
Thanks for reporting. Fixed now.

**Comment by dalmia** [comment]
Encountering the same problem on Linux 16.04. Both on Chromium and Firefox
