### ISSUE TITLE
Cannot create supervised classification task on dataset 41070 (USPS)

### ISSUE THREAD

**Issue by irfannurafif** [openml/OpenML#745]
https://www.openml.org/new/task?data=USPS(1)#!task-type-1

Target feature: int0
Estimation procedure: 10-fold crossvalidation

After submitting the form, no new task was created.

**Comment by joaquinvanschoren** [comment]
The ARFF file says that int0 is a numeric feature, so the API probably refuses to make a classification task on this?

It looks like int0 is actually categorical. For now you'll have to download the ARFF file, fix the feature description, upload the dataset as a new version, and make the classification task on the corrected version.

**Comment by irfannurafif** [comment]
@joaquinvanschoren Done reuploading on https://www.openml.org/d/41082 . Issue closed.
