### ISSUE TITLE
[Low priority] Citation landing page

### ISSUE THREAD

**Issue by ArlindKadra** [openml/OpenML#757]
https://www.openml.org/cite

On the first landing it shows the menu opened and it blocks a part of the page. When disabling the menu and activating it again, it fixes the problem.

![image](https://user-images.githubusercontent.com/24679211/41166719-49531238-6b41-11e8-900a-b45a63d900b6.png)

**Comment by joaquinvanschoren** [comment]
fixed in new frontend
