### ISSUE TITLE
No successful trace associated with this run

### ISSUE THREAD

**Issue by ArlindKadra** [openml/OpenML#767]
I am having some problems with runs associated with traces. Currently a trace arff is uploaded with the run, however while trying to access it, an error is raised. 
Run:
`https://test.openml.org/api/v1/xml/run/258`
Trace:
`openml.exceptions.OpenMLServerException: https://test.openml.org/api/v1/xml/run/trace/258 returned code 570: No successful trace associated with this run.`

The trace arff file is displayed without errors in weka. 
In the python connector, we recently added the setup_string attribute in the arff file. It is of String type and until now it has a None value in the majority of cases.

**Comment by hildeweerts** [comment]
When I come across this error it usually means that something went wrong during the evaluation of the run. You can try resetting the run using the API: https://www.openml.org/api/v1/run/reset/run_id.

Hope this helps :)

**Comment by mfeurer** [comment]
Thanks @hildeweerts for your suggestion. @janvanrijn could the issue be that there are missing values (`?`) for the setup_string in this file: https://test.openml.org/data/download/997/trace.arff ?

**Comment by joaquinvanschoren** [comment]
This seems related to #960 but that actually has a different API call and a different error code. Probably this issue is outdated and can be closed.

**Comment by ArlindKadra** [comment]
@joaquinvanschoren True. There was a problem with how values were being given to setup string, if I remember correctly @janvanrijn solved the issue. I am closing the issue, in case we observe the same problem we can reopen at a later time.
