### ISSUE TITLE
OpenML run returns "No evaluations yet (or not applicable)"

### ISSUE THREAD

**Issue by irfannurafif** [openml/OpenML#775]
OpenML run evaluation still returns "No evaluations yet (or not applicable)" after >3 hours 
https://www.openml.org/search?type=run 

It seems like it also happened on the test server but only on supervised classification tasks https://test.openml.org/search?type=run

**Comment by janvanrijn** [comment]
Thanks for pointing this out. My bad, I introduced a problem at the evaluation engine. 

If the keras wrapper is still under development, can you please only submit runs to the test server?

**Comment by janvanrijn** [comment]
The error is resolved and runs should be evaluated shortly both on live and test. 

> If I recall correctly, OpenML runs on test server are regularly deleted, but I need to save the evaluation results for reproducibility in my thesis. So I can't use the test server to record the results.

This is correct. I leave it up to you and @joaquinvanschoren (I assume your thesis supervisor) to judge whether the keras connector is stable enough to submit runs to the live server, but personally I would prefer to first have a code review from one of the core developers (focusing on unit tests) to determine whether in it's current state the package is maintainable and able to ensure correct serialization.

**Comment by joaquinvanschoren** [comment]
Irfan is working on the final comments from Matthias and adding more unit tests.
He needs the results for his thesis now. If we still find issues we can always remove the old runs and flows and upload new ones.
