### ISSUE TITLE
filters on website broken

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#791]
I tried to search for datasets on the website, but the result is empty as soon as I add more than one constraint.
I think the reason is that an ampersand is added in the url:
https://www.openml.org/search?q=qualities.NumberOfInstances%3Agt%3B100%2520qualities.NumberOfFeatures%3A%253E3&type=data

Reproduce:
Click on "filter" add ``>3`` to ``Instances``, and ``>3`` to ``features`` and click "search".

**Comment by joaquinvanschoren** [comment]
Saw it too earlier today. Looking into it.

**Comment by joaquinvanschoren** [comment]
Not for the old frontend. The new frontend will be unit tested via Jest. I'll add a unit test there.

**Comment by amueller** [comment]
Sweet!

**Comment by amueller** [comment]
unrelated: It looks like there's only 2500 active datasets. Is that right? That seems pretty far from the 20000 advertised on the landing page. It looks like nearly all the rest are "in preparation". What am I to make of that?
