### ISSUE TITLE
Wrong "adult" dataset in OpenML100 / CC18

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#813]
This one is tagged:
https://www.openml.org/d/1590

It should be this:
https://www.openml.org/d/1119

It should exclude the "fnlwgt" column (not sure it's marked, can't see that in the web interface).
Also the sklearn fetcher fails on this dataset.
CC @janvanrijn

**Comment by amueller** [comment]
It doesn't look like ``fnlwgt`` is dropped when loading from the python interface.
(also that interface doesn't crash like the scikit-learn one does).

**Comment by janvanrijn** [comment]
Regarding scikit-learn, there was some flawed if logic in a for loop. 

I created a PR to improve the code-quality and fix the problem:
https://github.com/scikit-learn/scikit-learn/pull/12330

**Comment by janvanrijn** [comment]
We should deactivate the current dataset(s) and upload a new version. Based on what information do you think that the `fnlwgt` column should be ignored?

**Comment by amueller** [comment]
Based on the description of the dataset. Original paper maybe?? It's a
reweighting of the individual so that the overall population is represented
better.

**Comment by amueller** [comment]
Ok looks like the original paper included the ``fnlwgt`` feature.
The description says
```
| Description of fnlwgt (final weight)
|
| The weights on the CPS files are controlled to independent estimates of the
| civilian noninstitutional population of the US.  These are prepared monthly
| for us by Population Division here at the Census Bureau.  We use 3 sets of
| controls.
|  These are:
|          1.  A single cell estimate of the population 16+ for each state.
|          2.  Controls for Hispanic Origin by age and sex.
|          3.  Controls by Race, age and sex.
|
| We use all three sets of controls in our weighting program and "rake" through
| them 6 times so that by the end we come back to all the controls we used.
|
| The term estimate refers to population totals derived from CPS by creating
| "weighted tallies" of any specified socio-economic characteristics of the
| population.
|
| People with similar demographic characteristics should have
| similar weights.  There is one important caveat to remember
| about this statement.  That is that since the CPS sample is
| actually a collection of 51 state samples, each with its own
| probability of selection, the statement only applies within
| state.

```
I don't entirely understand this feature but I guess it should be included?

**Comment by amueller** [comment]
also shouldn't ``adult`` and ``adult-census`` be different versions of the dataset?

**Comment by janvanrijn** [comment]
Moved this to https://github.com/openml/OpenMLFirstBenchmarkSuite/issues/37
