### ISSUE TITLE
Nightly Snapshot offline

### ISSUE THREAD

**Issue by jakob-r** [openml/OpenML#844]
https://www.openml.org/downloads/ExpDB_SNAPSHOT.sql.gz does not work anymore. It would be highly appreciated if the snapshot is available again. We kind of depend on it.

**Comment by joaquinvanschoren** [comment]
Sorry, we moved to a new server and forgot to activate that. Done now. 
The next snapshot should be available in 15min or so.

**Comment by jakob-r** [comment]
Thanks!
