### ISSUE TITLE
No documentation for runs

### ISSUE THREAD

**Issue by ArlindKadra** [openml/OpenML#848]
I am checking out the documentation from:
`https://openml2.win.tue.nl/api_docs#!/`
Since I am reaching the documentation from the test server, is this an outdated link or there never was any documentation for runs?

**Comment by ArlindKadra** [comment]
Right now the REST api documentation does not show at all for me

**Comment by joaquinvanschoren** [comment]
Fixed. There was a small error in the documentation of the newest added call.

The second issue (not seeing docs at all) was likely caused by a redirection issue as are switching to a new main server. Should be fine now.

**Comment by ArlindKadra** [comment]
Great ;)
