### ISSUE TITLE
currently many errors on test server

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#849]
For example this https://test.openml.org/api/v1/json/evaluationmeasure/list results in 
```
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: 8192</p>
<p>Message:  The each() function is deprecated. This message will be suppressed on further calls</p>
<p>Filename: core/MY_Api_Model.php</p>
<p>Line Number: 60</p>
```

and also https://test.openml.org/d/1 shows a "not found" in the description:
![image](https://user-images.githubusercontent.com/4238748/48088385-2a29e200-e202-11e8-95c3-8c5e9b69a8f1.png)

**Comment by joaquinvanschoren** [comment]
We upgraded all servers to PHP 7. Sorry about the messages.

**Comment by joaquinvanschoren** [comment]
Fixed now. Please check and close :)

**Comment by giuseppec** [comment]
looks good now, thx.
