### ISSUE TITLE
Wiki / Markdown descriptions do not work anymore

### ISSUE THREAD

**Issue by janvanrijn** [openml/OpenML#857]
Wiki is already loading for minutes ... 

![screenshot from 2018-11-09 18-28-24](https://user-images.githubusercontent.com/2292730/48293477-4a011600-e44d-11e8-8850-c1c0803534bd.png)

**Comment by joaquinvanschoren** [comment]
Thanks. Fixed now.

**Comment by janvanrijn** [comment]
Doesn't seem fixed .. 

![screenshot from 2018-11-10 16-40-35](https://user-images.githubusercontent.com/2292730/48306476-5fd31180-e507-11e8-844f-076f63770ad3.png)

**Comment by joaquinvanschoren** [comment]
Darn, it was fixed (it was a bad apache setting). Then I pulled master and that caused another error. FIxing now.
