### ISSUE TITLE
Add options for sorting/filtering by any property/threshold on a dataset in search.

### ISSUE THREAD

**Issue by AndriyMulyar** [openml/OpenML#871]
A useful option would be to allow for sorting/filtering by any property/threshold on property of a dataset. Particularly, queries for things like 'all dataset's below a given minority class percentage' would allow a more granular access of data.

**Comment by joaquinvanschoren** [comment]
Hi Andriy, 

You can filter based on any dataset quality, e.g. add this to the query (in the search box):
qualities.MinorityClassPercentage:<0.01

The full list of properties is here: 
https://www.openml.org/search?q=%2520measure_type%3Adata_quality&type=measure

Same goes for the sorting, although you'd have to do that in the URL by adding:
&sort=qualities.NumberOfInstances&order=desc
