### ISSUE TITLE
Get rid of Bootstrap framework and make the site operable without JavaScript

### ISSUE THREAD

**Issue by KOLANICH** [openml/OpenML#878]
Bootstrap uses JS where CSS+HTML is enough.

**Comment by joaquinvanschoren** [comment]
There is too much going on to do without javascript. The new frontend will use React with (hopefully) no custom JS. We'll use Material-UI instead of Bootstrap.

**Comment by KOLANICH** [comment]
Using a JS framework won't solve the issue of dependency on JS. I don't know any legitimate reasons to render HTML from JS client-side on page load instead of rendering HTML server-side.

But I see many examples of it being done to just blackmail users to enable JS in order to make trackers work (some websites just hide the content with css and undo hiding in JS, some embed html into JS strings and then render it on load with `innerHTML`, some other do measures like obfuscation, it is very clear that all this is done intentionally and this is done the way to  prevent users without JS from using websites).

**Comment by joaquinvanschoren** [comment]
Our reasons have nothing to do with tracking. They are: 
- ease of development (use of modern frontend frameworks)
- attracting more bright people to help improve the frontend
- maintenance and unit testing
- allowing interactive visualization of data
- scalability (reduce the number of pageloads we need to serve)

We want to offer people an easy interface to browse all the data that OpenML has to offer. Having to do complete new pageloads every time is slow, difficult, not enjoyable, and it is heavy on the server.

We wouldn't mind at all if someone would build and host a no-JS frontend (you can totally do that on top of our API), but for our main frontend we have decided against this for the reasons above.

Obviously the practices that you mentioned above should be stopped, but banning JS altogether doesn't seem to be the right approach.

**Comment by KOLANICH** [comment]
>Our reasons have nothing to do with tracking.

I understand.

>scalability (reduce the number of pageloads we need to serve)

XMLHttpRequest / Fetch requests are also HTTP requests and the backend still has to do DB/memcached accesses. So it is not very clear that using AJAX would reduce loads a lot. It depends on lot of things, like caching in browser, cache-related headers, HTTP/2, compression, overhead on HTML markup, etc...
