### ISSUE TITLE
Specifying filters manually on website adds ampersand

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#886]
If you enter a filter on datasets on the website, like ``qualities.MajorityClassPercentage>.5``, if you execute the search, an ampersand will be added to the query: ``qualities.MajorityClassPercentage&>1`` that's very confusing and sometimes prevents the search from being executed again.

**Comment by amueller** [comment]
Possibly this is only an issue with ``>`` but I'm not sure.

running a filter by inserting ``>5`` into the ``numberOfClasses`` field works. But providing ```qualities.NumberOfClasses:>5`` as a filter doesn't work.
Also, I specify ``numberOfClasses`` in the field and run the search, and then simply press return again on the search field, the search returns nothing any more.

**Comment by joaquinvanschoren** [comment]
Thanks, fixed now.

**Comment by amueller** [comment]
thanks, seems fixed indeed!
