### ISSUE TITLE
Access and Run Properties on a Dataset 

### ISSUE THREAD

**Issue by dsleo** [openml/OpenML#909]
Hello,

OpenML is such a great initiative. I wasn't able to find the properties definition in the repo. 
Is it possible with the REST API (or another API for that matter) to get a dataset's properties? Or to run it on a new dataset ? 

Thanks for your help !

**Comment by joaquinvanschoren** [comment]
Hi, 

Sure. Dataset properties are called 'qualities'. 

You can search them on the website: https://www.openml.org/search?q=%2520measure_type%3Adata_quality&type=measure

Via the REST API: https://www.openml.org/api_docs#!/data/get_data_qualities_id

In the Python API, they are included as a dictionary in the dataset object: 
https://docs.openml.org/Python-API/

Similarly in the other APIs.

Hope that helps,
Joaquin

**Comment by dsleo** [comment]
Many thanks, I'll go ahead and close this then !

**Comment by dsleo** [comment]
Hi again,

Regarding my last point, I haven't found a way to run qualities on a new dataset, but perhaps I've missed something ? Is this something considered to be added to the Python API ?
Or do I have to manually run EvaluationEngine on my new datasets ?

Thanks again for your help !

**Comment by janvanrijn** [comment]
This should go automatically.

If it does not do so for a particular dataset in reasonable time (several minutes), and doesn't show a clear error message, please open an issue and we will have a look at it :)

**Comment by dsleo** [comment]
So perhaps I've missed this from the API's doc, but I have datasets (which are not from openML) for which I'd like to have the qualities (metafeatures) as well. Is there a way to get those for an external dataset ?

**Comment by janvanrijn** [comment]
You can try the java evaluation engine:
https://github.com/openml/evaluationengine
(also on maven)

but probably easier to just upload the dataset ;)
