### ISSUE TITLE
Uploading regression task to test server failing

### ISSUE THREAD

**Issue by ArlindKadra** [openml/OpenML#917]
Task xml:
```
<oml:task_inputs xmlns:oml="http://openml.org/openml">
	<oml:task_id>625</oml:task_id>
	<oml:task_type_id>2</oml:task_type_id>
	<oml:input name="source_data">105</oml:input>
	<oml:input name="target_feature">time</oml:input>
	<oml:input name="estimation_procedure">23</oml:input>
</oml:task_inputs>
```
Server output:
`
b'<oml:error xmlns:oml="http://openml.org/openml">\n\t<oml:code>622</oml:code>\n\t<oml:message>Input value does not match allowed values in foreign column.</oml:message>\n\t\t<oml:additional_information>problematic input: estimation_procedure</oml:additional_information>\n\t</oml:error>\n''`

The estimation procedure id is 23. 
On the website it is allowed to create 10 times 10 fold cross-validation. 
100 times is not allowed even on the website.

Trying with an id of 21 which corresponds to 10 times 10 fold cross-validation and is allowed on the website returns the same response:

`b'<oml:error xmlns:oml="http://openml.org/openml">\n\t<oml:code>622</oml:code>\n\t<oml:message>Input value does not match allowed values in foreign column.</oml:message>\n\t\t<oml:additional_information>problematic input: estimation_procedure</oml:additional_information>\n\t</oml:error>\n'`
```

<oml:task_inputs xmlns:oml="http://openml.org/openml">
	<oml:task_id>625</oml:task_id>
	<oml:task_type_id>2</oml:task_type_id>
	<oml:input name="source_data">105</oml:input>
	<oml:input name="target_feature">time</oml:input>
	<oml:input name="estimation_procedure">21</oml:input>
</oml:task_inputs>
```

**Comment by janvanrijn** [comment]
Please try estimation procedure id 9, which is 10x 10 fold cv for regression, ttid 2

Estimation procedure 23 is only available for task type id 1.

**Comment by janvanrijn** [comment]
Please close if solved :)

**Comment by ArlindKadra** [comment]
My bad, did not pay attention to the task id attribute in the estimation procedure list.
