### ISSUE TITLE
Unable to restart my password

### ISSUE THREAD

**Issue by rgmantovani** [openml/OpenML#918]
Hi,

I'm trying to login in my account on OpenML.
But, I lost my password and cannot restart with a new one.
Every time I try, I get this error message:

![screen shot 2019-02-12 at 09 29 29](https://user-images.githubusercontent.com/5933552/52640872-afd2c300-2ebe-11e9-97e7-23dad8d88b8d.png)

How do I fix this problem?
Thanks.

**Comment by joaquinvanschoren** [comment]
Confirmed. I can reproduce this.

**Comment by joaquinvanschoren** [comment]
Hi Rafael, 

We could not find an issue with the password reset. However, there is a 30-min interval in which you need to click the link in the email. Is it possible that you clicked it too late or that the email arrived too late?

Could you try again, please, making sure you click the link in the email within 30 minutes? 

We'll also update the non-informative error message.

**Comment by joaquinvanschoren** [comment]
Never mind the earlier comment. I can still reproduce this. It's not the time limit.

**Comment by joaquinvanschoren** [comment]
Ok, we found the issue. It works again now :).
Sorry for the inconvenience and the long wait.

**Comment by rgmantovani** [comment]
thanks Joaquin!
