### ISSUE TITLE
API can not return tagged runs

### ISSUE THREAD

**Issue by PGijsbers** [openml/OpenML#948]
Requesting runs tagged with 'curves' through the API gives a 'no results' reply after ~2 minutes.
E.g. the following link (using the read-only API key): https://openml.org/api/v1/xml/run/list/limit/10000/offset/0/tag/curves?api_key=c1994bdb7ecb3c6f3c8f3b35f4b47f1f 

However, runs do exist and can be retrieved through the web interface: https://www.openml.org/search?type=run&from=100&q=tags.tag%3Acurves

See also [the information in openml-python#654](https://github.com/openml/openml-python/pull/654#issuecomment-478272068).

**Comment by PGijsbers** [comment]
Tags and assigned as requested by @janvanrijn in the referenced issue.

**Comment by janvanrijn** [comment]
The tag `curves` does no longer have runs evaluated without error. Let close this issue. For the reason why these runs have errors, I would refer to the issue where files started missing several bytes (can't find issue but maybe @joaquinvanschoren can)
