### ISSUE TITLE
Account activation email has useless text part

### ISSUE THREAD

**Issue by mb706** [openml/OpenML#949]
It is good computer security practice to read email in plain text format. However, the OpenML.org "Account Activation" email plain text message reads as follows:

> Activate account for [MY EMAIL]
> Please click this link to Activate Your Account.

where the text "link" is obviously not a link, this being the plain-text view, and the activation link is not actually shown. I suggest including the activation URL with the plain-text part of the activation message.

**Comment by janvanrijn** [comment]
Thanks for the suggestion, it's on my list.

**Comment by janvanrijn** [comment]
I added this to the development branch and it is now available on the test server: test.openml.org. Will close for now, to keep the overview
