### ISSUE TITLE
bad characters in quality names

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#95]
There are three data qualities with "="s in their names:

RandomTreeDepth1AUC_K=0, RandomTreeDepth2AUC_K=0, RandomTreeDepth3AUC_K=0

When we use this as column names in R, the special characters are exchanged for "."s. This may lead to some confusion.

**Comment by berndbischl** [comment]
Status?

**Comment by janvanrijn** [comment]
Fixed this. Please close if you agree.

**Comment by joaquinvanschoren** [comment]
great, closing
