### ISSUE TITLE
Cannot fetch active datasets

### ISSUE THREAD

**Issue by sarim-zafar** [openml/OpenML#951]
I am unable to fetch the following active datasets using python API
[4537,252,202,486,495,559,563,565,525,538,700,669,1092,1168,4546,4562,4563,41022,40864]
All the errors are same except the last one

I get the following error:
OpenMLServerException: https://www.openml.org/api/v1/xml/data/features/4537 returned code 274: No features found. Additionally, dataset processed with error
OpenMLServerException: https://www.openml.org/api/v1/xml/data/features/252 returned code 274: No features found. Additionally, dataset processed with error
.
.
.
40864
```OpenMLServerError: Unexpected server error. Please contact the developers!
Status code: 403
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Forbidden</title>
</head>
  <body>
    <h3>403 Forbidden</h3>
    <p>You don't have the right access rights to view this page. </p>
  </body>
</html>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Forbidden</title>
</head>
  <body>
    <h3>403 Forbidden</h3>
    <p>You don't have the right access rights to view this page. </p>
  </body>
</html>```

**Comment by janvanrijn** [comment]
issue #483

let's close this issue
