### ISSUE TITLE
CC-18 has wisconsin breast cancer twise

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#954]
Not sure where else to open this, but 1510 and 15 seem to be basically the same dataset and both are tagged CC-18. Not sure if that's an issue with just the dataset tags.

**Comment by joaquinvanschoren** [comment]
There are two versions on UCI, one is 'original', the other 'diagnostic'. They seem to be quite different and they have different features and a different number of instances. 

I went back to our original discussion on this (for the OpenML100) and it seems that we did discuss this and decided that they are different enough but that these should be a note in the description, which was added. 

If you do think that these are indeed 'basically the same', we can of course reconsider.

**Comment by amueller** [comment]
hm you are right, sorry for the noise. I think I had looked at two other version of the dataset? weird. These are indeed quite different.

**Comment by joaquinvanschoren** [comment]
No worries. Thanks for keeping a close eye!

**Comment by amueller** [comment]
I've gone through all the cc-18 datasets with dabl.plot_supervised, it's quite interesting.

**Comment by amueller** [comment]
What is the definition of synthetic vs generated now btw?
balance-scale seems quite artificial to me.

**Comment by mfeurer** [comment]
Please check the dropdown list 'detailed motivation of these decisions' in the [OpenML-CC18 section](https://docs.openml.org/benchmark/#openml-cc18) of the documentation.

**Comment by amueller** [comment]
We strived to remove artificial datasets as they, for example, come from textbooks and it is hard to reliably assess their difficulty. We admit that there is a blurred line between artificial and simulated datasets and do not have a perfect distinction between them (for example, a lot of phenomena can be simulated, but the outcome might be like a simple, artificial dataset). Therefore, we removed datasets if we were in doubt of whether they are simulated or artificial.

Is everything there is on the topic, right? balance-scale is a regular 4d grid of values and the decision boundary is a * b > c * d.
I guess it's a benchmark of whether an algorithm can learn interactions, and so it's not useless, but I would call it artificial.

**Comment by mfeurer** [comment]
Agreed. @joaquinvanschoren @janvanrijn @giuseppec @berndbischl @rgmantovani @mllg do we have a process for this?

**Comment by joaquinvanschoren** [comment]
So the proposal is to remove balance-scale (id 11) from the CC-18 because it is artificial, right?

I see that you already labeled it as 'artificial'. So if we agree it is a matter of removing the OpenML-CC18 label (removing it from study 99). We are left with 71 then.

**Comment by mfeurer** [comment]
CC @frank-hutter

**Comment by amueller** [comment]
I'm not sure how much it's worth changing cc-18 now, and how much the study 99 label should change but that's up to you folks.

I'm happy if we work on a newer version (cc-19?) and you get cc-18 out the door?
It would be pretty easy to get the number of datasets to 100 with all the suggestions I left in the tracker but I didn't have time to work on uploading them yet.
