### ISSUE TITLE
Dataset with 0 features in test server

### ISSUE THREAD

**Issue by ArlindKadra** [openml/OpenML#959]
`https://test.openml.org/d/59`

The above dataset shows up with 0 features. 
It forces an extra check in the functionality of unit tests.

**Comment by janvanrijn** [comment]
The dataset has features, but the evaluation engine failed to process it (did not comply with the xsd schema). 

I would actually suggest to refrain from creating tasks on datasets with these kind of problems.

**Comment by ArlindKadra** [comment]
@janvanrijn  I know, but since it was not processed, there is no way to check the number and type of features without using `get_dataset`. 
I am not creating tasks on these datasets, skipping the datasets adds an extra check which can be removed in the future, when datasets that are not processed are purged.

**Comment by janvanrijn** [comment]
The dataset will (most likely) not be processed, and there are more of those cases. It it not the responsibility of the task upload function to have knowledge about that. All it needs to know: dataset not processed (yet), we won't create a task. The user should upon receiving an error investigate.

**Comment by ArlindKadra** [comment]
> The dataset will (most likely) not be processed, and there are more of those cases. It it not the responsibility of the task upload function to have knowledge about that. All it needs to know: dataset not processed (yet), we won't create a task. The user should upon receiving an error investigate.

I think we are not understanding each other.

https://github.com/openml/openml-python/blob/dc9946c115fbe8f2816654470fabd49450c082e8/tests/test_tasks/test_task.py#L74

Regarding the task that I had to do, I am already past this 'problem'. The dataset being not processed forces some checks on the unit test code. If datasets like this are removed in the future from the server, the ifs on the unit test can be removed. It depends on what level you want to deal with this nuisance, since it is after all the test server.

Feel free to close the issue if you are fine with it.
