### ISSUE TITLE
Add sorting to list_evaluations

### ISSUE THREAD

**Issue by sahithyaravi1493** [openml/OpenML#962]
#### Description
`list_evaluations` does not have a sorting option. This means we need to list all evaluations of a particular task or flow and then sort, which takes too long.

#### Steps/Code to Reproduce
```
from openml import evaluations
evaluations.list_evaluations(function='predictive_accuracy', flow=[flow_id], ascending=False, size=100)
```

#### Expected Results
Returns the top 100 evaluations in terms of predictive_accuracy with given flow_id

#### Actual Results
Feature not present

**Comment by janvanrijn** [comment]
WDYT?

https://test.openml.org/api/v1/evaluation/list/task/115/function/predictive_accuracy/limit/10/sort/desc

Needs documentation obviously, and we might need to restrict it a bit (it makes the call slow if there are many results)

**Comment by mfeurer** [comment]
The link returns no results at the moment.

**Comment by joaquinvanschoren** [comment]
Now it does :). Looks good!

Does it always sort by score (value)? Could we also sort by other properties, like upload_time (or run_id)?

**Comment by joaquinvanschoren** [comment]
FYI, the filter is called 'sort_order' now:
https://test.openml.org/api/v1/evaluation/list/task/115/function/predictive_accuracy/limit/10/sort_order/desc

**Comment by joaquinvanschoren** [comment]
Added filter to docs: https://www.openml.org/api_docs#!/evaluation/get_evaluation_list_filters
