### ISSUE TITLE
OpenML 100 on test server only returns 99 tasks, even if deactivated entities are allowed.

### ISSUE THREAD

**Issue by PGijsbers** [openml/OpenML#980]
As per title. I expect that there should be 100 tasks in OpenML100 even on the test server, when `status/all` is included. However, the query [`https://test.openml.org/api/v1/xml/task/list/limit/10000/offset/0/tag/OpenML100/status/all`](https://test.openml.org/api/v1/xml/task/list/limit/10000/offset/0/tag/OpenML100/status/all) returns only 99 tasks.

**Comment by joaquinvanschoren** [comment]
This seems fixed? Can we close it?

**Comment by PGijsbers** [comment]
I wasn't aware that this was worked on/resolved itself. It seems to work fine now :tada:
