### ISSUE TITLE
No extension registered which can handle model

### ISSUE THREAD

**Issue by ajoeajoe** [openml/OpenML#981]
errors when try to load CC18 study datasets:

import openml
benchmark_suite = openml.study.get_study('OpenML-CC18', 'tasks')

**Comment by ajoeajoe** [comment]
I can fix it use study.get_suite('OpenML-CC18')
but when I run use the following codes，errors happened：

from openml import study,datasets, tasks, runs, flows, config
import sklearn
from sklearn import tree
from sklearn.impute import SimpleImputer
benchmark_suite = study.get_suite('OpenML-CC18') # obtain the benchmark suite
print(benchmark_suite.tasks)
clf = sklearn.pipeline.Pipeline(steps=[('imputer',SimpleImputer()),('estimator',tree.DecisionTreeClassifier())]) # build a sklearn classifier
for task_id in benchmark_suite.tasks: # iterate over all tasks
print(task_id)
task = tasks.get_task(task_id) # download the OpenML task
X, y = task.get_X_and_y() # get the data (not used in this example)
config.apikey = '' # set the OpenML Api Key
run = runs.run_model_on_task(task,clf) # run classifier on splits (requires API key)
score = run.get_metric_fn(sklearn.metrics.accuracy_score) # print accuracy score
print('Data set: %s; Accuracy: %0.2f' % (task.get_dataset().name,score.mean()))
run.publish() # publish the experiment on OpenML (optional)
print('URL for run: %s/run/%d' %(config.server,run.run_id))

**Comment by ajoeajoe** [comment]
ValueError Traceback (most recent call last)
in ()
12 X, y = task.get_X_and_y() # get the data (not used in this example)
13 config.apikey = '0e5ae5d3e3522ac3ee387344173e3a97' # set the OpenML Api Key
---> 14 run = runs.run_model_on_task(task,clf) # run classifier on splits (requires API key)
15 score = run.get_metric_fn(sklearn.metrics.accuracy_score) # print accuracy score
16 print('Data set: %s; Accuracy: %0.2f' % (task.get_dataset().name,score.mean()))

1 frames
/usr/local/lib/python3.6/dist-packages/openml/extensions/functions.py in get_extension_by_model(model, raise_if_no_extension)
91 if len(candidates) == 0:
92 if raise_if_no_extension:
---> 93 raise ValueError('No extension registered which can handle model: {}'.format(model))
94 else:
95 return None

ValueError: No extension registered which can handle model: <openml.tasks.task.OpenMLClassificationTask object at 0x7f68c50fe630>

**Comment by ajoeajoe** [comment]
I have remove my apikeys for private consideration

**Comment by mfeurer** [comment]
Fixed in https://github.com/openml/openml-python/pull/714. Will be available in the next release of openml-python. In the meantime, please swap the arguments `task,clf` to `clf,task` to fix this issue.

**Comment by aquemy** [comment]
@ajoeajoe your API key is still in the logs of the second comment: https://github.com/openml/OpenML/issues/981#issuecomment-501823463

**Comment by ajoeajoe** [comment]
@aquemy  thx
