### ISSUE TITLE
Add user name or ID to evaluation list.

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#982]
The frontend shows visualizations of evaluations (per task) including the user names. Currently, we need to do:
* List all evaluations for task X
* List all runs for task X
* Download runs to get the uploader name

This is very slow. To solve this, we need to either:
* Get the uploader name in the evaluation list
* Get the uploader ID in the evaluation list and a new call that returns a mapping from user ID to user name.

**Comment by joaquinvanschoren** [comment]
Hi, any updates? Ideas?

**Comment by joaquinvanschoren** [comment]
@sahithyaravi1493 can you please give an update on the status? Thanks!

**Comment by sahithyaravi1493** [comment]
@joaquinvanschoren I looked into this and I am planning to work on the changes next week
