### ISSUE TITLE
Flow 8784 on website but unavailable in API

### ISSUE THREAD

**Issue by PGijsbers** [openml/OpenML#992]
I can't retrieve flow 8784 through the API.
On the website: https://openml.org/f/8784
API: https://openml.org/api/v1/xml/flow/8784

It's also not listed: https://www.openml.org/api/v1/flow/list

**Comment by joaquinvanschoren** [comment]
Hi, this is just the search engine which had a stale result.
The flow does not exist in the database anymore.

**Comment by PGijsbers** [comment]
Thanks. It's no longer found through the search engine either.
